#include "chordmap_editor.h"
#include <commdlg.h>
#include <filesystem>
#include <stdexcept>
namespace producer::app {namespace {
enum:UINT{Documents=10,New,Open,Save,Undo,Redo,Name,NameSet,Nodes,NodeName,NodeAdd,NodeRename,NodeDelete,Links,Destination,Weight,Minimum,Maximum,LinkAdd,LinkSet,LinkDelete,Groups,Signs,SignAdd,SignSet,SignDelete,Status,Root,Chord,Scale,SubSet,Palette,PaletteLayer,PaletteChordMask,PaletteScaleMask,PaletteRoot,PaletteSet,PaletteCopy};
struct Session{Framework& host;size_t selected=0;};
HWND control(HWND w,const wchar_t* cls,const wchar_t* text,DWORD style,int x,int y,int a,int b,UINT id=0){auto c=CreateWindowW(cls,text,WS_CHILD|WS_VISIBLE|style,x,y,a,b,w,reinterpret_cast<HMENU>(static_cast<UINT_PTR>(id)),nullptr,nullptr);if(!c)throw std::runtime_error("Chordmap control creation failed");SendMessageW(c,WM_SETFONT,reinterpret_cast<WPARAM>(GetStockObject(DEFAULT_GUI_FONT)),TRUE);return c;}
std::wstring value(HWND w,UINT id){const auto c=GetDlgItem(w,id);const auto n=GetWindowTextLengthW(c);std::wstring s(n+1,L'\0');GetWindowTextW(c,s.data(),n+1);s.resize(n);return s;}
std::uint32_t number(HWND w,UINT id,bool hex=false){const auto text=value(w,id);if(text.empty()||text.find_first_not_of(hex?L"0123456789abcdefABCDEF":L"0123456789")!=std::wstring::npos)throw std::runtime_error("Enter digits (hex for masks)");auto n=std::stoull(text,nullptr,hex?16:10);if(n>UINT32_MAX)throw std::runtime_error("Value exceeds DWORD");return static_cast<std::uint32_t>(n);}
std::uint16_t word_value(HWND w,UINT id){const auto n=number(w,id);if(n>UINT16_MAX)throw std::runtime_error("Value exceeds WORD");return static_cast<std::uint16_t>(n);}
std::wstring file(HWND w,bool save){wchar_t path[32768]{};OPENFILENAMEW f{};f.lStructSize=sizeof(f);f.hwndOwner=w;f.lpstrFilter=L"Chordmap\0*.cdp;*.cdm\0\0";f.lpstrFile=path;f.nMaxFile=32768;f.lpstrDefExt=L"cdp";f.Flags=OFN_EXPLORER|OFN_NOCHANGEDIR|OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);if(!(save?GetSaveFileNameW(&f):GetOpenFileNameW(&f)))return L"";return path;}
size_t row(HWND w,UINT id){auto n=SendDlgItemMessageW(w,id,CB_GETCURSEL,0,0);if(n==CB_ERR)throw std::runtime_error("Select an item");return static_cast<size_t>(n);}
void text_number(HWND w,UINT id,std::uint32_t n){SetWindowTextW(GetDlgItem(w,id),std::to_wstring(n).c_str());}
std::wstring hex(std::uint32_t n){wchar_t b[16]{};swprintf_s(b,L"%X",n);return b;}
void link_selection(HWND w,Session& s){if(s.host.chordmaps().empty())return;const auto nr=SendDlgItemMessageW(w,Nodes,CB_GETCURSEL,0,0),lr=SendDlgItemMessageW(w,Links,CB_GETCURSEL,0,0);if(nr==CB_ERR||lr==CB_ERR)return;auto nodes=s.host.chordmap_document(s.selected).nodes();const auto& c=nodes.at(nr).connections.at(lr);text_number(w,Destination,c.destination);text_number(w,Weight,c.weight);text_number(w,Minimum,c.minBeats);text_number(w,Maximum,c.maxBeats);}
void node_selection(HWND w,Session& s){SendDlgItemMessageW(w,Links,CB_RESETCONTENT,0,0);if(s.host.chordmaps().empty())return;const auto r=SendDlgItemMessageW(w,Nodes,CB_GETCURSEL,0,0);if(r==CB_ERR)return;const auto nodes=s.host.chordmap_document(s.selected).nodes();const auto& n=nodes.at(r);SetWindowTextW(GetDlgItem(w,NodeName),n.name.c_str());if(!n.subchords.empty()){const auto& sub=n.subchords.front();text_number(w,Root,sub.root);SetWindowTextW(GetDlgItem(w,Chord),hex(sub.chord).c_str());SetWindowTextW(GetDlgItem(w,Scale),hex(sub.scale).c_str());}for(const auto& c:n.connections){const auto t=L"To "+std::to_wstring(c.destination)+L"; weight "+std::to_wstring(c.weight)+L"; beats "+std::to_wstring(c.minBeats)+L".."+std::to_wstring(c.maxBeats);SendDlgItemMessageW(w,Links,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(t.c_str()));}SendDlgItemMessageW(w,Links,CB_SETCURSEL,0,0);link_selection(w,s);}
void sign_selection(HWND w,Session& s){if(s.host.chordmaps().empty())return;const auto r=SendDlgItemMessageW(w,Signs,CB_GETCURSEL,0,0);if(r!=CB_ERR)SetWindowTextW(GetDlgItem(w,Groups),hex(s.host.chordmap_document(s.selected).signposts().at(r).groups).c_str());}
void palette_selection(HWND w,Session& s){
    if(s.host.chordmaps().empty())return;const auto item=SendDlgItemMessageW(w,Palette,CB_GETCURSEL,0,0),layer=SendDlgItemMessageW(w,PaletteLayer,CB_GETCURSEL,0,0);if(item==CB_ERR||layer==CB_ERR)return;
    const auto entries=s.host.chordmap_document(s.selected).palette();if(static_cast<size_t>(item)>=entries.size()||static_cast<size_t>(layer)>=entries[item].subchords.size())return;
    const auto& sub=entries[item].subchords[layer];SetWindowTextW(GetDlgItem(w,PaletteRoot),(L"Fixed root: "+std::to_wstring(sub.root)).c_str());SetWindowTextW(GetDlgItem(w,PaletteChordMask),hex(sub.chord).c_str());SetWindowTextW(GetDlgItem(w,PaletteScaleMask),hex(sub.scale).c_str());
}
void refresh(HWND w,Session& s){const auto previous=SendDlgItemMessageW(w,Nodes,CB_GETCURSEL,0,0),palettePrevious=SendDlgItemMessageW(w,Palette,CB_GETCURSEL,0,0);for(const auto id:{Documents,Nodes,Links,Signs,Palette})SendDlgItemMessageW(w,id,CB_RESETCONTENT,0,0);const auto& owned=s.host.chordmaps();for(const auto& d:owned){const auto t=d.document->name()+(d.document->dirty()?L" *":L"")+L" — "+(d.path.empty()?L"unsaved":std::filesystem::path(d.path).filename().wstring());SendDlgItemMessageW(w,Documents,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(t.c_str()));}const bool present=!owned.empty();for(const auto id:{Save,Undo,Redo,Name,NameSet,Nodes,NodeName,NodeAdd,NodeRename,NodeDelete,Links,Destination,Weight,Minimum,Maximum,LinkAdd,LinkSet,LinkDelete,Groups,Signs,SignAdd,SignSet,SignDelete,Root,Chord,Scale,SubSet,Palette,PaletteLayer,PaletteChordMask,PaletteScaleMask,PaletteSet,PaletteCopy})EnableWindow(GetDlgItem(w,id),present);if(!present)return;if(s.selected>=owned.size())s.selected=owned.size()-1;SendDlgItemMessageW(w,Documents,CB_SETCURSEL,s.selected,0);auto& doc=s.host.chordmap_document(s.selected);SetWindowTextW(GetDlgItem(w,Name),doc.name().c_str());auto nodes=doc.nodes();for(const auto& n:nodes){const auto t=std::to_wstring(n.id)+L": "+n.name+L" ("+std::to_wstring(n.subchords.size())+L" subchords)";SendDlgItemMessageW(w,Nodes,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(t.c_str()));}SendDlgItemMessageW(w,Nodes,CB_SETCURSEL,previous>=0&&static_cast<size_t>(previous)<nodes.size()?previous:0,0);node_selection(w,s);for(const auto& p:doc.signposts()){const auto t=p.name+L"; groups "+hex(p.groups)+L"; cadences "+std::to_wstring(p.cadences);SendDlgItemMessageW(w,Signs,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(t.c_str()));}SendDlgItemMessageW(w,Signs,CB_SETCURSEL,0,0);sign_selection(w,s);for(const auto& p:doc.palette()){const auto t=p.name+L"; root "+(p.subchords.empty()?L"?":std::to_wstring(p.subchords[0].root));SendDlgItemMessageW(w,Palette,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(t.c_str()));}SendDlgItemMessageW(w,Palette,CB_SETCURSEL,palettePrevious>=0&&static_cast<size_t>(palettePrevious)<doc.palette().size()?palettePrevious:0,0);palette_selection(w,s);SetWindowTextW(GetDlgItem(w,Status),L"Save each Chordmap, then Save Project. Destination 0 ends a path. Groups: 1..7 / A..F; hex mask 7F3F. Imported design layouts restrict node insertion/deletion.");}
LRESULT CALLBACK proc(HWND w,UINT msg,WPARAM wp,LPARAM lp){auto s=reinterpret_cast<Session*>(GetWindowLongPtrW(w,GWLP_USERDATA));try{
 if(msg==WM_CREATE){s=static_cast<Session*>(reinterpret_cast<CREATESTRUCTW*>(lp)->lpCreateParams);SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(s));
 control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP|WS_VSCROLL,16,16,660,200,Documents);
 int x=16;for(const auto b:std::initializer_list<std::pair<UINT,const wchar_t*>>{{New,L"New"},{Open,L"Open..."},{Save,L"Save As..."},{Undo,L"Undo"},{Redo,L"Redo"}}){control(w,L"BUTTON",b.second,WS_TABSTOP,x,54,120,28,b.first);x+=130;}
 control(w,L"STATIC",L"Chordmap name",0,16,94,150,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,170,90,350,26,Name);control(w,L"BUTTON",L"Set Name",WS_TABSTOP,534,90,140,28,NameSet);
 control(w,L"STATIC",L"Chord nodes",0,16,132,150,22);control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP|WS_VSCROLL,170,128,504,250,Nodes);
 control(w,L"EDIT",L"C",WS_BORDER|WS_TABSTOP,16,168,250,26,NodeName);control(w,L"BUTTON",L"Insert Node",WS_TABSTOP,280,168,120,28,NodeAdd);control(w,L"BUTTON",L"Rename",WS_TABSTOP,412,168,120,28,NodeRename);control(w,L"BUTTON",L"Delete Node",WS_TABSTOP,544,168,130,28,NodeDelete);
 control(w,L"STATIC",L"First subchord: root / chord mask / scale mask",0,16,208,400,22);control(w,L"EDIT",L"0",WS_BORDER|WS_TABSTOP,16,234,64,26,Root);control(w,L"EDIT",L"91",WS_BORDER|WS_TABSTOP,94,234,160,26,Chord);control(w,L"EDIT",L"AB5",WS_BORDER|WS_TABSTOP,268,234,160,26,Scale);control(w,L"BUTTON",L"Set Subchord",WS_TABSTOP,442,234,232,28,SubSet);
 control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP|WS_VSCROLL,16,282,658,200,Links);
 const UINT edits[]={Destination,Weight,Minimum,Maximum};const wchar_t* labels[]={L"Destination ID",L"Weight (0..100)",L"Minimum beats",L"Maximum beats"};const wchar_t* defaults[]={L"0",L"50",L"1",L"4"};for(int i=0;i<4;++i){control(w,L"STATIC",labels[i],0,16+i*165,322,155,22);control(w,L"EDIT",defaults[i],WS_BORDER|WS_TABSTOP,16+i*165,350,150,26,edits[i]);}
 control(w,L"BUTTON",L"Insert Connection",WS_TABSTOP,16,392,210,28,LinkAdd);control(w,L"BUTTON",L"Set Connection",WS_TABSTOP,240,392,210,28,LinkSet);control(w,L"BUTTON",L"Delete Connection",WS_TABSTOP,464,392,210,28,LinkDelete);
 control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP|WS_VSCROLL,16,438,658,200,Signs);control(w,L"STATIC",L"Signpost group mask (hex)",0,16,480,250,22);control(w,L"EDIT",L"1",WS_BORDER|WS_TABSTOP,280,476,150,26,Groups);
 control(w,L"BUTTON",L"Add Node as Signpost",WS_TABSTOP,16,520,210,28,SignAdd);control(w,L"BUTTON",L"Set Groups",WS_TABSTOP,240,520,210,28,SignSet);control(w,L"BUTTON",L"Delete Signpost",WS_TABSTOP,464,520,210,28,SignDelete);control(w,L"STATIC",L"",0,16,564,658,36,Status);control(w,L"STATIC",L"Palette chord / layer (root is fixed)",0,16,604,650,22);
 control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP|WS_VSCROLL,16,632,350,250,Palette);control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,380,632,140,150,PaletteLayer);for(int k=1;k<=4;++k){const auto label=L"Layer "+std::to_wstring(k);SendDlgItemMessageW(w,PaletteLayer,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(label.c_str()));}SendDlgItemMessageW(w,PaletteLayer,CB_SETCURSEL,0,0);
 control(w,L"STATIC",L"Fixed root",0,532,638,142,22,PaletteRoot);control(w,L"STATIC",L"Chord mask (hex)",0,16,676,180,22);control(w,L"STATIC",L"Scale mask (hex)",0,370,676,148,22);
 control(w,L"EDIT",L"91",WS_BORDER|WS_TABSTOP,202,672,152,26,PaletteChordMask);control(w,L"EDIT",L"AB5AB5",WS_BORDER|WS_TABSTOP,520,672,154,26,PaletteScaleMask);
 control(w,L"BUTTON",L"Set Palette Layer",WS_TABSTOP,16,710,314,28,PaletteSet);control(w,L"BUTTON",L"Copy Palette to New Node",WS_TABSTOP,348,710,326,28,PaletteCopy);
 refresh(w,*s);return 0;}
 if(msg==WM_COMMAND&&s){const auto id=LOWORD(wp);if(HIWORD(wp)==CBN_SELCHANGE){if(id==Documents){s->selected=row(w,Documents);refresh(w,*s);}else if(id==Nodes)node_selection(w,*s);else if(id==Links)link_selection(w,*s);else if(id==Signs)sign_selection(w,*s);else if(id==Palette||id==PaletteLayer)palette_selection(w,*s);return 0;}if(HIWORD(wp)!=BN_CLICKED)return 0;
 if(id==New)s->selected=s->host.new_chordmap();else if(id==Open){const auto path=file(w,false);if(path.empty())return 0;s->selected=s->host.open_chordmap(path);}else if(id==Save){const auto path=file(w,true);if(path.empty())return 0;s->host.save_chordmap(s->selected,path);}else{auto& d=s->host.chordmap_document(s->selected);bool changed=false;const auto selected_node=[&](){return d.nodes().at(row(w,Nodes)).id;};switch(id){case PaletteSet:{const auto item=row(w,Palette),layer=row(w,PaletteLayer);auto sub=d.palette().at(item).subchords.at(layer);sub.chord=number(w,PaletteChordMask,true);sub.scale=number(w,PaletteScaleMask,true);changed=d.edit_palette_subchord(item,layer,sub);break;}case PaletteCopy:changed=d.insert_palette_node(row(w,Palette));break;case Undo:changed=d.undo();break;case Redo:changed=d.redo();break;case NameSet:changed=d.set_name(value(w,Name));break;case NodeAdd:changed=d.insert_node(value(w,NodeName),{});break;case NodeRename:changed=d.rename_node(selected_node(),value(w,NodeName));break;case NodeDelete:changed=d.delete_node(selected_node());break;case SubSet:{const auto nodes=d.nodes();auto sub=nodes.at(row(w,Nodes)).subchords.at(0);const auto root=number(w,Root);if(root>=24)throw std::runtime_error("Root must be below 24");sub.root=static_cast<std::uint8_t>(root);sub.chord=number(w,Chord,true);sub.scale=number(w,Scale,true);changed=d.edit_subchord(selected_node(),0,sub);break;}case LinkAdd:case LinkSet:{ChordMapConnection c{};if(id==LinkSet)c=d.nodes().at(row(w,Nodes)).connections.at(row(w,Links));c.destination=word_value(w,Destination);c.weight=word_value(w,Weight);c.minBeats=word_value(w,Minimum);c.maxBeats=word_value(w,Maximum);changed=id==LinkAdd?d.insert_connection(selected_node(),c):d.set_connection(selected_node(),row(w,Links),c);break;}case LinkDelete:changed=d.delete_connection(selected_node(),row(w,Links));break;case SignAdd:changed=d.insert_signpost(selected_node(),number(w,Groups,true));break;case SignSet:changed=d.set_signpost_groups(row(w,Signs),number(w,Groups,true));break;case SignDelete:changed=d.delete_signpost(row(w,Signs));break;default:return 0;}if(!changed)throw std::runtime_error("Unchanged or invalid edit");}refresh(w,*s);return 0;
 }if(msg==WM_CLOSE){DestroyWindow(w);return 0;}
 }catch(const std::exception& e){const std::string detail=e.what();MessageBoxW(w,std::wstring(detail.begin(),detail.end()).c_str(),L"Chordmap",MB_OK|MB_ICONERROR);if(msg==WM_CREATE)return -1;}return DefWindowProcW(w,msg,wp,lp);}
}
void show_chordmap_editor(HWND parent,Framework& host,size_t initialIndex){const auto instance=GetModuleHandleW(nullptr);static bool registered=false;if(!registered){WNDCLASSW c{};c.hInstance=instance;c.lpfnWndProc=proc;c.hCursor=LoadCursorW(nullptr,IDC_ARROW);c.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);c.lpszClassName=L"SourceProducerChordmaps";if(!RegisterClassW(&c))throw std::runtime_error("Chordmap window registration failed");registered=true;}Session session{host};session.selected=initialIndex;const auto w=CreateWindowExW(WS_EX_APPWINDOW,L"SourceProducerChordmaps",L"Chordmap Documents",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,0,714,790,nullptr,nullptr,instance,&session);if(!w)throw std::runtime_error("Chordmap window creation failed");const bool enabled=IsWindowEnabled(parent)!=FALSE;EnableWindow(parent,FALSE);ShowWindow(w,SW_SHOW);UpdateWindow(w);MSG msg{};BOOL result=1;while(IsWindow(w)&&(result=GetMessageW(&msg,nullptr,0,0))>0)if(!IsDialogMessageW(w,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}if(IsWindow(w))DestroyWindow(w);EnableWindow(parent,enabled);SetActiveWindow(parent);if(result==0)PostQuitMessage(static_cast<int>(msg.wParam));if(result==-1)throw std::runtime_error("Chordmap message loop failed");}
}

