#include "container_editor.h"
#include <commdlg.h>
#include <filesystem>
#include <stdexcept>
namespace producer::app {namespace {
enum:UINT {Documents=10,New,Open,Save,Undo,Redo,Name,ApplyName,Objects,Alias,Keep,NoLoads,Apply,Segments,Add,Remove,Status,Embed,Reference,Runtime};
struct Session{Framework& host;size_t selected=0,object=0;std::vector<size_t> available;};
void control(HWND w,const wchar_t* cls,const wchar_t* value,DWORD flags,int x,int y,int width,int height,UINT id=0){CreateWindowW(cls,value,WS_CHILD|WS_VISIBLE|flags,x,y,width,height,w,reinterpret_cast<HMENU>(static_cast<UINT_PTR>(id)),GetModuleHandleW(nullptr),nullptr);}
std::wstring text(HWND w,UINT id){auto c=GetDlgItem(w,id);std::wstring v(GetWindowTextLengthW(c)+1,0);GetWindowTextW(c,v.data(),static_cast<int>(v.size()));v.pop_back();return v;}
std::wstring file(HWND w,bool save,bool runtime=false){wchar_t path[32768]{};OPENFILENAMEW f{};f.lStructSize=sizeof(f);f.hwndOwner=w;f.lpstrFile=path;f.nMaxFile=32768;f.lpstrFilter=runtime?L"Runtime Container\0*.con\0":L"Producer Container\0*.cop;*.con\0";f.lpstrDefExt=runtime?L"con":L"cop";f.Flags=OFN_EXPLORER|OFN_PATHMUSTEXIST|OFN_NOCHANGEDIR|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);return(save?GetSaveFileNameW(&f):GetOpenFileNameW(&f))?path:L"";}
void refresh(HWND w,Session& s){
    SendDlgItemMessageW(w,Documents,CB_RESETCONTENT,0,0);for(const auto& e:s.host.containers()){auto name=e.document->name().empty()?(e.path.empty()?L"Untitled Container":std::filesystem::path(e.path).filename().wstring()):e.document->name();if(e.document->dirty())name+=L" *";SendDlgItemMessageW(w,Documents,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(name.c_str()));}
    const bool present=!s.host.containers().empty();for(auto id:{Save,Undo,Redo,Name,ApplyName,Objects,Alias,Keep,NoLoads,Apply,Add,Remove,Embed,Reference,Runtime})EnableWindow(GetDlgItem(w,id),present);SendDlgItemMessageW(w,Objects,CB_RESETCONTENT,0,0);SendDlgItemMessageW(w,Segments,CB_RESETCONTENT,0,0);s.available.clear();
    for(size_t i=0;i<s.host.documents().size();++i){const auto& e=s.host.documents()[i];if(e.path.empty())continue;s.available.push_back(i);auto name=std::filesystem::path(e.path).filename().wstring();SendDlgItemMessageW(w,Segments,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(name.c_str()));}SendDlgItemMessageW(w,Segments,CB_SETCURSEL,0,0);EnableWindow(GetDlgItem(w,Add),present&&!s.available.empty());
    if(!present){SetWindowTextW(GetDlgItem(w,Status),L"Create or open a standalone Container.");return;}if(s.selected>=s.host.containers().size())s.selected=0;SendDlgItemMessageW(w,Documents,CB_SETCURSEL,s.selected,0);auto& d=s.host.container_document(s.selected);SetWindowTextW(GetDlgItem(w,Name),d.name().c_str());auto objects=d.graph().objects();for(size_t i=0;i<objects.size();++i){auto label=std::to_wstring(i+1)+L": "+objects[i].alias.value_or(L"(no alias)")+(objects[i].referenceRuntime?L" [Reference Runtime]":L" [Embed Runtime]");SendDlgItemMessageW(w,Objects,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(label.c_str()));}if(s.object>=objects.size())s.object=0;for(auto id:{Alias,Keep,Remove,Embed,Reference})EnableWindow(GetDlgItem(w,id),!objects.empty());SetWindowTextW(GetDlgItem(w,Alias),objects.empty()?L"":objects[s.object].alias.value_or(L"").c_str());SendDlgItemMessageW(w,Keep,BM_SETCHECK,!objects.empty()&&(objects[s.object].flags&1)?BST_CHECKED:BST_UNCHECKED,0);SendDlgItemMessageW(w,NoLoads,BM_SETCHECK,d.graph().flags()&2?BST_CHECKED:BST_UNCHECKED,0);SendDlgItemMessageW(w,Objects,CB_SETCURSEL,s.object,0);
    SetWindowTextW(GetDlgItem(w,Status),L"Choose Embed Runtime or Reference Runtime for the selected object. Save design Container then Project; Save Runtime writes the .con copy. Saved Segment and native Project required.");
}
LRESULT CALLBACK proc(HWND w,UINT msg,WPARAM wp,LPARAM lp){auto s=reinterpret_cast<Session*>(GetWindowLongPtrW(w,GWLP_USERDATA));try{
    if(msg==WM_CREATE){s=static_cast<Session*>(reinterpret_cast<CREATESTRUCTW*>(lp)->lpCreateParams);SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(s));control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,16,12,720,180,Documents);control(w,L"BUTTON",L"New",WS_TABSTOP,16,50,110,28,New);control(w,L"BUTTON",L"Open...",WS_TABSTOP,136,50,110,28,Open);control(w,L"BUTTON",L"Save As...",WS_TABSTOP,256,50,110,28,Save);control(w,L"BUTTON",L"Undo",WS_TABSTOP,376,50,110,28,Undo);control(w,L"BUTTON",L"Redo",WS_TABSTOP,496,50,110,28,Redo);control(w,L"STATIC",L"Container name",0,16,90,110,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,130,90,430,25,Name);control(w,L"BUTTON",L"Apply Name",WS_TABSTOP,580,88,156,28,ApplyName);control(w,L"STATIC",L"Contained object",0,16,130,130,24);control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,150,130,586,180,Objects);control(w,L"STATIC",L"Alias",0,16,170,100,24);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,120,170,616,25,Alias);control(w,L"BUTTON",L"Keep cached",BS_AUTOCHECKBOX|WS_TABSTOP,16,210,180,25,Keep);control(w,L"BUTTON",L"Do not preload objects",BS_AUTOCHECKBOX|WS_TABSTOP,210,210,260,25,NoLoads);control(w,L"BUTTON",L"Apply Properties",WS_TABSTOP,500,208,236,28,Apply);control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,16,260,360,180,Segments);control(w,L"BUTTON",L"Add Reference Runtime",WS_TABSTOP,390,258,220,28,Add);control(w,L"BUTTON",L"Remove",WS_TABSTOP,620,258,116,28,Remove);control(w,L"BUTTON",L"Use Embed Runtime",WS_TABSTOP,16,302,220,28,Embed);control(w,L"BUTTON",L"Use Reference Runtime",WS_TABSTOP,256,302,240,28,Reference);control(w,L"BUTTON",L"Save Runtime...",WS_TABSTOP,516,302,220,28,Runtime);control(w,L"STATIC",L"",0,16,346,720,100,Status);refresh(w,*s);return 0;}
    if(msg==WM_COMMAND&&s){const auto id=LOWORD(wp);if(id==Documents&&HIWORD(wp)==CBN_SELCHANGE){s->selected=static_cast<size_t>(SendDlgItemMessageW(w,Documents,CB_GETCURSEL,0,0));refresh(w,*s);return 0;}if(id==Objects&&HIWORD(wp)==CBN_SELCHANGE){s->object=static_cast<size_t>(SendDlgItemMessageW(w,Objects,CB_GETCURSEL,0,0));refresh(w,*s);return 0;}if(HIWORD(wp)!=BN_CLICKED)return 0;
        if(id==New)s->selected=s->host.new_container();else if(id==Open){auto p=file(w,false);if(p.empty())return 0;s->selected=s->host.open_container(p);}else if(id==Save){auto p=file(w,true);if(p.empty())return 0;s->host.save_container(s->selected,p);}else if(id==Runtime){auto p=file(w,true,true);if(p.empty())return 0;s->host.save_runtime_as(RuntimeDocumentKind::Container,s->selected,p);}else if(id==Embed||id==Reference){auto& d=s->host.container_document(s->selected);const auto objects=d.graph().objects();if(!objects.empty()&&objects[s->object].referenceRuntime!=(id==Reference)&&!d.set_reference_runtime(s->object,id==Reference))throw std::runtime_error("Runtime membership requires a design link");}else if(id==Undo)s->host.container_document(s->selected).undo();else if(id==Redo)s->host.container_document(s->selected).redo();else if(id==ApplyName){auto& d=s->host.container_document(s->selected);auto value=text(w,Name);if(value!=d.name()&&!d.set_name(value))throw std::runtime_error("Invalid Container name");}else if(id==Add){const auto i=SendDlgItemMessageW(w,Segments,CB_GETCURSEL,0,0);if(i==CB_ERR)return 0;auto segment=s->available.at(static_cast<size_t>(i));auto alias=std::filesystem::path(s->host.documents()[segment].path).stem().wstring();if(!s->host.add_container_segment_reference(s->selected,segment,alias))throw std::runtime_error("Save native Project, .cop and .sgp in the same directory before adding a distinct reference");s->object=s->host.container_document(s->selected).graph().objects().size()-1;}else if(id==Remove){if(!s->host.container_document(s->selected).remove_object(s->object))throw std::runtime_error("Object removal rejected");}else if(id==Apply){auto& d=s->host.container_document(s->selected);auto objects=d.graph().objects();if(!objects.empty()){auto alias=text(w,Alias);bool keep=SendDlgItemMessageW(w,Keep,BM_GETCHECK,0,0)==BST_CHECKED;if((alias!=objects[s->object].alias.value_or(L"")||keep!=bool(objects[s->object].flags&1))&&!d.set_object_properties(s->object,alias,keep))throw std::runtime_error("Container object properties rejected");}d.set_no_loads(SendDlgItemMessageW(w,NoLoads,BM_GETCHECK,0,0)==BST_CHECKED);}else return 0;refresh(w,*s);return 0;
    }
    if(msg==WM_CLOSE){DestroyWindow(w);return 0;}
}catch(const std::exception& e){MessageBoxA(w,e.what(),"Container operation failed",MB_OK|MB_ICONERROR);return 0;}return DefWindowProcW(w,msg,wp,lp);}
}
void show_container_documents(HWND parent,Framework& host,size_t initialIndex){const auto instance=GetModuleHandleW(nullptr);static bool registered=false;if(!registered){WNDCLASSW c{};c.hInstance=instance;c.lpfnWndProc=proc;c.hCursor=LoadCursorW(nullptr,IDC_ARROW);c.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);c.lpszClassName=L"SourceProducerContainerDocuments";if(!RegisterClassW(&c))throw std::runtime_error("Container class registration failed");registered=true;}Session s{host};s.selected=initialIndex;auto w=CreateWindowExW(WS_EX_APPWINDOW,L"SourceProducerContainerDocuments",L"Container Documents",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,780,490,nullptr,nullptr,instance,&s);if(!w)throw std::runtime_error("Container window creation failed");bool enabled=IsWindowEnabled(parent)!=FALSE;EnableWindow(parent,FALSE);ShowWindow(w,SW_SHOW);MSG msg{};BOOL result=1;while(IsWindow(w)&&(result=GetMessageW(&msg,nullptr,0,0))>0)if(!IsDialogMessageW(w,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}if(IsWindow(w))DestroyWindow(w);EnableWindow(parent,enabled);SetActiveWindow(parent);if(!result)PostQuitMessage(static_cast<int>(msg.wParam));if(result<0)throw std::runtime_error("Container message loop failed");}
}
