#include "param_control.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <stdexcept>
namespace producer::app {
const ParamGuid param_time_music={0x9d,0xc4,0x74,0x05,0x04,0x5b,0x15,0x4b,0xa5,0x42,0xae,0x28,0x20,0x30,0x11,0x7b};
const ParamGuid param_time_reference={0x2b,0x71,0xad,0x93,0xa0,0xda,0xfe,0x4f,0xbc,0x81,0xb0,0xce,0x50,0x0f,0xcd,0xd9};
namespace {
Chunk leaf(const char* id,Bytes bytes){Chunk c;c.id=id;c.data=std::move(bytes);return c;}
Chunk list(const char* type,std::vector<Chunk> children={}){Chunk c;c.id="LIST";c.type=type;c.children=std::move(children);return c;}
template<class C> auto unique(C& c,const char* id,const char* type="")->decltype(c.find(id)){decltype(c.find(id)) found=nullptr;for(auto& child:c.children)if(child.id==id&&child.type==type){if(found)throw std::runtime_error("Ambiguous Parameter Control chunk");found=&child;}return found;}
template<class C> auto nth(C& c,const char* type,size_t index)->decltype(c.find("LIST")){for(auto& child:c.children)if(child.id=="LIST"&&child.type==type){if(!index--)return &child;}return nullptr;}
ParamObject address(const Bytes& b){if(b.size()<52||read32(b,0))throw std::runtime_error("Invalid Parameter Control object header");ParamObject a;std::copy_n(b.begin()+4,16,a.timeFormat.begin());a.pchannel=read32(b,20);a.stage=read32(b,24);a.buffer=read32(b,28);std::copy_n(b.begin()+32,16,a.objectClass.begin());a.index=read32(b,48);if(!valid_param_object(a))throw std::runtime_error("Unsupported parameter time format");return a;}
void encode(Bytes& b,const ParamObject& a){put32(b,0,0);std::copy(a.timeFormat.begin(),a.timeFormat.end(),b.begin()+4);put32(b,20,a.pchannel);put32(b,24,a.stage);put32(b,28,a.buffer);std::copy(a.objectClass.begin(),a.objectClass.end(),b.begin()+32);put32(b,48,a.index);}
ParamCurve curve(const Bytes& b){if(b.size()<24)throw std::runtime_error("Truncated Parameter Control curve");ParamCurve v;v.start=static_cast<std::int32_t>(read32(b,0));v.end=static_cast<std::int32_t>(read32(b,4));std::memcpy(&v.startValue,b.data()+8,4);std::memcpy(&v.endValue,b.data()+12,4);v.type=read32(b,16);v.flags=read32(b,20);if(!valid_param_curve(v))throw std::runtime_error("Invalid Parameter Control curve");return v;}
void encode(Bytes& b,const ParamCurve& v){put32(b,0,static_cast<std::uint32_t>(v.start));put32(b,4,static_cast<std::uint32_t>(v.end));std::memcpy(b.data()+8,&v.startValue,4);std::memcpy(b.data()+12,&v.endValue,4);put32(b,16,v.type);put32(b,20,v.flags);}
struct Record{Bytes bytes;ParamCurve value;bool selected=false;};
std::vector<Record> records(const Chunk& p){auto c=unique(p,"prcc");if(!c||c->data.size()<4)throw std::runtime_error("Parameter Control curves missing");const auto stride=read32(c->data,0);if(stride<24||(c->data.size()-4)%stride)throw std::runtime_error("Invalid Parameter Control stride/tail");std::vector<Record> out;for(size_t i=4;i<c->data.size();i+=stride){Bytes b(c->data.begin()+i,c->data.begin()+i+stride);auto v=curve(b);if(!out.empty()&&out.back().value.start>v.start)throw std::runtime_error("Unsorted Parameter Control curves");out.push_back({std::move(b),v});}return out;}
std::uint32_t parameter_index(const Chunk& p){auto h=unique(p,"prph");if(!h||h->data.size()<8||read32(h->data,0))throw std::runtime_error("Invalid Parameter Control parameter header");return read32(h->data,4);}
Chunk* parameter(Chunk& t,size_t oi,size_t pi){auto l=unique(t,"LIST","prmt");if(!l)return nullptr;auto o=nth(*l,"prol",oi);return o?nth(*o,"prpl",pi):nullptr;}
bool publish(Chunk& t,Chunk next){(void)param_control_objects(next);if(t.encode()==next.encode())return false;t=std::move(next);return true;}
void write_records(Chunk& p,std::vector<Record> r,size_t* result){std::stable_sort(r.begin(),r.end(),[](const Record& a,const Record& b){return a.value.start<b.value.start;});auto c=unique(p,"prcc");auto n=read32(c->data,0);Bytes b(4);put32(b,0,n);size_t selected=0;for(size_t i=0;i<r.size();++i){auto v=r[i].bytes;if(v.size()>n)throw std::runtime_error("Curve extension cannot fit destination stride");v.resize(n);encode(v,r[i].value);b.insert(b.end(),v.begin(),v.end());if(r[i].selected)selected=i;}c->data=std::move(b);if(result)*result=selected;}
bool erase_list(Chunk& c,const char* type,size_t index){for(auto it=c.children.begin();it!=c.children.end();++it)if(it->id=="LIST"&&it->type==type){if(!index--){c.children.erase(it);return true;}}return false;}
}
bool valid_param_object(const ParamObject& a){return a.timeFormat==param_time_music||a.timeFormat==param_time_reference;}
bool valid_param_curve(const ParamCurve& v){return v.start<=v.end&&std::isfinite(v.startValue)&&std::isfinite(v.endValue)&&(v.type==1||v.type==2||v.type==4||v.type==8||v.type==16)&&!(v.flags&~3u);}
std::vector<ParamControlObject> param_control_objects(const Chunk& t){std::vector<ParamControlObject> out;auto l=unique(t,"LIST","prmt");if(!l)throw std::runtime_error("Parameter Control list missing");for(const auto& o:l->children)if(o.id=="LIST"&&o.type=="prol"){auto h=unique(o,"proh");if(!h)throw std::runtime_error("Parameter Control object header missing");ParamControlObject v;v.address=address(h->data);for(const auto& p:o.children)if(p.id=="LIST"&&p.type=="prpl"){ParamParameter x;x.index=parameter_index(p);for(const auto& r:records(p))x.curves.push_back(r.value);v.parameters.push_back(std::move(x));}out.push_back(std::move(v));}return out;}
Chunk param_control_track(){Chunk t;t.id="RIFF";t.type="DMTK";Bytes h(32);const Bytes id={0x7b,0x53,0xe0,0x4b,0x19,0x5c,0xd3,0x11,0x8b,0xdc,0x00,0x60,0x08,0x93,0xb1,0xb6};std::copy(id.begin(),id.end(),h.begin());put32(h,20,1);std::memcpy(h.data()+28,"prmt",4);Bytes x(8);put32(x,0,0x38);t.children={leaf("trkh",h),leaf("trkx",x),list("prmt")};return t;}
bool add_param_object(Chunk& t,const ParamObject& a){if(!valid_param_object(a))return false;(void)param_control_objects(t);auto next=t;auto l=unique(next,"LIST","prmt");if(!l){next.children.push_back(list("prmt"));l=&next.children.back();}Bytes h(52);encode(h,a);l->children.push_back(list("prol",{leaf("proh",h)}));return publish(t,std::move(next));}
bool edit_param_object(Chunk& t,size_t i,const ParamObject& a){if(!valid_param_object(a))return false;(void)param_control_objects(t);auto next=t;auto l=unique(next,"LIST","prmt");auto o=l?nth(*l,"prol",i):nullptr;if(!o)return false;encode(unique(*o,"proh")->data,a);return publish(t,std::move(next));}
bool delete_param_object(Chunk& t,size_t i){(void)param_control_objects(t);auto next=t;auto l=unique(next,"LIST","prmt");return l&&erase_list(*l,"prol",i)&&publish(t,std::move(next));}
bool add_param_parameter(Chunk& t,size_t oi,std::uint32_t index){(void)param_control_objects(t);auto next=t;auto l=unique(next,"LIST","prmt");auto o=l?nth(*l,"prol",oi):nullptr;if(!o)return false;for(const auto& p:o->children)if(p.id=="LIST"&&p.type=="prpl"&&parameter_index(p)==index)return false;Bytes h(8),c(4);put32(h,4,index);put32(c,0,24);o->children.push_back(list("prpl",{leaf("prph",h),leaf("prcc",c)}));return publish(t,std::move(next));}
bool delete_param_parameter(Chunk& t,size_t oi,size_t pi){(void)param_control_objects(t);auto next=t;auto l=unique(next,"LIST","prmt");auto o=l?nth(*l,"prol",oi):nullptr;return o&&erase_list(*o,"prpl",pi)&&publish(t,std::move(next));}
bool add_param_curve(Chunk& t,size_t oi,size_t pi,const ParamCurve& v,size_t* result){if(!valid_param_curve(v))return false;(void)param_control_objects(t);auto next=t;auto p=parameter(next,oi,pi);if(!p)return false;auto r=records(*p);r.push_back({Bytes(read32(unique(*p,"prcc")->data,0)),v,true});size_t picked=0;write_records(*p,std::move(r),&picked);if(!publish(t,std::move(next)))return false;if(result)*result=picked;return true;}
bool edit_param_curve(Chunk& t,size_t oi,size_t pi,size_t ci,const ParamCurve& v,size_t* result){if(!valid_param_curve(v))return false;(void)param_control_objects(t);auto next=t;auto p=parameter(next,oi,pi);if(!p)return false;auto r=records(*p);if(ci>=r.size())return false;r[ci].value=v;r[ci].selected=true;size_t picked=0;write_records(*p,std::move(r),&picked);if(!publish(t,std::move(next)))return false;if(result)*result=picked;return true;}
bool delete_param_curve(Chunk& t,size_t oi,size_t pi,size_t ci){(void)param_control_objects(t);auto next=t;auto p=parameter(next,oi,pi);if(!p)return false;auto r=records(*p);if(ci>=r.size())return false;r.erase(r.begin()+ci);write_records(*p,std::move(r),nullptr);return publish(t,std::move(next));}
Bytes copy_param_curve(const Chunk& t,size_t oi,size_t pi,size_t ci){auto next=t;auto p=parameter(next,oi,pi);if(!p)throw std::runtime_error("Parameter selection missing");auto r=records(*p);if(ci>=r.size())throw std::runtime_error("Curve selection out of range");Bytes b(4);put32(b,0,static_cast<std::uint32_t>(r[ci].bytes.size()));b.insert(b.end(),r[ci].bytes.begin(),r[ci].bytes.end());return list("PRMC",{leaf("prcc",b)}).encode();}
bool paste_param_curve(Chunk& t,size_t oi,size_t pi,const Bytes& bytes,std::int32_t at,size_t* result){auto clipboard=Chunk::parse_list(bytes);if(clipboard.type!="PRMC")throw std::runtime_error("Expected Parameter Control clipboard");auto incoming=records(clipboard);if(incoming.size()!=1)throw std::runtime_error("Expected one parameter curve");auto v=incoming.front();const auto end=static_cast<std::int64_t>(at)+v.value.end-v.value.start;if(end>INT32_MAX||end<INT32_MIN)return false;v.value.start=at;v.value.end=static_cast<std::int32_t>(end);v.selected=true;(void)param_control_objects(t);auto next=t;auto p=parameter(next,oi,pi);if(!p)return false;auto r=records(*p);r.push_back(std::move(v));size_t picked=0;write_records(*p,std::move(r),&picked);if(!publish(t,std::move(next)))return false;if(result)*result=picked;return true;}
}
