#include "runtime_settings_editor.h"
#include <stdexcept>
namespace producer::app {namespace {
enum:UINT {Project=10,Component,Name,ProjectSet,ComponentSet,NameSet,SaveDefault,Status,DocumentFolder,DocumentFolderSet,DocumentFolderReset};
struct Session{Framework& host;RuntimeDocumentKind kind;size_t index;};
HWND control(HWND w,const wchar_t* cls,const wchar_t* text,DWORD style,int x,int y,int width,int height,UINT id=0){const auto c=CreateWindowW(cls,text,WS_CHILD|WS_VISIBLE|style,x,y,width,height,w,reinterpret_cast<HMENU>(static_cast<UINT_PTR>(id)),nullptr,nullptr);if(!c)throw std::runtime_error("Runtime settings control creation failed");SendMessageW(c,WM_SETFONT,reinterpret_cast<WPARAM>(GetStockObject(DEFAULT_GUI_FONT)),TRUE);return c;}
std::wstring value(HWND w,UINT id){const auto c=GetDlgItem(w,id);const auto n=GetWindowTextLengthW(c);std::wstring text(n+1,L'\0');GetWindowTextW(c,text.data(),n+1);text.resize(n);return text;}
void refresh(HWND w,Session& s){SetWindowTextW(GetDlgItem(w,Project),s.host.runtime_project_folder().c_str());SetWindowTextW(GetDlgItem(w,Component),s.host.runtime_component_folder(s.kind).c_str());SetWindowTextW(GetDlgItem(w,DocumentFolder),s.host.runtime_file_folder(s.kind,s.index).c_str());SetWindowTextW(GetDlgItem(w,Name),s.host.runtime_filename(s.kind,s.index).c_str());SetWindowTextW(GetDlgItem(w,Status),L"Document folder overrides the component default. Use Component Default removes this document override. Relative folders use the Project directory. Save Project to retain these settings. Create output folders before saving.");}
LRESULT CALLBACK proc(HWND w,UINT msg,WPARAM wp,LPARAM lp){auto s=reinterpret_cast<Session*>(GetWindowLongPtrW(w,GWLP_USERDATA));try{
 if(msg==WM_CREATE){s=static_cast<Session*>(reinterpret_cast<CREATESTRUCTW*>(lp)->lpCreateParams);SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(s));control(w,L"STATIC",L"Project default folder",0,16,16,420,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,16,42,460,26,Project);control(w,L"BUTTON",L"Set Project Folder",WS_TABSTOP,490,42,190,28,ProjectSet);control(w,L"STATIC",L"Component default folder",0,16,88,420,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,16,114,460,26,Component);control(w,L"BUTTON",L"Set Component Folder",WS_TABSTOP,490,114,190,28,ComponentSet);control(w,L"STATIC",L"This document's runtime folder",0,16,160,420,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,16,186,460,26,DocumentFolder);control(w,L"BUTTON",L"Set Document Folder",WS_TABSTOP,490,186,190,28,DocumentFolderSet);control(w,L"BUTTON",L"Use Component Default",WS_TABSTOP,16,222,280,28,DocumentFolderReset);control(w,L"STATIC",L"This document's runtime name",0,16,264,420,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,16,290,460,26,Name);control(w,L"BUTTON",L"Set Name",WS_TABSTOP,490,290,190,28,NameSet);control(w,L"BUTTON",L"Save Runtime to Default",WS_TABSTOP,16,338,280,30,SaveDefault);control(w,L"STATIC",L"",0,16,386,660,92,Status);refresh(w,*s);return 0;}
 if(msg==WM_COMMAND&&s&&HIWORD(wp)==BN_CLICKED){const auto id=LOWORD(wp);switch(id){case ProjectSet:if(!s->host.set_runtime_project_folder(value(w,Project))&&s->host.runtime_project_folder()!=value(w,Project))throw std::runtime_error("Invalid Project folder");break;case ComponentSet:if(!s->host.set_runtime_component_folder(s->kind,value(w,Component))&&s->host.runtime_component_folder(s->kind)!=value(w,Component))throw std::runtime_error("Invalid component folder");break;case DocumentFolderSet:if(!s->host.set_runtime_file_folder(s->kind,s->index,value(w,DocumentFolder))&&s->host.runtime_file_folder(s->kind,s->index)!=value(w,DocumentFolder))throw std::runtime_error("Invalid document folder");break;case DocumentFolderReset:s->host.set_runtime_file_folder(s->kind,s->index,L"");break;case NameSet:if(!s->host.set_runtime_filename(s->kind,s->index,value(w,Name))&&s->host.runtime_filename(s->kind,s->index)!=value(w,Name))throw std::runtime_error("Invalid runtime name or extension");break;case SaveDefault:s->host.save_runtime_default(s->kind,s->index);break;default:return 0;}refresh(w,*s);return 0;}
 if(msg==WM_CLOSE){DestroyWindow(w);return 0;}
 }catch(const std::exception& e){const std::string text=e.what();MessageBoxW(w,std::wstring(text.begin(),text.end()).c_str(),L"Runtime Settings",MB_OK|MB_ICONERROR);if(msg==WM_CREATE)return -1;}return DefWindowProcW(w,msg,wp,lp);}
}
void show_runtime_settings(HWND parent,Framework& host,RuntimeDocumentKind kind,size_t index){const auto instance=GetModuleHandleW(nullptr);static bool registered=false;if(!registered){WNDCLASSW c{};c.hInstance=instance;c.lpfnWndProc=proc;c.hCursor=LoadCursorW(nullptr,IDC_ARROW);c.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);c.lpszClassName=L"SourceProducerRuntimeSettings";if(!RegisterClassW(&c))throw std::runtime_error("Runtime settings window registration failed");registered=true;}Session session{host,kind,index};const auto w=CreateWindowExW(WS_EX_APPWINDOW,L"SourceProducerRuntimeSettings",L"Runtime Settings",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,720,530,nullptr,nullptr,instance,&session);if(!w)throw std::runtime_error("Runtime settings window creation failed");const bool enabled=IsWindowEnabled(parent)!=FALSE;EnableWindow(parent,FALSE);ShowWindow(w,SW_SHOW);UpdateWindow(w);MSG msg{};BOOL result=1;while(IsWindow(w)&&(result=GetMessageW(&msg,nullptr,0,0))>0)if(!IsDialogMessageW(w,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}if(IsWindow(w))DestroyWindow(w);EnableWindow(parent,enabled);SetActiveWindow(parent);if(result==0)PostQuitMessage(static_cast<int>(msg.wParam));if(result<0)throw std::runtime_error("Runtime settings message loop failed");}
}
