#include "script_editor.h"
#include <commdlg.h>
#include <filesystem>
#include <stdexcept>
#include <sstream>
#include <limits>
namespace producer::app {namespace {
enum:UINT{Documents=10,New,Open,Save,Undo,Redo,Name,Language,LoadAll,DownloadAll,Properties,Source,ApplySource,Status,ContainerObjects,Alias,Keep,NoLoads,ApplyContainer,ContainerDetail,InitScript,Routine,CallRoutine,Variable,Number,SetNumber,GetNumber,RuntimeStatus,AvailableSegments,AddReference,RemoveObject};
struct Session{Framework& host;Conductor& conductor;size_t selected=0;size_t objectSelected=0;Bytes executed;size_t executedIndex=0;std::vector<size_t> available;};
void control(HWND w,const wchar_t* cls,const wchar_t* txt,DWORD flags,int x,int y,int width,int height,UINT id=0){CreateWindowW(cls,txt,WS_CHILD|WS_VISIBLE|flags,x,y,width,height,w,reinterpret_cast<HMENU>(static_cast<UINT_PTR>(id)),GetModuleHandleW(nullptr),nullptr);}
std::wstring text(HWND w,UINT id){auto c=GetDlgItem(w,id);std::wstring v(GetWindowTextLengthW(c)+1,0);GetWindowTextW(c,v.data(),static_cast<int>(v.size()));v.pop_back();return v;}
std::wstring file(HWND w,bool save){wchar_t path[32768]{};OPENFILENAMEW f{};f.lStructSize=sizeof(f);f.hwndOwner=w;f.lpstrFile=path;f.nMaxFile=32768;f.lpstrFilter=L"Producer Script\0*.spp;*.spt\0";f.lpstrDefExt=L"spp";f.Flags=OFN_EXPLORER|OFN_PATHMUSTEXIST|OFN_NOCHANGEDIR|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);return(save?GetSaveFileNameW(&f):GetOpenFileNameW(&f))?path:L"";}
void show_result(HWND w,const ScriptResult& r){std::wostringstream out;if(r.passed())out<<L"Script operation succeeded.";else out<<L"Script error 0x"<<std::hex<<static_cast<unsigned long>(r.result)<<std::dec<<L"; line "<<r.error.line<<L", character "<<r.error.character<<L": "<<r.error.description;SetWindowTextW(GetDlgItem(w,RuntimeStatus),out.str().c_str());}
void refresh(HWND w,Session& s){
    SendDlgItemMessageW(w,Documents,CB_RESETCONTENT,0,0);for(const auto& e:s.host.scripts()){auto label=(e.document->name().empty()?(e.path.empty()?L"Untitled Script":std::filesystem::path(e.path).filename().wstring()):e.document->name())+(e.document->dirty()?L" *":L"");SendDlgItemMessageW(w,Documents,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(label.c_str()));}
    const bool present=!s.host.scripts().empty();for(auto id:{Save,Undo,Redo,Name,Language,LoadAll,DownloadAll,Properties,Source,ApplySource,ContainerObjects,Alias,Keep,NoLoads,ApplyContainer,InitScript,AvailableSegments,AddReference,RemoveObject})EnableWindow(GetDlgItem(w,id),present);
    const bool runnable=present&&s.executedIndex==s.selected&&s.executed==s.host.script_document(s.selected<s.host.scripts().size()?s.selected:0).save_bytes();for(auto id:{Routine,CallRoutine,Variable,Number,SetNumber,GetNumber})EnableWindow(GetDlgItem(w,id),runnable);if(!runnable)SetWindowTextW(GetDlgItem(w,RuntimeStatus),L"Initialize Script to run the applied source snapshot. Source edits require initialization again.");
    if(!present){SetWindowTextW(GetDlgItem(w,Status),L"Create or open a Script.");return;}if(s.selected>=s.host.scripts().size())s.selected=s.host.scripts().size()-1;SendDlgItemMessageW(w,Documents,CB_SETCURSEL,s.selected,0);const auto& d=s.host.script_document(s.selected);
    SetWindowTextW(GetDlgItem(w,Name),d.name().c_str());SetWindowTextW(GetDlgItem(w,Language),d.language().c_str());SendDlgItemMessageW(w,LoadAll,BM_SETCHECK,(d.flags()&1)?BST_CHECKED:BST_UNCHECKED,0);SendDlgItemMessageW(w,DownloadAll,BM_SETCHECK,(d.flags()&2)?BST_CHECKED:BST_UNCHECKED,0);auto source=d.source();SetWindowTextW(GetDlgItem(w,Source),source?source->c_str():L"");EnableWindow(GetDlgItem(w,Source),source.has_value());EnableWindow(GetDlgItem(w,ApplySource),source.has_value());SetWindowTextW(GetDlgItem(w,Status),source?(d.dirty()?L"Modified. Save Script, then Save Project.":L"Saved."):L"External source reference retained. Source file editing is pending.");
    auto graph=d.container();auto objects=graph.objects();
    s.available.clear();SendDlgItemMessageW(w,AvailableSegments,CB_RESETCONTENT,0,0);for(size_t i=0;i<s.host.documents().size();++i){const auto& entry=s.host.documents()[i];if(entry.path.empty())continue;const auto filename=std::filesystem::path(entry.path).filename().wstring();bool used=false;for(const auto& item:objects)if(auto f=item.payload.find("file"))if(CompareStringOrdinal(filename.c_str(),-1,decode_utf16(f->data).c_str(),-1,TRUE)==CSTR_EQUAL)used=true;if(used)continue;s.available.push_back(i);SendDlgItemMessageW(w,AvailableSegments,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(filename.c_str()));}SendDlgItemMessageW(w,AvailableSegments,CB_SETCURSEL,0,0);EnableWindow(GetDlgItem(w,AddReference),!s.available.empty());EnableWindow(GetDlgItem(w,RemoveObject),!objects.empty());SendDlgItemMessageW(w,ContainerObjects,CB_RESETCONTENT,0,0);for(size_t i=0;i<objects.size();++i){const auto label=std::to_wstring(i+1)+L": "+objects[i].alias.value_or(L"(no alias)");SendDlgItemMessageW(w,ContainerObjects,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(label.c_str()));}SendDlgItemMessageW(w,NoLoads,BM_SETCHECK,(graph.flags()&2)?BST_CHECKED:BST_UNCHECKED,0);for(auto id:{ContainerObjects,Alias,Keep})EnableWindow(GetDlgItem(w,id),!objects.empty());if(objects.empty()){SetWindowTextW(GetDlgItem(w,Alias),L"");SetWindowTextW(GetDlgItem(w,ContainerDetail),L"Empty Container. Add a saved Project Segment reference.");}else{if(s.objectSelected>=objects.size())s.objectSelected=0;SendDlgItemMessageW(w,ContainerObjects,CB_SETCURSEL,s.objectSelected,0);const auto& item=objects[s.objectSelected];SetWindowTextW(GetDlgItem(w,Alias),item.alias.value_or(L"").c_str());SendDlgItemMessageW(w,Keep,BM_SETCHECK,(item.flags&1)?BST_CHECKED:BST_UNCHECKED,0);std::wstring detail=item.reference?L"Reference":L"Embedded";if(auto f=item.payload.find("file"))detail+=L": "+decode_utf16(f->data);detail+=L". Initialize Script to resolve objects.";SetWindowTextW(GetDlgItem(w,ContainerDetail),detail.c_str());}
}
LRESULT CALLBACK proc(HWND w,UINT msg,WPARAM wp,LPARAM lp){auto s=reinterpret_cast<Session*>(GetWindowLongPtrW(w,GWLP_USERDATA));try{
    if(msg==WM_CREATE){s=static_cast<Session*>(reinterpret_cast<CREATESTRUCTW*>(lp)->lpCreateParams);SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(s));control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,16,12,720,180,Documents);control(w,L"BUTTON",L"New",WS_TABSTOP,16,50,110,28,New);control(w,L"BUTTON",L"Open...",WS_TABSTOP,136,50,110,28,Open);control(w,L"BUTTON",L"Save As...",WS_TABSTOP,256,50,110,28,Save);control(w,L"BUTTON",L"Undo",WS_TABSTOP,376,50,110,28,Undo);control(w,L"BUTTON",L"Redo",WS_TABSTOP,496,50,110,28,Redo);
        control(w,L"STATIC",L"Name",0,16,90,100,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,120,90,600,25,Name);control(w,L"STATIC",L"Language",0,16,124,100,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,120,124,260,25,Language);control(w,L"BUTTON",L"Load all content",BS_AUTOCHECKBOX|WS_TABSTOP,16,160,190,25,LoadAll);control(w,L"BUTTON",L"Download all segments",BS_AUTOCHECKBOX|WS_TABSTOP,220,160,250,25,DownloadAll);control(w,L"BUTTON",L"Apply Properties",WS_TABSTOP,500,158,220,28,Properties);
        control(w,L"STATIC",L"Source",0,16,198,100,22);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP|WS_VSCROLL|WS_HSCROLL|ES_MULTILINE|ES_AUTOVSCROLL|ES_AUTOHSCROLL|ES_WANTRETURN,16,224,704,230,Source);SendDlgItemMessageW(w,Source,EM_SETLIMITTEXT,1048576,0);control(w,L"BUTTON",L"Apply Source",WS_TABSTOP,16,466,180,28,ApplySource);control(w,L"STATIC",L"",0,16,506,704,22,Status);control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,16,532,360,180,AvailableSegments);control(w,L"BUTTON",L"Add reference",WS_TABSTOP,386,530,150,28,AddReference);control(w,L"BUTTON",L"Remove object",WS_TABSTOP,546,530,174,28,RemoveObject);control(w,L"STATIC",L"Container object",0,16,566,130,24);control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,150,566,570,200,ContainerObjects);control(w,L"STATIC",L"Alias",0,16,606,100,24);control(w,L"EDIT",L"",WS_BORDER|WS_TABSTOP,120,606,600,25,Alias);control(w,L"BUTTON",L"Keep cached",BS_AUTOCHECKBOX|WS_TABSTOP,16,646,180,25,Keep);control(w,L"BUTTON",L"Do not preload objects",BS_AUTOCHECKBOX|WS_TABSTOP,220,646,250,25,NoLoads);control(w,L"BUTTON",L"Apply Container",WS_TABSTOP,500,644,220,28,ApplyContainer);control(w,L"STATIC",L"",0,16,690,704,55,ContainerDetail);control(w,L"BUTTON",L"Initialize Script",WS_TABSTOP,16,755,180,28,InitScript);control(w,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_TABSTOP,210,755,280,150,Routine);control(w,L"BUTTON",L"Call Routine",WS_TABSTOP,510,755,210,28,CallRoutine);control(w,L"EDIT",L"Score",WS_BORDER|WS_TABSTOP,16,795,240,26,Variable);control(w,L"EDIT",L"0",WS_BORDER|WS_TABSTOP,270,795,160,26,Number);control(w,L"BUTTON",L"Set Number",WS_TABSTOP,440,795,135,28,SetNumber);control(w,L"BUTTON",L"Get Number",WS_TABSTOP,585,795,135,28,GetNumber);control(w,L"EDIT",L"",WS_BORDER|ES_MULTILINE|ES_READONLY,16,837,704,55,RuntimeStatus);refresh(w,*s);return 0;}
    if(msg==WM_COMMAND&&s){const auto id=LOWORD(wp);if(id==Documents&&HIWORD(wp)==CBN_SELCHANGE){s->selected=static_cast<size_t>(SendDlgItemMessageW(w,Documents,CB_GETCURSEL,0,0));refresh(w,*s);return 0;}if(id==ContainerObjects&&HIWORD(wp)==CBN_SELCHANGE){s->objectSelected=static_cast<size_t>(SendDlgItemMessageW(w,ContainerObjects,CB_GETCURSEL,0,0));refresh(w,*s);return 0;}if(HIWORD(wp)!=BN_CLICKED)return 0;
        if(id==InitScript){const auto bytes=s->host.script_document(s->selected).save_bytes();const auto& entry=s->host.scripts().at(s->selected);const auto dir=entry.path.empty()?L"":std::filesystem::path(entry.path).parent_path().wstring();const auto r=s->conductor.load_script(bytes,dir,w);show_result(w,r);if(!r.passed())return 0;s->executed=bytes;s->executedIndex=s->selected;refresh(w,*s);SendDlgItemMessageW(w,Routine,CB_RESETCONTENT,0,0);for(const auto& name:s->conductor.script_session().routines())SendDlgItemMessageW(w,Routine,CB_ADDSTRING,0,reinterpret_cast<LPARAM>(name.c_str()));SendDlgItemMessageW(w,Routine,CB_SETCURSEL,0,0);show_result(w,r);return 0;}
        if(id==CallRoutine||id==SetNumber||id==GetNumber){if(s->executedIndex!=s->selected||s->executed!=s->host.script_document(s->selected).save_bytes())throw std::runtime_error("Script source changed; initialize again");auto& runtime=s->conductor.script_session();if(id==CallRoutine)show_result(w,runtime.call(text(w,Routine)));else if(id==GetNumber){LONG n=0;const auto r=runtime.get_number(text(w,Variable),n);if(r.passed())SetWindowTextW(GetDlgItem(w,Number),std::to_wstring(n).c_str());show_result(w,r);}else{const auto value=text(w,Number);size_t used=0;const auto n=std::stoll(value,&used);if(used!=value.size()||n<std::numeric_limits<LONG>::min()||n>std::numeric_limits<LONG>::max())throw std::runtime_error("Script number must be a signed 32-bit integer");show_result(w,runtime.set_number(text(w,Variable),static_cast<LONG>(n)));}return 0;}
        if(id==AddReference){const auto selected=SendDlgItemMessageW(w,AvailableSegments,CB_GETCURSEL,0,0);if(selected==CB_ERR)return 0;const auto segment=s->available.at(static_cast<size_t>(selected));const auto alias=std::filesystem::path(s->host.documents()[segment].path).stem().wstring();if(!s->host.add_script_segment_reference(s->selected,segment,alias))throw std::runtime_error("Reference requires saved .spp and .sgp in the same directory, saved native Project metadata, and a unique object and alias");s->objectSelected=s->host.script_document(s->selected).container().objects().size()-1;refresh(w,*s);return 0;}
        if(id==RemoveObject){if(!s->host.script_document(s->selected).remove_contained_object(s->objectSelected))throw std::runtime_error("Container object removal rejected");refresh(w,*s);return 0;}
        if(id==New)s->selected=s->host.new_script();else if(id==Open){auto p=file(w,false);if(p.empty())return 0;s->selected=s->host.open_script(p);}else if(id==Save){auto p=file(w,true);if(p.empty())return 0;s->host.save_script(s->selected,p);}else if(id==Undo)s->host.script_document(s->selected).undo();else if(id==Redo)s->host.script_document(s->selected).redo();else if(id==Properties){auto& d=s->host.script_document(s->selected);auto name=text(w,Name),lang=text(w,Language);const bool load=SendDlgItemMessageW(w,LoadAll,BM_GETCHECK,0,0)==BST_CHECKED,download=SendDlgItemMessageW(w,DownloadAll,BM_GETCHECK,0,0)==BST_CHECKED;if((name!=d.name()||lang!=d.language()||load!=bool(d.flags()&1)||download!=bool(d.flags()&2))&&!d.set_properties(name,lang,load,download))throw std::runtime_error("Script properties rejected");}else if(id==ApplySource){auto& d=s->host.script_document(s->selected);auto source=text(w,Source);if(d.source()!=std::optional<std::wstring>(source)&&!d.set_source(source))throw std::runtime_error("Script source rejected");}else if(id==ApplyContainer){auto& d=s->host.script_document(s->selected);const bool noLoads=SendDlgItemMessageW(w,NoLoads,BM_GETCHECK,0,0)==BST_CHECKED;auto objects=d.container().objects();if(!objects.empty()){const auto alias=text(w,Alias);const bool keep=SendDlgItemMessageW(w,Keep,BM_GETCHECK,0,0)==BST_CHECKED;if((alias!=objects[s->objectSelected].alias.value_or(L"")||keep!=bool(objects[s->objectSelected].flags&1))&&!d.set_contained_properties(s->objectSelected,alias,keep))throw std::runtime_error("Container properties rejected");}d.set_container_no_loads(noLoads);}else return 0;refresh(w,*s);return 0;}
    if(msg==WM_CLOSE){DestroyWindow(w);return 0;}
}catch(const std::exception& e){MessageBoxA(w,e.what(),"Script operation failed",MB_OK|MB_ICONERROR);return 0;}return DefWindowProcW(w,msg,wp,lp);}
}
void show_script_documents(HWND parent,Framework& host,Conductor& conductor,size_t initialIndex){const auto instance=GetModuleHandleW(nullptr);static bool registered=false;if(!registered){WNDCLASSW c{};c.hInstance=instance;c.lpfnWndProc=proc;c.hCursor=LoadCursorW(nullptr,IDC_ARROW);c.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);c.lpszClassName=L"SourceProducerScriptDocuments";if(!RegisterClassW(&c))throw std::runtime_error("Script class registration failed");registered=true;}Session s{host,conductor};s.selected=initialIndex;const auto w=CreateWindowExW(WS_EX_APPWINDOW,L"SourceProducerScriptDocuments",L"Script Documents",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,780,930,nullptr,nullptr,instance,&s);if(!w)throw std::runtime_error("Script window creation failed");const bool enabled=IsWindowEnabled(parent)!=FALSE;EnableWindow(parent,FALSE);ShowWindow(w,SW_SHOW);MSG msg{};BOOL result=1;while(IsWindow(w)&&(result=GetMessageW(&msg,nullptr,0,0))>0)if(!IsDialogMessageW(w,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}if(IsWindow(w))DestroyWindow(w);EnableWindow(parent,enabled);SetActiveWindow(parent);if(!result)PostQuitMessage(static_cast<int>(msg.wParam));if(result<0)throw std::runtime_error("Script message loop failed");}
}
