void chord_composition_tests(const std::filesystem::path& dir,bool runtimeProof){
    SegmentDocument doc;doc.select_track_group(0x80000000);auto cord=*chord_track().find("LIST","cord");ChordEvent c;c.name=L"Generated";c.subchords[0].chordRoot=7;require(set_chord_event(cord,c),"Composition model generated payload fixture");
    const auto empty=doc.save_bytes();require(doc.replace_composed_chords(cord)&&doc.chords().size()==1&&doc.chords()[0].subchords[0].chordRoot==7,"Composition adds selected high-bit group Chord track");const auto generated=doc.save_bytes();require(doc.undo()&&doc.save_bytes()==empty&&doc.redo()&&doc.save_bytes()==generated,"Composed payload is one whole-byte undo redo");require(!doc.replace_composed_chords(cord)&&doc.save_bytes()==generated,"Identical composition does not add history");
    require(read_composed_chords(cord.encode()).encode()==cord.encode(),"Public track LIST persistence decoded without changing bytes");auto wrapper=chord_track();*wrapper.find("LIST","cord")=cord;require(read_composed_chords(wrapper.encode()).encode()==cord.encode(),"Wrapped native Chord persistence decoded independently");auto trailing=cord.encode();trailing.push_back(0);rejected([&]{read_composed_chords(trailing);},"Composed persistence trailing bytes rejected");wrapper.children.push_back(cord);rejected([&]{read_composed_chords(wrapper.encode());},"Ambiguous wrapped Chord payload rejected");
    auto bad=cord;bad.find("crdb")->data.pop_back();rejected([&]{doc.replace_composed_chords(bad);},"Truncated generated Chord rejected");bad=cord;put32(bad.find("crdb")->data,36,static_cast<std::uint32_t>(doc.length()));rejected([&]{doc.replace_composed_chords(bad);},"Out of range generated Chord rejected");require(doc.save_bytes()==generated&&doc.undo()&&doc.save_bytes()==empty&&doc.redo()&&doc.save_bytes()==generated,"Composition refusal retains bytes and history");
    auto opaque=Chunk::parse(generated);auto tracks=opaque.find("LIST","trkl");auto t=tracks->children.back().find("LIST","cord");Chunk unknown;unknown.id="zzzz";unknown.data={1,2,3};t->children.push_back(unknown);t->find("crdh")->data.push_back(0x77);tracks->children.back().find("trkh")->data.push_back(0x99);doc.load(opaque.encode());doc.select_track_group(0x80000000);const auto imported=doc.save_bytes();c.subchords[0].chordRoot=5;require(set_chord_event(cord,c)&&doc.replace_composed_chords(cord),"Compose replaces existing imported payload");const auto retained=Chunk::parse(doc.save_bytes());auto track=retained.find("LIST","trkl")->children.back();require(track.find("trkh")->data.back()==0x99&&track.find("LIST","cord")->find("zzzz")->data==Bytes({1,2,3})&&track.find("LIST","cord")->find("crdh")->data.back()==0x77,"Composition retains track and Chord metadata extensions");require(doc.undo()&&doc.save_bytes()==imported,"Imported composition undo retains all opaque bytes");
    doc.select_track_group(1);require(doc.chords().empty(),"Composition never replaces another group Chord track");
    rejected([&]{compose_chord_track(doc.save_bytes(),0,{},{});},"Zero composition group rejected before COM");rejected([&]{compose_chord_track(doc.save_bytes(),1,{}, {},4);},"Unsupported activity rejected before COM");rejected([&]{compose_chord_track(doc.save_bytes(),1,{},{});},"Missing harmonic references rejected before COM");require(doc.save_bytes()==imported,"Missing composition prerequisites do not mutate source");
    if(!runtimeProof)return;
    Framework host;const auto si=host.new_segment(),sti=host.new_style(),mi=host.new_chordmap();const auto& style=host.style_document(sti);require(host.new_style_pattern(sti,L"Pulse",0)&&host.add_style_band_gm_instrument(sti,{},0,0,64,100),"Owned normal Style with GM Band");require(host.insert_style_part_note(sti,0,0,{0,384,0,UINT32_MAX,60,100}),"Owned fixed MIDI Style note; harmonic effect separate");
    auto& map=host.chordmap_document(mi);std::uint16_t a=0,b=0;require(map.insert_palette_node(12,&a)&&map.insert_palette_node(19,&b)&&map.insert_connection(a,{0,50,4,4,a})&&map.insert_connection(a,{0,50,4,4,b})&&map.insert_connection(b,{0,50,4,4,b})&&map.insert_connection(b,{0,50,4,4,a})&&map.insert_signpost(a,0x100)&&map.insert_signpost(b,0x200),"Owned source ChordMap two-node four-layer connected SignPosts");
    auto& segment=host.document(si);require(segment.set_signpost({0,0x100,0})&&segment.set_signpost({12288,0x200,4})&&segment.set_signpost({24576,0x100,8}),"Segment template SignPost progression");const auto out=dir/L"composition-fixture";std::filesystem::create_directories(out);host.save_segment(si,(out/L"Seed.sgp").wstring());host.save_style(sti,(out/L"Pulse.stp").wstring());host.save_chordmap(mi,(out/L"Map.cdp").wstring());require(host.assign_style_reference(si,sti,0)&&host.assign_chordmap_reference(si,mi,0),"Template owned unsaved Style and ChordMap references");
    const auto before=segment.save_bytes(),styleBefore=style.save_bytes(),mapBefore=map.save_bytes();write_file_atomic((out/L"Before.sgp").wstring(),before);
    require(host.compose_chords(si)&&!segment.chords().empty(),"OS Composer creates actual Chord Track from owned template");const auto after=segment.save_bytes();require(style.save_bytes()==styleBefore&&map.save_bytes()==mapBefore,"Composer leaves owned Style and ChordMap untouched");require(segment.undo()&&segment.save_bytes()==before&&segment.redo()&&segment.save_bytes()==after,"OS composition whole-document one undo redo");write_file_atomic((out/L"After.sgp").wstring(),after);SegmentDocument restored;restored.load(read_file((out/L"After.sgp").wstring()));require(restored.chords().size()==segment.chords().size()&&restored.save_bytes()==after,"Composed native Segment restores exact generated payload");
    const auto chords=segment.chords();require(chords.front().time==0&&chords.front().subchords[0].chordRoot%12==0,"First SignPost generated tonic chord");const auto second=std::find_if(chords.begin(),chords.end(),[](const ChordEvent& e){return e.time==12288;});require(second!=chords.end()&&second->subchords[0].chordRoot%12==7,"Second SignPost generated dominant chord at requested measure");
}
