// Included after the core test helpers, so these use the same check oracle.
void chord_track_tests(const std::filesystem::path& dir){
    SegmentDocument doc;ChordEvent c;c.name=L"CM7";c.time=800;
    require(doc.set_chord(c)&&doc.chords().size()==1&&doc.chords()[0].time==768&&doc.chords()[0].beat==1,"Chord owned insert snaps to Timeline beat");const auto inserted=doc.save_bytes();
    c.time=900;c.name=L"Dm";c.subchords[0].chordRoot=2;require(doc.set_chord(c)&&doc.chords().size()==1&&doc.chords()[0].name==L"Dm","Chord same beat replaces event");const auto replaced=doc.save_bytes();
    require(doc.undo()&&doc.save_bytes()==inserted&&doc.redo()&&doc.save_bytes()==replaced,"Chord replacement complete-byte Undo Redo");
    c.time=3072;c.name=L"G7";require(doc.set_chord(c)&&doc.chords()[1].measure==1,"Chord insert derives stored measure");const auto two=doc.save_bytes();
    auto moved=doc.chords()[1];moved.time=780;size_t index=999;require(doc.edit_chord(1,moved,0,&index)&&index==0&&doc.chords().size()==1&&doc.chords()[0].name==L"G7","Chord move replaces destination beat and reports sorted index");
    require(doc.undo()&&doc.save_bytes()==two,"Chord collision Undo restores both records");
    const auto rejected=[&](ChordEvent bad){const auto bytes=doc.save_bytes();const bool dirty=doc.dirty();auto expected=doc;size_t output=999;require(!doc.edit_chord(0,bad,0,&output)&&output==999&&doc.save_bytes()==bytes&&doc.dirty()==dirty,"Invalid Chord leaves bytes dirty and output index unchanged");require(doc.undo()==expected.undo()&&doc.save_bytes()==expected.save_bytes()&&doc.redo()==expected.redo()&&doc.save_bytes()==expected.save_bytes(),"Invalid Chord leaves Undo Redo intact");};
    auto bad=doc.chords()[0];bad.time=-1;rejected(bad);bad=doc.chords()[0];bad.time=doc.length();rejected(bad);bad=doc.chords()[0];bad.name=std::wstring(17,L'x');rejected(bad);bad=doc.chords()[0];bad.flags=2;rejected(bad);bad=doc.chords()[0];bad.subchords.clear();rejected(bad);bad=doc.chords()[0];bad.subchords[0].chordRoot=24;rejected(bad);bad=doc.chords()[0];bad.subchords[0].scalePattern=0x1000000;rejected(bad);
    const auto base=dir/L"chord-track";std::filesystem::create_directories(base);doc.save((base/L"authored.sgp").wstring());SegmentDocument reload;reload.load(read_file((base/L"authored.sgp").wstring()));require(reload.save_bytes()==two&&!reload.dirty()&&reload.chords().size()==2&&reload.chords()[0].subchords[0].chordRoot==2,"Chord save reload typed values and clean checkpoint");
    auto tree=Chunk::parse(two);auto track=tree.find("LIST","trkl")->children.back();auto cord=track.find("LIST","cord");auto body=cord->find("crdb");auto& b=body->data;b.insert(b.begin()+44,{0xde,0xad,0xbe,0xef});put32(b,0,44);b.insert(b.end(),{0x12,0x34,0x56,0x78});put32(b,52,24);b[74]=0xaa;b[75]=0xbb;Chunk unknown;unknown.id="keep";unknown.data={7};unknown.padding=0x9d;cord->children.insert(cord->children.begin()+1,unknown);cord->find("crdh")->data.push_back(0xee);
    auto e=chord_events(*cord)[0];e.name=L"Extended";require(change_chord_event(*cord,0,e),"Chord extended record edit");const auto edited=cord->find("crdb")->data;require(read32(edited,0)==44&&read32(edited,52)==24&&edited[44]==0xde&&edited[74]==0xaa&&edited[75]==0xbb&&edited[76]==0x12&&cord->find("keep")->encode()==unknown.encode()&&cord->find("crdh")->data.back()==0xee,"Chord edit retains struct extension reserved bytes unknown chunk and padding");
    const auto malformed=[&](Bytes bytes){auto broken=*cord;broken.find("crdb")->data=std::move(bytes);const auto before=broken.encode();bool refused=false;try{(void)set_chord_event(broken,e);}catch(const std::exception&){refused=true;}require(refused&&broken.encode()==before,"Malformed Chord refuses transactional mutation");};auto bytes=edited;put32(bytes,0,UINT32_MAX);malformed(bytes);bytes=edited;put32(bytes,48,UINT32_MAX);malformed(bytes);bytes=edited;put32(bytes,52,19);malformed(bytes);bytes=edited;bytes.pop_back();malformed(bytes);
    doc.select_track_group(2);require(doc.chords().empty(),"Chord group isolates existing track");c.time=0;c.name=L"Group2";require(doc.set_chord(c)&&doc.chords()[0].name==L"Group2","Chord new track owns selected group");doc.select_track_group(1);require(doc.chords().size()==2&&doc.save_bytes()!=two,"Chord group selection preserves other group bytes");require(doc.delete_chord(0)&&doc.chords().size()==1&&doc.undo()&&doc.chords().size()==2,"Chord delete and Undo");
    auto boundary=doc.chords()[0];boundary.name=std::wstring(16,L'x');boundary.subchords.resize(8);boundary.subchords.back().chordRoot=23;boundary.subchords.back().scaleRoot=23;require(doc.edit_chord(0,boundary)&&doc.chords()[0].name==boundary.name&&doc.chords()[0].subchords.size()==8,"Chord fixed WCHAR16 and SDK maximum eight subchords round trip");boundary.subchords.push_back(SubChord{});rejected(boundary);
    Framework host;const auto owned=host.open_segment((base/L"authored.sgp").wstring());require(host.document(owned).edit_chord(0,doc.chords()[0]),"Chord edit owned by Framework Segment");host.save_segment(owned,(base/L"project-song.sgp").wstring());host.save_project((base/L"chord-track.pro").wstring());Framework reopened;reopened.open_project((base/L"chord-track.pro").wstring());require(reopened.document(0).chords().size()==2&&reopened.document(0).chords()[0].subchords.size()==8&&reopened.document(0).save_bytes()==host.document(owned).save_bytes()&&Chunk::parse(read_file((base/L"chord-track.pro").wstring())).type=="JAZP","Chord native JAZP Project reload resolves saved owned Segment");
}
