#include "compat/playback_runtime.h"
void chordmap_reference_tests(const std::filesystem::path& dir,bool runtimeProof=false){
    if(runtimeProof){
        ChordMapDocument map;map.set_name(L"Owned map");map.set_scale(0xabcdef);SegmentDocument source=SegmentDocument::playback_test();ChordMapReference r;r.hasId=true;r.objectId=map.object_id();r.name=map.name();r.filename=L"Missing.cdp";require(source.set_chordmap_reference(r),"Runtime fixture authored without disk publication");
        const auto bytes=source.save_bytes();auto maps=resolve_chordmaps(source.chordmap_references(),dir.wstring(),{{L"",map.save_bytes()}});require(maps.size()==1&&maps[0].bytes==map.save_bytes(),"Unsaved owned GUID resolves despite absent filename");auto copy=prepare_chordmap_playback(bytes,maps);require(copy.maps[0].reference.filename.empty()&&chordmap_references(Chunk::parse(copy.segment))[0].filename.empty(),"Runtime snapshot disables missing-file fallback");
        Conductor conductor;conductor.play(bytes,dir.wstring(),nullptr,{}, {}, {}, {}, {},maps);require((conductor.segment_chordmap_scale(0)&0xffffff)==0xabcdef,"OS Segment reference binds edited owned ChordMap scale");require(conductor.segment_track_group(producer::runtime::chordMapTrackClass,1,0)==1,"OS ChordMap Track retains group");require(source.save_bytes()==bytes,"Runtime registration leaves source intact");conductor.stop();conductor.shutdown();return;
    }
    ChordMapDocument a,b;a.set_name(L"Map A");b.set_name(L"Map B");b.set_scale(0x123456);
    ChordMapReference ref;ref.hasId=true;ref.objectId=a.object_id();ref.name=a.name();
    SegmentDocument doc;const auto empty=doc.save_bytes();require(doc.set_chordmap_reference(ref)&&doc.chordmap_references().size()==1,"Single ChordMap reference authored");const auto first=doc.save_bytes();
    require(!doc.set_chordmap_reference(ref)&&doc.save_bytes()==first,"Noop ChordMap retains bytes");
    ref.objectId=b.object_id();ref.name=b.name();ref.time=768;require(doc.set_chordmap_reference(ref),"ChordMap reference replacement");
    const auto second=doc.save_bytes();require(doc.undo()&&doc.save_bytes()==first&&doc.redo()&&doc.save_bytes()==second,"ChordMap whole-byte Undo Redo");
    auto invalid=[&](ChordMapReference bad){auto expected=doc;const auto before=doc.save_bytes();const auto dirty=doc.dirty();require(!doc.set_chordmap_reference(bad)&&doc.save_bytes()==before&&doc.dirty()==dirty,"Invalid ChordMap edit retains document checkpoint");require(doc.undo()==expected.undo()&&doc.save_bytes()==expected.save_bytes()&&doc.redo()==expected.redo()&&doc.save_bytes()==expected.save_bytes(),"Invalid ChordMap edit retains history");};
    auto bad=ref;bad.time=-1;invalid(bad);bad=ref;bad.time=doc.length();invalid(bad);bad=ref;bad.hasId=false;bad.filename.clear();invalid(bad);bad=ref;bad.filename=std::wstring(260,L'x');invalid(bad);bad=ref;bad.name=std::wstring(L"x\0y",3);invalid(bad);
    require(doc.clear_chordmap_reference()&&doc.chordmap_references().empty()&&doc.undo()&&doc.save_bytes()==second&&doc.redo()&&doc.chordmap_references().empty(),"Clear reference preserves undo redo");
    doc.load(empty);doc.select_track_group(0x80000000);ref.time=0;require(doc.set_chordmap_reference(ref)&&doc.chordmap_references()[0].groups==0x80000000,"Highest group bit allowed");doc.select_track_group(1);require(doc.chordmap_references(0).empty()&&doc.set_chordmap_reference(ref),"Distinct group has own ChordMap track");require(doc.chordmap_references().size()==2,"Whole Segment retains both groups");
    auto track=chordmap_reference_track(1);ref.groups=1;require(set_chordmap_reference(track,ref),"Track factory uses frozen class and pftr");
    auto& event=track.find("LIST","pftr")->children[0];Chunk opaque;opaque.id="zzzz";opaque.data={1,2,3};event.children.push_back(opaque);auto desc=event.find("LIST","DMRF");desc->find("refh")->data.push_back(0x77);desc->children.push_back(opaque);
    ref.time=12;require(set_chordmap_reference(track,ref)&&track.find("LIST","pftr")->children[0].find("zzzz")->data==Bytes({1,2,3})&&track.find("LIST","pftr")->children[0].find("LIST","DMRF")->find("refh")->data.back()==0x77,"Reference edit retains unknown chunks and extended header");
    auto multiple=track;multiple.find("LIST","pftr")->children.push_back(multiple.find("LIST","pftr")->children[0]);const auto multi=multiple.encode();require(chordmap_track_references(multiple).size()==2,"Imported reference array retained");rejected([&]{set_chordmap_reference(multiple,ref);},"Single editor refuses imported array replacement");rejected([&]{clear_chordmap_reference(multiple);},"Single editor refuses imported array deletion");require(multiple.encode()==multi,"Imported multiple refusal preserves bytes");
    const auto corrupt=[&](const std::function<void(Chunk&)>& change){auto next=track;change(next);rejected([&]{chordmap_track_references(next);},"Malformed reference rejected");};
    corrupt([](Chunk& t){put32(t.find("trkh")->data,20,0);});corrupt([](Chunk& t){t.find("trkh")->data[0]=0;});corrupt([](Chunk& t){t.find("LIST","pftr")->children[0].find("stmp")->data.pop_back();});corrupt([](Chunk& t){put32(t.find("LIST","pftr")->children[0].find("stmp")->data,0,0x80000000);});corrupt([](Chunk& t){t.find("LIST","pftr")->children[0].find("LIST","DMRF")->find("guid")->data.pop_back();});corrupt([](Chunk& t){t.find("LIST","pftr")->children[0].find("LIST","DMRF")->find("refh")->data[0]=0;});
    const auto base=dir/L"chordmap-reference";std::filesystem::create_directories(base);Framework host;auto si=host.new_segment(),ai=host.new_chordmap(),bi=host.new_chordmap();host.document(si)=SegmentDocument::playback_test();host.chordmap_document(ai)=a;host.chordmap_document(bi)=b;
    host.save_segment(si,(base/L"Song.sgp").wstring());host.save_chordmap(ai,(base/L"A.cdp").wstring());host.save_chordmap(bi,(base/L"B.cdp").wstring());const auto savedB=read_file((base/L"B.cdp").wstring());
    require(host.assign_chordmap_reference(si,ai)&&host.document(si).chordmap_references()[0].filename==L"A.cdp","Framework assigns owned GUID and relative filename");require(host.assign_chordmap_reference(si,bi),"Framework replaces selection");require(host.chordmap_document(bi).set_scale(0xabcdef),"Unsaved ChordMap edit");auto maps=host.playback_chordmaps(si);require(maps.size()==1&&maps[0].bytes==host.chordmap_document(bi).save_bytes()&&maps[0].bytes!=savedB,"GUID resolves unsaved owned snapshot before disk");
    const auto source=host.document(si).save_bytes();auto snapshot=prepare_chordmap_playback(source,maps);auto refs=chordmap_references(Chunk::parse(snapshot.segment));require(refs.size()==1&&refs[0].hasId&&refs[0].filename.empty()&&host.document(si).save_bytes()==source,"Private runtime snapshot disables disk fallback without source mutation");
    rejected([&]{prepare_chordmap_playback(source,{});},"Unresolved reference refused");auto wrong=maps;wrong[0].reference.time++;rejected([&]{prepare_chordmap_playback(source,wrong);},"Wrong snapshot context refused");wrong=maps;wrong[0].bytes=a.save_bytes();rejected([&]{prepare_chordmap_playback(source,wrong);},"Wrong snapshot GUID refused");
    std::vector<ChordMapCatalogEntry> duplicate={{L"",b.save_bytes()},{L"",b.save_bytes()}};rejected([&]{resolve_chordmaps({maps[0].reference},base.wstring(),duplicate);},"Ambiguous owned GUID refused");
    auto fileRef=maps[0].reference;fileRef.hasId=false;fileRef.filename=L"../outside.cdp";rejected([&]{resolve_chordmaps({fileRef},base.wstring(),{});},"Directory escape refused");
    host.save_chordmap(bi,(base/L"B.cdp").wstring());host.save_segment(si,(base/L"Song.sgp").wstring());host.save_project((base/L"chordmap-reference.pro").wstring());Framework reload;reload.open_project((base/L"chordmap-reference.pro").wstring());require(reload.documents().size()==1&&reload.chordmaps().size()==2&&!reload.dirty()&&reload.playback_chordmaps(0)[0].bytes==maps[0].bytes,"Native Project restores typed reference and owned map");
    if(runtimeProof){Conductor conductor;conductor.play(source,base.wstring(),nullptr,{}, {}, {}, {}, {},maps);require((conductor.segment_chordmap_scale(0)&0xffffff)==0xabcdef,"OS Segment reference binds edited owned ChordMap scale");require(conductor.segment_track_group(producer::runtime::chordMapTrackClass,1,0)==1,"OS ChordMap Track retains group");require(host.document(si).save_bytes()==source,"Runtime registration leaves source intact");conductor.stop();conductor.shutdown();}
}
