void chordmap_document_tests(const std::filesystem::path& dir,const std::wstring& originals=L"",const std::wstring& emptyOriginal=L""){
    const auto base=dir/L"chordmap-document",source=base/L"Source";std::filesystem::create_directories(source);ComponentCatalog catalog;
    require(catalog.is_chordmap_path(L"MAP.CDP")&&catalog.is_chordmap_path(L"Map.cdm")&&!catalog.is_chordmap_path(L"Map.sgp"),"Chordmap factory extensions");auto factory=catalog.create_chordmap_document("DMPR");rejected([&]{catalog.create_chordmap_document("DMAP");},"Chordmap factory refuses other forms");
    ChordMapDocument doc;const auto initial=doc.save_bytes();require(Chunk::parse(initial).type=="DMPR"&&doc.name()==L"Chordmap"&&doc.nodes().empty()&&!doc.dirty(),"New owned DMPR header database and graph");
    auto emptyTree=Chunk::parse(initial);emptyTree.children.erase(std::remove_if(emptyTree.children.begin(),emptyTree.children.end(),[](const Chunk& c){return c.id=="LIST"&&c.type=="spsq";}),emptyTree.children.end());ChordMapDocument empty;empty.load(emptyTree.encode());const auto emptyBytes=empty.save_bytes();require(empty.signposts().empty()&&empty.save_bytes()==emptyTree.encode(),"Omitted empty Signpost list accepted without normalization");require(!empty.set_signpost_groups(0,1)&&!empty.delete_signpost(0)&&empty.save_bytes()==emptyBytes&&!empty.dirty(),"Missing Signpost edits preserve empty original bytes");std::uint16_t emptyNode=0;require(empty.insert_node(L"Empty",{},&emptyNode)&&empty.insert_signpost(emptyNode,1)&&empty.signposts().size()==1,"First Signpost creates optional container");require(empty.undo()&&empty.signposts().empty()&&empty.redo()&&empty.signposts().size()==1,"Optional Signpost creation full history");if(!emptyOriginal.empty()){const auto bytes=read_file(emptyOriginal);ChordMapDocument observed;observed.load(bytes);require(observed.save_bytes()==bytes&&observed.nodes().empty()&&observed.signposts().empty()&&!observed.name().empty(),"Original newly saved empty CDP typed lossless load");require(!observed.delete_signpost(0)&&observed.save_bytes()==bytes&&!observed.dirty(),"Original empty CDP invalid edit retains checkpoint");require(observed.set_name(L"Observed empty")&&observed.undo()&&observed.save_bytes()==bytes,"Original empty CDP name edit history");}
    std::uint16_t a=99,b=99;require(doc.insert_node(L"C",{},&a)&&a==1&&doc.insert_node(L"F",{},&b)&&b==2,"Chordmap inserts unique WORD node identities");
    const auto sharedTree=Chunk::parse(doc.save_bytes());const auto& sharedNodes=sharedTree.find("LIST","cmap")->children;
    require(sharedTree.find("chdt")->data.size()==Chunk::parse(initial).find("chdt")->data.size()+20&&sharedNodes[0].find("LIST","chrd")->find("sbcn")->data==sharedNodes[1].find("LIST","chrd")->find("sbcn")->data,"Identical authored Subchords share one database identity");
    ChordMapDocument reuse;std::uint16_t reuseNode=0;require(reuse.insert_node(L"Reuse",{},&reuseNode),"Subchord reuse fixture");const auto reuseIdentity=Chunk::parse(reuse.save_bytes()).find("LIST","cmap")->children[0].find("LIST","chrd")->find("sbcn")->data;auto replacement=reuse.nodes()[0].subchords[0];replacement.root=5;require(reuse.edit_subchord(reuseNode,0,replacement)&&reuse.edit_subchord(reuseNode,0,{}),"Subchord copy on write can return to existing definition");
    const auto reused=Chunk::parse(reuse.save_bytes());require(reused.find("chdt")->data.size()==Chunk::parse(initial).find("chdt")->data.size()+40&&reused.find("LIST","cmap")->children[0].find("LIST","chrd")->find("sbcn")->data==reuseIdentity,"Returning Subchord reuses original identity without another duplicate");
    auto connection=ChordMapConnection{};connection.destination=b;require(doc.insert_connection(a,connection)&&doc.insert_connection(b,{}),"Chordmap owned destination and terminal zero connections");
    require(doc.insert_signpost(a,0x101)&&doc.signposts()[0].groups==0x101&&doc.signposts()[0].subchords[0].chord==0x91,"Chordmap Signpost copies chord with multiple groups");
    auto sub=doc.nodes()[0].subchords[0];sub.chord=0x121;sub.root=5;sub.flags=0xabcd;const auto before=doc.save_bytes();require(doc.edit_subchord(a,0,sub)&&doc.nodes()[0].subchords[0].chord==0x121&&doc.signposts()[0].subchords[0].chord==0x91&&doc.nodes()[1].subchords[0].chord==0x91,"Subchord copy on write isolates Signpost and other nodes");
    const auto after=doc.save_bytes();require(doc.undo()&&doc.save_bytes()==before&&doc.redo()&&doc.save_bytes()==after,"Chordmap full byte Undo Redo");doc.save((source/L"Map.cdp").wstring());require(!doc.dirty(),"Chordmap save establishes checkpoint");
    require(doc.rename_node(a,L"C minor Ω")&&doc.set_name(L"和声 Ω")&&doc.set_scale(0xffab5),"Chordmap Unicode names and DWORD scale ownership");doc.save((source/L"Map.cdp").wstring());const auto clean=doc.save_bytes();const auto invariant=[&](const std::function<bool()>& f){const auto bytes=doc.save_bytes();const auto dirty=doc.dirty();require(!f()&&doc.save_bytes()==bytes&&doc.dirty()==dirty,"Invalid Chordmap edit retains bytes and dirty");};
    sub.root=24;invariant([&]{return doc.edit_subchord(a,0,sub);});sub.root=0;sub.chord=0x1000000;invariant([&]{return doc.insert_node(L"invalid",sub,&a);});require(a==1,"Invalid insertion retains output ID");
    invariant([&]{return doc.set_scale(0x1000000);});invariant([&]{return doc.set_name(L"");});invariant([&]{return doc.set_name(std::wstring(20,L'a'));});invariant([&]{return doc.rename_node(a,std::wstring(L"a\0b",3));});
    connection.destination=65535;invariant([&]{return doc.insert_connection(a,connection);});connection.destination=b;connection.weight=101;invariant([&]{return doc.set_connection(a,0,connection);});connection.weight=50;connection.minBeats=5;connection.maxBeats=4;invariant([&]{return doc.insert_connection(a,connection);});
    invariant([&]{return doc.set_signpost_groups(0,0);});invariant([&]{return doc.set_signpost_groups(0,0x8000);});invariant([&]{return doc.insert_signpost(65535,1);});invariant([&]{return doc.delete_connection(a,99);});
    require(doc.undo()&&doc.scale()==0xab5ab5&&doc.name()==L"和声 Ω"&&doc.redo()&&doc.save_bytes()==clean,"Invalid edits preserve previous history and checkpoint");
    auto broken=Chunk::parse(clean);broken.find("chdt")->data.pop_back();rejected([&]{doc.load(broken.encode());},"Truncated database load rejected");require(doc.save_bytes()==clean&&!doc.dirty(),"Malformed load leaves owned document intact");
    broken=Chunk::parse(clean);auto map=broken.find("LIST","cmap");map->children.push_back(map->children.front());rejected([&]{doc.load(broken.encode());},"Duplicate node identity load rejected");
    broken=Chunk::parse(clean);auto& badLinks=broken.find("LIST","cmap")->children.front().find("ncsq")->data;badLinks[12]=0xfe;badLinks[13]=0xff;rejected([&]{doc.load(broken.encode());},"Dangling loaded destination rejected");require(doc.save_bytes()==clean&&doc.undo()&&doc.redo()&&doc.save_bytes()==clean,"Failed graph load preserves history");
    // Extended records and shared database IDs are imported; editing one owner
    // retains extension bytes and every other reference rather than mutating a shared record.
    auto extended=Chunk::parse(clean);auto& db=extended.find("chdt")->data;Bytes exdb{24,0};for(size_t p=2;p<db.size();p+=20){exdb.insert(exdb.end(),db.begin()+p,db.begin()+p+20);exdb.insert(exdb.end(),{0x11,0x22,0x33,0x44});}db=exdb;
    auto& entries=extended.find("LIST","cmap")->children;auto& one=entries[0];auto& two=entries[1];two.find("LIST","chrd")->find("sbcn")->data=one.find("LIST","chrd")->find("sbcn")->data;auto& links=one.find("ncsq")->data;links[0]=16;links.insert(links.end(),{0x55,0x66,0x77,0x88});ChordMapDocument imported;imported.load(extended.encode());const auto peer=imported.nodes()[1].subchords[0].chord;sub=imported.nodes()[0].subchords[0];sub.chord=0x421;require(imported.edit_subchord(a,0,sub)&&imported.nodes()[1].subchords[0].chord==peer,"Imported shared database edit isolates peer");auto edited=Chunk::parse(imported.save_bytes());const auto& db2=edited.find("chdt")->data;require(Bytes(db2.end()-4,db2.end())==Bytes({0x11,0x22,0x33,0x44}),"Subchord extension preserved on copy on write");connection=imported.nodes()[0].connections[0];connection.weight=0;require(imported.set_connection(a,0,connection)&&imported.nodes()[0].connections[0].weight==0,"Connection zero weight accepted");edited=Chunk::parse(imported.save_bytes());const auto& link2=edited.find("LIST","cmap")->children[0].find("ncsq")->data;require(Bytes(link2.end()-4,link2.end())==Bytes({0x55,0x66,0x77,0x88}),"Connection extension retained by edit");
    require(doc.delete_node(b)&&doc.nodes().size()==1&&doc.nodes()[0].connections.empty()&&doc.signposts().size()==1,"Delete node removes incoming links retaining independent Signpost");require(doc.undo()&&doc.nodes().size()==2&&doc.redo()&&doc.nodes().size()==1,"Structural deletion full history");require(doc.set_signpost_groups(0,0x7f3f)&&doc.delete_signpost(0)&&doc.signposts().empty()&&doc.undo()&&doc.signposts().size()==1,"Signpost group delete history");
    Framework host;const auto owned=host.open_chordmap((source/L"Map.cdp").wstring());require(owned==host.open_chordmap((source/L"Map.cdp").wstring())&&host.chordmaps().size()==1,"Framework deduplicates owned Chordmap path");host.save_project((source/L"Source.pro").wstring());const auto project=read_file((source/L"Source.pro").wstring());auto native=Chunk::parse(project);const auto ref=native.find("LIST","file");require(native.type=="JAZP"&&ref&&decode_utf16(ref->find("LIST","UNFO")->find("rnam")->data)==L"Map.cdm"&&decode_utf16(ref->find("LIST","UNFO")->find("nnam")->data)==L"和声 Ω","Native Project owns Chordmap identity name runtime metadata");
    Framework reloaded;reloaded.open_project((source/L"Source.pro").wstring());require(reloaded.chordmaps().size()==1&&!reloaded.dirty()&&reloaded.chordmap_document(0).save_bytes()==clean,"Separate Framework native reload restores graph and checkpoint");reloaded.save_project((source/L"Source.pro").wstring());require(read_file((source/L"Source.pro").wstring())==project,"Unchanged native Chordmap Project resave exact");require(host.chordmap_document(owned).set_name(L"Revised Ω")&&host.dirty(),"Chordmap edit participates in Project dirty");rejected([&]{host.save_project((source/L"Source.pro").wstring());},"Project refuses unsaved Chordmap");host.save_chordmap(owned,(source/L"Map.cdp").wstring());host.save_project((source/L"Source.pro").wstring());native=Chunk::parse(read_file((source/L"Source.pro").wstring()));require(decode_utf16(native.find("LIST","file")->find("LIST","UNFO")->find("nnam")->data)==L"Revised Ω","Saved Chordmap refreshes native display metadata");
    const auto other=host.new_chordmap();rejected([&]{host.save_chordmap(other,(source/L"Map.cdp").wstring());},"Second Chordmap cannot overwrite another owner");host.save_chordmap(other,(source/L"Other.cdp").wstring());host.save_project((source/L"Source.pro").wstring());const auto copied=base/L"Copied";host.copy_project((copied/L"Copied.pro").wstring());std::filesystem::rename(source,base/L"SourceHeld");Framework copiedHost;copiedHost.open_project((copied/L"Copied.pro").wstring());require(copiedHost.chordmaps().size()==2&&copiedHost.chordmap_document(0).name()==L"Revised Ω"&&!copiedHost.dirty(),"Copied native Chordmap Project restores with source folder absent");
    if(!originals.empty()){size_t count=0;for(const auto& entry:std::filesystem::recursive_directory_iterator(originals)){if(!entry.is_regular_file()||!catalog.is_chordmap_path(entry.path().wstring()))continue;++count;const auto bytes=read_file(entry.path().wstring());ChordMapDocument original;original.load(bytes);require(original.save_bytes()==bytes&&!original.nodes().empty()&&!original.name().empty(),"Original DMPR lossless typed graph load");const auto first=original.nodes()[0];require(original.rename_node(first.id,L"Observed edit Ω"),"Imported Chordmap node owned name edit");const auto changed=original.save_bytes();require(original.undo()&&original.save_bytes()==bytes&&original.redo()&&original.save_bytes()==changed,"Imported graph name full history");const auto blocked=original.save_bytes();rejected([&]{original.insert_node(L"guard",{});},"Imported design layout insertion explicitly unsupported");require(original.save_bytes()==blocked,"Imported layout refusal preserves document");}require(count==27,"All 27 observed original Chordmaps exercised; static comparison only");}
}

