void chordmap_palette_tests(const std::filesystem::path& dir,const std::wstring& originalPath){
    ChordMapDocument doc,observed;observed.load(read_file(originalPath));const auto original=observed.save_bytes(),initial=doc.save_bytes();
    require(doc.palette().size()==24&&observed.palette().size()==24,"24 original and source fixed-root palette entries");
    for(size_t i=0;i<24;++i){const auto a=doc.palette()[i],b=observed.palette()[i];require(a.name==b.name&&a.subchords.size()==4&&b.subchords.size()==4,"Original palette names and four layers");for(size_t k=0;k<4;++k){const auto s=a.subchords[k],o=b.subchords[k];require(s.root==i&&s.root==o.root&&s.scaleRoot==o.scaleRoot&&s.chord==o.chord&&s.scale==o.scale&&s.inversions==o.inversions&&s.flags==o.flags&&s.levels==o.levels,"Default source palette matches original semantic layer");}}
    require(doc.scale()==observed.scale()&&read32(Chunk::parse(initial).find("perh")->data,40)==read32(Chunk::parse(original).find("perh")->data,40),"Original low24 default scale");
    const auto oldHeader=Chunk::parse(original).find("perh")->data;require(observed.set_scale(0xabcdef)&&((read32(Chunk::parse(observed.save_bytes()).find("perh")->data,40)^read32(oldHeader,40))&0xff000000)==0,"Scale author retains upper header byte");require(observed.undo()&&observed.save_bytes()==original,"Imported scale edit full byte Undo");
    std::uint16_t node=0;require(doc.insert_palette_node(5,&node)&&doc.nodes()[0].subchords.size()==4&&doc.nodes()[0].subchords[2].root==5,"Palette copies all four layers into node");require(doc.insert_signpost(node,0x100),"Palette copied node supplies Signpost");auto sub=doc.palette()[5].subchords[2];sub.chord=0x121;const auto before=doc.save_bytes();require(doc.edit_palette_subchord(5,2,sub)&&doc.palette()[5].subchords[2].chord==0x121&&doc.nodes()[0].subchords[2].chord==0x91&&doc.signposts()[0].subchords[2].chord==0x91,"Palette copy-on-write isolates placed nodes and Signposts");const auto after=doc.save_bytes();require(doc.undo()&&doc.save_bytes()==before&&doc.redo()&&doc.save_bytes()==after,"Palette layer single undo redo owns whole bytes");sub.root=6;require(!doc.edit_palette_subchord(5,2,sub)&&doc.save_bytes()==after,"Fixed palette root rejects mutation without history changes");require(!doc.edit_palette_subchord(24,0,sub)&&!doc.edit_palette_subchord(5,4,sub)&&doc.save_bytes()==after,"Palette bounds retain document");std::uint16_t untouched=500;require(!doc.insert_palette_node(24,&untouched)&&untouched==500&&doc.save_bytes()==after,"Invalid palette copy retains output and bytes");require(doc.undo()&&doc.save_bytes()==before&&doc.redo()&&doc.save_bytes()==after,"Invalid palette edits retain previous history");
    const auto base=dir/L"palette";std::filesystem::create_directories(base);Framework host;const auto index=host.new_chordmap();host.chordmap_document(index)=doc;host.save_chordmap(index,(base/L"Palette.cdp").wstring());host.save_project((base/L"Palette.pro").wstring());Framework restored;restored.open_project((base/L"Palette.pro").wstring());require(restored.chordmaps().size()==1&&restored.chordmap_document(0).save_bytes()==after&&!restored.dirty(),"Palette four layers isolated node Signpost restored by native Project");
    observed.load(original);auto imported=observed.palette()[0].subchords[1];imported.chord=0x121;require(observed.edit_palette_subchord(0,1,imported)&&observed.palette()[0].subchords[0].chord==0x91&&observed.palette()[1].subchords[1].chord==0x91,"Imported palette layer edit isolates all other roots and layers");require(observed.undo()&&observed.save_bytes()==original,"Original palette bytes checkpoint restored exactly");
}
