void container_document_tests(const std::filesystem::path& dir){
    ContainerDocument d;const auto initial=d.save_bytes();require(d.graph().objects().empty()&&!d.dirty(),"Standalone Container empty saved checkpoint");
    require(d.set_name(L"Owned Container")&&d.dirty(),"Standalone Unicode name edit");const auto named=d.save_bytes();
    auto broken=Chunk::parse(named);broken.find("conh")->data.clear();rejected([&]{d.load(broken.encode());},"Malformed Container rejected");
    require(d.save_bytes()==named&&d.undo()&&d.save_bytes()==initial,"Invalid load retains document and history");require(d.redo()&&d.save_bytes()==named,"Standalone Redo restores name");
    require(!d.set_name(std::wstring(L"bad\0text",8))&&d.save_bytes()==named,"Invalid standalone name retains bytes");
    auto extended=Chunk::parse(named);put32(extended.find("conh")->data,0,0x80000000u);extended.find("conh")->data.push_back(99);Chunk unknown;unknown.id="zzzz";unknown.data={1,2,3};extended.children.push_back(unknown);d.load(extended.encode());
    require(d.set_no_loads(true)&&d.graph().flags()==0x80000002u,"Standalone no-load changes only known flag");auto edited=Chunk::parse(d.save_bytes());require(edited.find("conh")->data.size()==5&&edited.find("conh")->data[4]==99&&edited.find("zzzz")->data==unknown.data,"Standalone header extension and unknown chunk retained");
    const auto folder=dir/L"ContainerProject";std::filesystem::create_directories(folder);Framework host;auto si=host.new_segment(),ci=host.new_container();
    require(!host.add_container_segment_reference(ci,si,L"Song"),"Unsaved Container reference rejected");host.save_segment(si,(folder/L"Song.sgp").wstring());host.save_container(ci,(folder/L"Owned.cop").wstring());const auto project=folder/L"ContainerProject.pro";host.save_project(project.wstring());
    require(host.add_container_segment_reference(ci,si,L"Song",true),"Saved native Project Segment reference created");auto& owned=host.container_document(ci);const auto reference=owned.save_bytes();
    require(!host.add_container_segment_reference(ci,si,L"Second")&&owned.save_bytes()==reference,"Repeated object rejected without mutation");
    auto entries=owned.graph().objects();require(entries.size()==1&&entries[0].reference&&entries[0].flags==1&&entries[0].alias==L"Song","Standalone typed reference alias and KEEP");
    require(owned.set_object_properties(0,L"Scene",false)&&owned.undo()&&owned.save_bytes()==reference&&owned.redo(),"Standalone reference edit Undo Redo");auto final=owned.save_bytes();require(!owned.remove_object(99)&&owned.save_bytes()==final,"Invalid removal retains document");require(owned.remove_object(0)&&owned.undo()&&owned.save_bytes()==final,"Standalone deletion Undo restores exact graph");
    host.save_container(ci,(folder/L"Owned.cop").wstring());host.save_project(project.wstring());const auto projectBytes=read_file(project.wstring());Framework reload;reload.open_project(project.wstring());require(reload.containers().size()==1&&reload.documents().size()==1&&!reload.dirty()&&reload.container_document(0).save_bytes()==final,"Native Project restores standalone Container owned bytes and checkpoint");reload.save_project(project.wstring());require(read_file(project.wstring())==projectBytes,"Native Container Project resave byte stable");
    auto p=Chunk::parse(projectBytes);bool runtime=false;for(auto& file:p.children)if(file.type=="file")if(auto name=file.find("name"))if(decode_utf16(name->data)==L"Owned.cop")runtime=decode_utf16(file.find("LIST","UNFO")->find("rnam")->data)==L"Owned.con";require(runtime,"Native Container entry retains .con runtime name");
    const auto count=reload.containers().size();require(reload.open_container((folder/L"Owned.cop").wstring())==0&&reload.containers().size()==count,"Repeated standalone path retains one owner");
    write_file_atomic((folder/L"Broken.cop").wstring(),broken.encode());rejected([&]{reload.open_container((folder/L"Broken.cop").wstring());},"Malformed standalone open rejected");require(reload.containers().size()==count&&!reload.dirty(),"Malformed open preserves Framework catalog and checkpoint");
}
