void dls_articulation_tests(const std::filesystem::path& dir,const std::wstring& inputPath,const std::wstring& originalPath){
 bool roundtrip=true;for(std::int64_t whole:{-32768LL,-1LL,0LL,32767LL})for(std::int64_t fraction=0;fraction<65536;++fraction){const auto raw=static_cast<std::int32_t>(whole*65536+fraction);if(parse_articulation_scale(format_articulation_scale(raw,true),true)!=raw)roundtrip=false;}
 require(roundtrip,"all fractional residues roundtrip at signed limits and zero");
 require(format_articulation_scale(INT32_MIN,true)==L"-32768"&&format_articulation_scale(INT32_MAX,true)==L"32767.9999847412109375"&&parse_articulation_scale(L"-1200.25",true)==-78659584,"exact fixed-point boundary and quarter cent");
 require(parse_articulation_scale(L"0.0000076293945312",true)==0&&parse_articulation_scale(L"0.0000076293945313",true)==1&&parse_articulation_scale(L"-0.0000076293945313",true)==-1,"sub-LSB rounding symmetric");
 require(parse_articulation_scale(L"-2147483648",false)==INT32_MIN&&parse_articulation_scale(L"2147483647",false)==INT32_MAX,"raw extremes retained");
 for(const auto* text:{L"32768",L"-32768.00002",L"1,5",L"nan",L"1e2",L"1.12345678901234567",L"",L"1."})rejected([&]{parse_articulation_scale(text,true);},"invalid units rejected");
 rejected([&]{parse_articulation_scale(L"1.5",false);},"raw fractional edit rejected");
 require(articulation_unit(0x500)==ArticulationUnit::Cents&&articulation_unit(1)==ArticulationUnit::Centibels&&articulation_unit(0x206)==ArticulationUnit::Timecents&&articulation_unit(0x20a)==ArticulationUnit::Raw&&articulation_unit(65535)==ArticulationUnit::Raw,"known destination units and opaque sustain fallback");
 DlsArticulation env{"lar2","art2",{{2,0,0x206,0,99},{0,0,65535,0,-7},{0,0,0x206,0,-65536}}};
 auto named=envelope_connections(env,envelope_parameters[0],-78659584);
 require(named.size()==3&&named[0].scale==99&&named[1].scale==-7&&named[2].scale==-78659584,"named Envelope preserves modulated and unknown records");
 auto added=envelope_connections(env,envelope_parameters[4],INT32_MIN);require(added.size()==4&&added[3].destination==0x20b&&added[3].scale==INT32_MIN,"explicit Level2 delay constant appended");
 auto duplicate=env;duplicate.connections.push_back(env.connections[2]);rejected([&]{envelope_connections(duplicate,envelope_parameters[0],0);},"ambiguous Envelope duplicate rejected");
 rejected([&]{envelope_connections({"lart","art1",{}},envelope_parameters[4],0);},"Level2 Envelope rejected in art1");
 const auto base=dir/L"Articulation";std::filesystem::create_directories(base);auto root=Chunk::parse(read_file(inputPath));const auto original=Chunk::parse(read_file(originalPath));
 const auto observed=*original.find("LIST","lins")->children.at(0).find("LIST","lar2");auto& ins=root.find("LIST","lins")->children.at(0);ins.children.erase(std::remove_if(ins.children.begin(),ins.children.end(),[](const Chunk& c){return c.id=="LIST"&&(c.type=="lart"||c.type=="lar2");}),ins.children.end());ins.children.push_back(observed);const auto before=root.encode();write_file_atomic((base/L"Before.dls").wstring(),before);
 Framework host;host.open_collection((base/L"Before.dls").wstring());auto& d=host.collection_document(0);const auto blocks=d.articulations(0);require(blocks.size()==1&&blocks[0].listType=="lar2"&&blocks[0].chunkId=="art1"&&blocks[0].connections.size()==1,"original saved explicit articulation identifiers");const auto c=blocks[0].connections[0];require(c.source==0&&c.control==0&&c.destination==0x500&&c.transform==0&&c.scale==INT32_MAX,"original saved raw connection fields");require(d.articulations(0,0).empty(),"no manufactured Region override");
 auto values=blocks[0].connections;values[0].scale=-65536;require(d.set_articulation_connections(0,{},0,values)&&d.dirty(),"owned Instrument connection edit");const auto edited=d.save_bytes();auto expected=root;put32(expected.find("LIST","lins")->children[0].find("LIST","lar2")->find("art1")->data,16,0xffff0000u);require(edited==expected.encode()&&d.articulations(0)[0].connections[0].scale==-65536,"signed scale changes exactly four bytes");require(!d.set_articulation_connections(0,{},0,values)&&!d.set_articulation_connections(0,{},99,values),"no-op and absent block preserve history");require(d.undo()&&d.save_bytes()==before&&!d.undo()&&d.redo()&&d.save_bytes()==edited,"one exact Undo Redo transaction");
 d.undo();rejected([&]{d.add_articulation(0,0,{"bad!","art1",values});},"invalid level rejected");rejected([&]{d.set_articulation_connections(0,999,0,values);},"missing Region rejected");require(d.save_bytes()==before&&!d.undo()&&d.redo()&&d.save_bytes()==edited,"rejection retains redo and bytes");
 DlsArticulation region{"lart","art1",{{0,0,1,0,INT32_MIN},{2,3,4,5,INT32_MAX}}};require(d.add_articulation(0,0,region)&&d.articulations(0,0).size()==1&&d.articulations(0)[0].connections[0].scale==-65536,"Region ownership independent");const auto overridden=d.save_bytes();require(d.undo()&&d.save_bytes()==edited&&d.redo()&&d.save_bytes()==overridden,"Region creation one transaction");auto expanded=region.connections;expanded.push_back({65535,65535,65535,65535,-1});require(d.set_articulation_connections(0,0,0,expanded)&&d.articulations(0,0)[0].connections.size()==3,"variable count opaque selectors");
 host.save_collection(0,(base/L"Edited.dls").wstring());host.save_project((base/L"Articulation.dmpj").wstring());const auto saved=d.save_bytes();Framework reload;reload.open_project((base/L"Articulation.dmpj").wstring());require(reload.collection_document(0).save_bytes()==saved&&!reload.dirty(),"separate Framework exact reload");reload.save_collection(0,(base/L"Resaved.dls").wstring());require(read_file((base/L"Resaved.dls").wstring())==saved,"exact collection resave");
 auto extended=root;auto& art=extended.find("LIST","lins")->children[0].find("LIST","lar2")->children[0];art.data.insert(art.data.begin()+8,{0xa1,0xb2,0xc3,0xd4});put32(art.data,0,12);art.data.insert(art.data.end(),{0xe5,0xf6,0x77});Chunk opaque;opaque.id="cdl ";opaque.data={9,8,7,6};extended.find("LIST","lins")->children[0].find("LIST","lar2")->children.push_back(opaque);DlsDocument extras;extras.load(extended.encode());auto enlarged=values;enlarged.push_back({1,2,3,4,-123456});require(extras.set_articulation_connections(0,{},0,enlarged),"extended header tail resize");auto expectedExtras=extended;auto& b=expectedExtras.find("LIST","lins")->children[0].find("LIST","lar2")->children[0].data;put32(b,4,2);put32(b,20,0xffff0000u);b.insert(b.begin()+24,12,0);b[24]=1;b[26]=2;b[28]=3;b[30]=4;put32(b,32,static_cast<std::uint32_t>(-123456));require(extras.save_bytes()==expectedExtras.encode(),"header tail conditional chunk siblings exact");require(extras.set_articulation_connections(0,{},0,{})&&extras.articulations(0)[0].connections.empty(),"empty explicit block retained");
 DlsDocument namedDoc;namedDoc.load(extended.encode());require(namedDoc.add_articulation(0,0,env),"owned Region Envelope block");const auto namedBefore=namedDoc.save_bytes();auto namedValues=envelope_connections(namedDoc.articulations(0,0).at(0),envelope_parameters[0],-78659584);require(namedDoc.set_articulation_connections(0,0,0,namedValues)&&namedDoc.articulations(0).at(0).connections[0].scale==INT32_MAX,"named Region changes leave Instrument untouched");const auto namedAfter=namedDoc.save_bytes();require(namedDoc.undo()&&namedDoc.save_bytes()==namedBefore&&namedDoc.redo()&&namedDoc.save_bytes()==namedAfter,"named Envelope exact single transaction history");DlsDocument namedReload;namedReload.load(namedAfter);require(namedReload.save_bytes()==namedAfter&&namedReload.articulations(0,0).at(0).connections[2].scale==-78659584,"named Envelope exact separate document reload");write_file_atomic((base/L"EnvelopeBefore.dls").wstring(),namedBefore);write_file_atomic((base/L"EnvelopeEdited.dls").wstring(),namedAfter);
 auto invalid=root;put32(invalid.find("LIST","lins")->children[0].find("LIST","lar2")->children[0].data,4,UINT32_MAX);const auto bad=invalid.encode();DlsDocument malformed;malformed.load(bad);rejected([&]{malformed.articulations(0);},"overflow count rejected");rejected([&]{malformed.set_articulation_connections(0,{},0,values);},"malformed edit rejected");require(malformed.save_bytes()==bad&&!malformed.undo(),"malformed edit atomic");write_file_atomic((base/L"ExtendedBefore.dls").wstring(),extended.encode());write_file_atomic((base/L"ExtendedEdited.dls").wstring(),expectedExtras.encode());write_file_atomic((base/L"ObservedArticulation.bin").wstring(),observed.encode());
}
