void lyric_document_tests(const std::filesystem::path& dir,const std::wstring& original=L""){
    SegmentDocument doc;const auto empty=doc.save_bytes();size_t selected=999;
    require(doc.add_lyric({3085,6144,8,L"\u6b4c\u8a5e \u03a9 first"},0,&selected)&&selected==0,"Lyric Unicode and independent physical/logical clocks");const auto one=doc.save_bytes();
    require(doc.add_lyric({769,0,16,L"earlier"},0,&selected)&&selected==0&&doc.lyrics()[1].logical==6144,"Lyric sorted insertion retains logical position");const auto two=doc.save_bytes();
    const auto clip=doc.copy_lyric(1);require(doc.save_bytes()==two&&doc.paste_lyric(clip,9217,3072,0,&selected)&&selected==2,"Lyric clipboard independent target clocks");const auto three=doc.save_bytes();
    require(doc.undo()&&doc.save_bytes()==two&&doc.redo()&&doc.save_bytes()==three,"Lyric paste whole-document history");
    require(doc.edit_lyric(2,{13,6144,4,L"\u66f4\u65b0 \xd83c\xdfb5"},0,&selected)&&selected==0,"Lyric text timing physical/logical edit and supplementary Unicode");const auto edited=doc.save_bytes();
    require(doc.delete_lyric(0)&&doc.lyrics().size()==2&&doc.undo()&&doc.save_bytes()==edited,"Lyric delete exact Undo");doc.undo();const auto before=doc.save_bytes();selected=999;
    require(!doc.add_lyric({-1,0,4,L"x"})&&!doc.add_lyric({0,-1,4,L"x"})&&!doc.add_lyric({doc.length(),0,4,L"x"})&&!doc.add_lyric({0,doc.length(),4,L"x"}),"Lyric both clock boundaries reject");
    for(auto timing:{0u,1u,2u,32u,64u,0xffffffffu})require(!doc.add_lyric({0,0,timing,L"x"}),"Lyric invalid delivery flag rejects");
    require(!doc.add_lyric({0,0,4,std::wstring(1,0xd800)})&&!doc.add_lyric({0,0,4,std::wstring(1,0xdc00)})&&!doc.add_lyric({0,0,4,std::wstring(L"a\0b",3)}),"Lyric malformed Unicode and embedded NUL reject");
    require(!doc.edit_lyric(999,{0,0,4,L"x"},0,&selected)&&!doc.delete_lyric(999)&&!doc.paste_lyric(clip,0,doc.length()),"Lyric invalid selection and paste refuse");
    rejected([&]{doc.paste_lyric(Bytes{1,2,3},0,0);},"Lyric malformed clipboard rejects");
    require(doc.save_bytes()==before&&selected==999&&doc.redo()&&doc.save_bytes()==edited,"Lyric failed edits preserve bytes output index and redo");
    SegmentDocument restored;restored.load(edited);require(restored.save_bytes()==edited&&!restored.dirty()&&restored.lyrics()[0].text==L"\u66f4\u65b0 \xd83c\xdfb5","Lyric saved reload Unicode exact");
    doc.select_track_group(2);require(doc.lyrics().empty()&&doc.add_lyric({0,0,16,L"group two"}),"Lyric independent group ownership");doc.select_track_group(1);require(doc.lyrics().size()==3,"Lyric peer group unchanged");
    auto root=Chunk::parse(doc.save_bytes());auto peer=lyric_track();add_lyric_event(peer,{256,512,4,L"peer"});root.find("LIST","trkl")->children.push_back(peer);restored.load(root.encode());require(restored.edit_lyric(0,{257,513,8,L"peer edited"},1)&&restored.lyrics(0).size()==3&&restored.lyrics(1)[0].physical==257,"nth Lyric track ownership");
    const auto base=dir/L"lyric-document";std::filesystem::create_directories(base);restored.save((base/L"Created.sgp").wstring());Framework host;host.open_segment((base/L"Created.sgp").wstring());host.save_project((base/L"lyric-document.pro").wstring());Framework reload;reload.open_project((base/L"lyric-document.pro").wstring());require(reload.document(0).save_bytes()==restored.save_bytes()&&!reload.dirty(),"Lyric native Project separate Framework reload");
    auto extended=lyric_track();add_lyric_event(extended,{12,24,16,L"old"});auto list=extended.find("LIST","lyrt")->find("LIST","lyrl");auto& entry=list->children[0];entry.find("lyrh")->data.insert(entry.find("lyrh")->data.end(),{0xaa,0xbb});entry.find("lyrn")->data.insert(entry.find("lyrn")->data.end(),{0xad,0xde});Chunk opaque;opaque.id="zzzz";opaque.data={1,2,3};opaque.padding=0x7e;entry.children.push_back(opaque);list->children.insert(list->children.begin(),opaque);const auto saved=extended.encode();
    require(change_lyric_event(extended,0,{13,25,8,L"new text"}),"Lyric extended entry edit");auto expected=Chunk::parse(saved);auto& ex=expected.find("LIST","lyrt")->find("LIST","lyrl")->children[1];put32(ex.find("lyrh")->data,4,8);put32(ex.find("lyrh")->data,8,25);put32(ex.find("lyrh")->data,12,13);ex.find("lyrn")->data=utf16(L"new text");ex.find("lyrn")->data.insert(ex.find("lyrn")->data.end(),{0xad,0xde});require(extended.encode()==expected.encode(),"Lyric retains header extension text tail unknown chunks padding");
    auto target=lyric_track();require(paste_lyric_event(target,copy_lyric_event(extended,0),27,39)&&target.find("LIST","lyrt")->find("LIST","lyrl")->children[0].find("zzzz")->encode()==opaque.encode(),"Lyric clipboard retains whole entry extensions");
    for(auto mutation:{0,1,2,3}){auto bad=Chunk::parse(saved);auto& e=bad.find("LIST","lyrt")->find("LIST","lyrl")->children[1];if(mutation==0)put32(e.find("lyrh")->data,0,1);if(mutation==1)e.find("lyrh")->data.resize(15);if(mutation==2)e.find("lyrn")->data={65,0};if(mutation==3)e.children.push_back(*e.find("lyrh"));const auto b=bad.encode();rejected([&]{change_lyric_event(bad,0,{1,2,4,L"x"});},"Lyric malformed source entry rejects");require(bad.encode()==b,"Lyric malformed source entry atomic");}
    if(!original.empty())for(const auto name:{L"OriginalEmptyLyric.sgp",L"OriginalUnicodeQuick.sgp",L"OriginalSeparatedBefore.sgp"}){const auto bytes=read_file((std::filesystem::path(original)/name).wstring());SegmentDocument observed;observed.load(bytes);const auto events=observed.lyrics();const auto none=std::wstring(name)==L"OriginalEmptyLyric.sgp",separated=std::wstring(name)==L"OriginalSeparatedBefore.sgp";
        require(observed.save_bytes()==bytes&&events.size()==(none?0:1),"Original Lyric no-edit bytes and event count");if(!none)require(events[0].physical==(separated?3085:3072)&&events[0].logical==(separated?6144:3072)&&events[0].timing==(separated?8:4)&&events[0].text==L"\u6b4c\u8a5e \u03a9 first","Original Lyric GUI properties match decoded contract");
        require(observed.add_lyric({9217,6144,16,L"source Unicode \u6b4c"}),"Original Lyric owned edit");const auto changed=observed.save_bytes();require(observed.undo()&&observed.save_bytes()==bytes&&observed.redo()&&observed.save_bytes()==changed,"Original Lyric exact history");observed.save((base/name).wstring());SegmentDocument reopened;reopened.load(read_file((base/name).wstring()));require(reopened.save_bytes()==changed&&reopened.lyrics().size()==events.size()+1,"Original Lyric edited save reload");
    }
    require(one!=empty,"Lyric materialized owned track");
}
