void mute_document_tests(const std::filesystem::path& dir,const std::wstring& original=L""){
    SegmentDocument doc;const auto empty=doc.save_bytes();size_t selected=999;
    require(valid_mute({0,0xfffffffbu,0xfffffffbu})&&valid_mute({0,0xfffffffbu,mute_channel_silent}),"Mute highest ordinary DWORD PChannel is allowed");
    require(doc.add_mute({768,0,mute_channel_silent},0,&selected)&&selected==0,"Mute owns silent map");
    require(doc.add_mute({1536,0,0})&&doc.add_mute({0,16,0},0,&selected)&&selected==2,"Mute DWORD PChannel16 and channel/time ordering");
    require(doc.add_mute({doc.length(),16,16}),"Mute terminal restore equals Segment length");const auto four=doc.save_bytes();auto clip=doc.copy_mute(0);
    require(doc.paste_mute(clip,2304,0,&selected)&&selected==2,"Mute clipboard new clock");const auto five=doc.save_bytes();
    require(doc.undo()&&doc.save_bytes()==four&&doc.redo()&&doc.save_bytes()==five,"Mute full-document UndoRedo");
    require(doc.edit_mute(2,{257,17,0},0,&selected)&&selected==4,"Mute channel edit reorders selection");const auto changed=doc.save_bytes();
    require(doc.delete_mute(4)&&doc.undo()&&doc.save_bytes()==changed,"Mute delete exact Undo");doc.undo();const auto before=doc.save_bytes();selected=999;
    for(auto c:{0xfffffffcu,0xfffffffdu,0xfffffffeu,0xffffffffu})require(!doc.add_mute({0,c,0}),"Mute broadcast source reserved rejects");
    for(auto c:{0xfffffffcu,0xfffffffdu,0xfffffffeu})require(!doc.add_mute({0,18,c}),"Mute broadcast map reserved rejects");
    require(!doc.add_mute({-1,18,0})&&!doc.add_mute({doc.length()+1,18,0})&&!doc.add_mute({768,0,0}),"Mute bounds and same channel/time collision reject");
    require(!doc.edit_mute(999,{0,1,0},0,&selected)&&!doc.delete_mute(999)&&!doc.paste_mute(clip,768)&&!doc.paste_mute(clip,doc.length()+1),"Mute invalid selection and paste reject");
    rejected([&]{doc.paste_mute(Bytes{1,2,3},0);},"Mute malformed clipboard rejects");rejected([&]{doc.add_mute({0,18,0},999);},"Mute invalid nth track rejects");
    require(doc.save_bytes()==before&&selected==999&&doc.redo()&&doc.save_bytes()==changed,"Mute rejected input preserves bytes selection and redo");
    require(!doc.edit_mute(0,doc.mutes()[0])&&doc.save_bytes()==changed,"Mute no-op unchanged");SegmentDocument restored;restored.load(changed);require(restored.save_bytes()==changed&&!restored.dirty()&&restored.mutes().size()==5,"Mute save reload");
    doc.select_track_group(2);require(doc.mutes().empty()&&doc.add_mute({0,32,mute_channel_silent}),"Mute group and DWORD PChannel32");doc.select_track_group(1);require(doc.mutes().size()==5,"Mute peer group unchanged");
    auto root=Chunk::parse(doc.save_bytes());auto peer=mute_track();add_mute_event(peer,{0,33,33});root.find("LIST","trkl")->children.push_back(peer);restored.load(root.encode());require(restored.edit_mute(0,{1,33,0},1)&&restored.mutes(0).size()==5&&restored.mutes(1)[0].time==1,"Mute nth-track ownership");
    const auto base=dir/L"mute-document";std::filesystem::create_directories(base);restored.save((base/L"Created.sgp").wstring());Framework host;host.open_segment((base/L"Created.sgp").wstring());host.save_project((base/L"mute-document.pro").wstring());Framework reload;reload.open_project((base/L"mute-document.pro").wstring());require(reload.document(0).save_bytes()==restored.save_bytes()&&!reload.dirty(),"Mute native Project separate Framework reload");
    auto extended=mute_track();add_mute_event(extended,{768,0,mute_channel_silent});auto& data=extended.find("mute")->data;put32(data,0,15);data.insert(data.end(),{0xaa,0xbb,0xcc});extended.find("mute")->padding=0x7f;Chunk opaque;opaque.id="zzzz";opaque.data={1,2,3};opaque.padding=0x7e;extended.children.push_back(opaque);const auto saved=extended.encode();require(change_mute_event(extended,0,{769,0,0}),"Mute extended stride edit");auto expected=Chunk::parse(saved);put32(expected.find("mute")->data,4,769);put32(expected.find("mute")->data,12,0);require(extended.encode()==expected.encode(),"Mute extensions siblings padding retained");auto target=Chunk::parse(saved);require(paste_mute_event(target,copy_mute_event(extended,0),2304)&&target.find("mute")->data.size()==34&&target.find("mute")->data[31]==0xaa,"Mute clipboard extension retained");auto shortTarget=mute_track();const auto shortBefore=shortTarget.encode();rejected([&]{paste_mute_event(shortTarget,copy_mute_event(extended,0),0);},"Mute incompatible stride refuses truncation");require(shortTarget.encode()==shortBefore,"Mute stride rejection atomic");
    for(auto mutation:{0,1,2,3}){auto bad=Chunk::parse(saved);auto p=bad.find("mute");if(mutation==0)put32(p->data,0,11);if(mutation==1)p->data.pop_back();if(mutation==2)put32(p->data,8,0xffffffffu);if(mutation==3)bad.children.push_back(*p);const auto b=bad.encode();rejected([&]{change_mute_event(bad,0,{1,2,0});},"Mute malformed source rejects");require(bad.encode()==b,"Mute malformed source atomic");}
    if(!original.empty())for(const auto name:{L"OriginalEmptyMute.sgp",L"OriginalOneBeatMute.sgp",L"OriginalMuteRemap.sgp"}){auto bytes=read_file((std::filesystem::path(original)/name).wstring());SegmentDocument observed;observed.load(bytes);auto events=observed.mutes();bool none=std::wstring(name)==L"OriginalEmptyMute.sgp",remap=std::wstring(name)==L"OriginalMuteRemap.sgp";require(observed.save_bytes()==bytes&&events.size()==(none?0:remap?4:2),"Original Mute no-edit bytes and count");if(!none)require(events[0].time==768&&events[0].channel==0&&events[0].map==mute_channel_silent&&events[1].time==1536&&events[1].map==0,"Original one-beat Mute/restore GUI contract");if(remap)require(events[2].time==0&&events[2].channel==1&&events[2].map==0&&events[3].time==observed.length()&&events[3].map==1,"Original Remap terminal restore GUI contract");require(observed.add_mute({2304,17,mute_channel_silent}),"Original Mute owned DWORD edit");auto edited=observed.save_bytes();require(observed.undo()&&observed.save_bytes()==bytes&&observed.redo()&&observed.save_bytes()==edited,"Original Mute exact history");observed.save((base/name).wstring());SegmentDocument reopened;reopened.load(read_file((base/name).wstring()));require(reopened.save_bytes()==edited&&reopened.mutes().size()==events.size()+1,"Original Mute edited save reload");}
    require(doc.save_bytes()!=empty,"Mute materialized owned track");
}
