void param_control_tests(const std::filesystem::path& dir){
    SegmentDocument d;const auto empty=d.save_bytes();ParamObject a;a.timeFormat=param_time_music;a.pchannel=16;a.objectClass[0]=0x94;
    require(d.add_parameter_object(a)&&d.parameter_controls().size()==1,"Parameter object DWORD address owned");
    require(d.add_parameter(0,7)&&d.add_parameter(0,8)&&!d.add_parameter(0,7),"Multiple unique parameters under one object");
    require(d.add_parameter_curve(0,0,{1536,2304,1,3,2,0})&&d.add_parameter_curve(0,0,{0,768,2,2,1,1}),"Curve additions sorted by signed music clock");
    require(d.parameter_controls()[0].parameters[0].curves[0].start==0&&d.parameter_controls()[0].parameters[1].index==8,"Typed parameters and curve order");const auto authored=d.save_bytes();
    require(d.undo()&&d.redo()&&d.save_bytes()==authored,"Curve whole-document Undo Redo");
    auto t=param_control_track();add_param_object(t,a);add_param_parameter(t,0,7);add_param_curve(t,0,0,{-768,0,1,2,2,3});
    auto o=t.find("LIST","prmt")->find("LIST","prol");o->find("proh")->data.push_back(0x81);auto p=o->find("LIST","prpl");p->find("prph")->data.push_back(0x82);auto c=p->find("prcc");put32(c->data,0,26);c->data.insert(c->data.end(),{0x83,0x84});Chunk unknown;unknown.id="zzzz";unknown.data={9};unknown.padding=0xa5;o->children.push_back(unknown);const auto extended=t.encode();
    require(param_control_objects(t)[0].parameters[0].curves[0].start==-768,"Negative pickup clock retained as signed SDK time");
    require(edit_param_curve(t,0,0,0,{-768,768,2,4,16,0}),"Extended curve edit");auto expected=Chunk::parse(extended);auto& cb=expected.find("LIST","prmt")->find("LIST","prol")->find("LIST","prpl")->find("prcc")->data;put32(cb,8,768);float start=2,end=4;std::memcpy(cb.data()+12,&start,4);std::memcpy(cb.data()+16,&end,4);put32(cb,20,16);put32(cb,24,0);
    require(t.encode()==expected.encode(),"Curve edit preserves object parameter record extensions and unknown padding");
    const auto clip=copy_param_curve(t,0,0,0);require(paste_param_curve(t,0,0,clip,1536)&&param_control_objects(t)[0].parameters[0].curves[1].end==3072,"Clipboard shifts complete extended curve duration");
    const auto beforePaste=t.encode();auto narrow=param_control_track();add_param_object(narrow,a);add_param_parameter(narrow,0,7);const auto narrowBefore=narrow.encode();rejected([&]{paste_param_curve(narrow,0,0,clip,0);},"Narrow destination refuses extension loss");require(narrow.encode()==narrowBefore,"Rejected clipboard leaves destination exact");
    require(!paste_param_curve(t,0,0,clip,INT32_MAX)&&t.encode()==beforePaste,"Clipboard end overflow rejected without mutation");
    auto broken=Chunk::parse(authored);auto tc=broken.find("LIST","trkl")->children.back().find("LIST","prmt")->find("LIST","prol")->find("LIST","prpl")->find("prcc");put32(tc->data,0,23);rejected([&]{d.load(broken.encode());},"Truncated curve stride load refused");require(d.save_bytes()==authored,"Failed load retains document");
    broken=Chunk::parse(authored);auto& missing=broken.find("LIST","trkl")->children.back().children;missing.erase(std::remove_if(missing.begin(),missing.end(),[](const Chunk& c){return c.id=="LIST"&&c.type=="prmt";}),missing.end());rejected([&]{d.load(broken.encode());},"Parameter class with missing payload refused");require(d.save_bytes()==authored,"Missing payload refusal retains document");
    broken=Chunk::parse(authored);auto oh=broken.find("LIST","trkl")->children.back().find("LIST","prmt")->find("LIST","prol")->find("proh");put32(oh->data,0,1);rejected([&]{d.load(broken.encode());},"Reserved object flags load refused");
    broken=Chunk::parse(authored);auto ph=broken.find("LIST","trkl")->children.back().find("LIST","prmt")->find("LIST","prol")->find("LIST","prpl")->find("prph");put32(ph->data,0,1);rejected([&]{d.load(broken.encode());},"Reserved parameter flags load refused");
    require(!d.edit_parameter_curve(0,0,0,{0,-1,0,1,2,0})&&!d.edit_parameter_curve(0,0,0,{0,1,std::numeric_limits<float>::infinity(),1,2,0})&&!d.edit_parameter_curve(0,0,0,{0,1,0,1,3,0})&&!d.edit_parameter_curve(0,0,0,{0,1,0,1,2,4}),"Invalid interval value enum and flags refuse");require(d.save_bytes()==authored&&d.undo()&&d.redo()&&d.save_bytes()==authored,"Rejected edits preserve bytes and history");
    a.timeFormat=param_time_reference;a.pchannel=0xfffffffb;a.index=UINT32_MAX;require(d.edit_parameter_object(0,a)&&d.parameter_controls()[0].address.pchannel==0xfffffffb,"Reference time and full DWORD object lookup preserved");
    const auto changed=d.save_bytes();require(d.delete_parameter_curve(0,0,0)&&d.undo()&&d.save_bytes()==changed,"Delete curve Undo");require(d.delete_parameter(0,1)&&d.undo()&&d.save_bytes()==changed,"Delete parameter Undo");require(d.delete_parameter_object(0)&&d.parameter_controls().empty()&&d.undo()&&d.save_bytes()==changed,"Delete object Undo");
    d.select_track_group(2);require(d.parameter_controls().empty()&&d.add_parameter_object(a)&&d.parameter_controls().size()==1,"New group creates separate Parameter track");d.select_track_group(1);require(d.parameter_controls()[0].parameters.size()==2,"Other group parameter strip retained");
    const auto scenario=dir/L"Scenario";std::filesystem::create_directories(scenario);d.save((scenario/L"Song.sgp").wstring());Framework host;host.open_segment((scenario/L"Song.sgp").wstring());host.save_project((scenario/L"Scenario.pro").wstring());Framework reload;reload.open_project((scenario/L"Scenario.pro").wstring());require(reload.document(0).save_bytes()==d.save_bytes()&&!reload.dirty(),"Native Project independent document restores Parameter tracks");
    require(empty!=d.save_bytes(),"Parameter edits are real saved document changes");
}
