struct ParamAutomationTrace {std::mutex lock;unsigned sets=0,envelopes=0,flushes=0,formats=0;std::vector<MP_ENVELOPE_SEGMENT> segments;std::vector<std::pair<LONG,float>> notes;};
struct SourceParameterTool final:producer::runtime::Tool,IMediaParams,IMediaParamInfo,IPersistStream {
    LONG refs=1;GUID classId;ParamAutomationTrace& trace;float value=1;GUID timeFormat{};
    SourceParameterTool(REFGUID id,ParamAutomationTrace& t):classId(id),trace(t){}
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void** out)override{if(!out)return E_POINTER;*out=nullptr;if(id==IID_IUnknown||id==producer::runtime::toolId)*out=static_cast<producer::runtime::Tool*>(this);else if(id==__uuidof(IMediaParams))*out=static_cast<IMediaParams*>(this);else if(id==__uuidof(IMediaParamInfo))*out=static_cast<IMediaParamInfo*>(this);else if(id==IID_IPersist||id==IID_IPersistStream)*out=static_cast<IPersistStream*>(this);else return E_NOINTERFACE;AddRef();return S_OK;}
    ULONG STDMETHODCALLTYPE AddRef()override{return InterlockedIncrement(&refs);}
    ULONG STDMETHODCALLTYPE Release()override{const auto n=InterlockedDecrement(&refs);if(!n)delete this;return n;}
    HRESULT STDMETHODCALLTYPE GetClassID(CLSID* out)override{if(!out)return E_POINTER;*out=classId;return S_OK;}
    HRESULT STDMETHODCALLTYPE IsDirty()override{return S_FALSE;}
    HRESULT STDMETHODCALLTYPE Load(IStream*)override{return E_NOTIMPL;}
    HRESULT STDMETHODCALLTYPE Save(IStream*,BOOL)override{return S_OK;}
    HRESULT STDMETHODCALLTYPE GetSizeMax(ULARGE_INTEGER* n)override{if(!n)return E_POINTER;n->QuadPart=0;return S_OK;}
    HRESULT STDMETHODCALLTYPE Init(producer::runtime::Graph*)override{return S_OK;}
    HRESULT STDMETHODCALLTYPE GetMsgDeliveryType(DWORD* out)override{if(!out)return E_POINTER;*out=8;return S_OK;}
    HRESULT STDMETHODCALLTYPE GetMediaTypeArraySize(DWORD* out)override{if(!out)return E_POINTER;*out=1;return S_OK;}
    HRESULT STDMETHODCALLTYPE GetMediaTypes(DWORD** out,DWORD n)override{if(!out||!*out)return E_POINTER;if(n!=1)return E_INVALIDARG;**out=1;return S_OK;}
    HRESULT STDMETHODCALLTYPE GetParam(DWORD index,MP_DATA* out)override{if(!out)return E_POINTER;if(index)return E_INVALIDARG;std::lock_guard<std::mutex> guard(trace.lock);*out=value;return S_OK;}
    HRESULT STDMETHODCALLTYPE SetParam(DWORD index,MP_DATA v)override{if(index||!std::isfinite(v)||v<0||v>1)return E_INVALIDARG;std::lock_guard<std::mutex> guard(trace.lock);++trace.sets;value=v;return S_OK;}
    HRESULT STDMETHODCALLTYPE AddEnvelope(DWORD index,DWORD count,MP_ENVELOPE_SEGMENT* curves)override{if(index||(count&&!curves))return E_INVALIDARG;std::lock_guard<std::mutex> guard(trace.lock);++trace.envelopes;for(DWORD i=0;i<count;++i){trace.segments.push_back(curves[i]);std::cerr<<"parameter envelope "<<curves[i].rtStart<<".."<<curves[i].rtEnd<<" value="<<curves[i].valStart<<".."<<curves[i].valEnd<<" curve="<<curves[i].iCurve<<" flags="<<curves[i].flags<<"\n";}return S_OK;}
    HRESULT STDMETHODCALLTYPE FlushEnvelope(DWORD index,REFERENCE_TIME,REFERENCE_TIME)override{if(index&&index!=DWORD_ALLPARAMS)return E_INVALIDARG;std::lock_guard<std::mutex> guard(trace.lock);++trace.flushes;return S_OK;}
    HRESULT STDMETHODCALLTYPE SetTimeFormat(GUID format,MP_TIMEDATA data)override{std::cerr<<"parameter time format="<<std::hex<<format.Data1<<std::dec<<" data="<<data<<"\n";GUID music;std::memcpy(&music,param_time_music.data(),16);if(format!=music)return E_INVALIDARG;std::lock_guard<std::mutex> guard(trace.lock);timeFormat=format;++trace.formats;return S_OK;}
    HRESULT STDMETHODCALLTYPE GetParamCount(DWORD* n)override{if(!n)return E_POINTER;*n=1;return S_OK;}
    HRESULT STDMETHODCALLTYPE GetParamInfo(DWORD index,MP_PARAMINFO* out)override{if(!out)return E_POINTER;if(index)return E_INVALIDARG;*out={};out->mpType=MPT_FLOAT;out->mopCaps=MP_CAPS_CURVE_JUMP|MP_CAPS_CURVE_LINEAR;out->mpdMinValue=0;out->mpdMaxValue=1;out->mpdNeutralValue=1;wcscpy_s(out->szLabel,L"Velocity gain");return S_OK;}
    HRESULT STDMETHODCALLTYPE GetParamText(DWORD index,WCHAR** out)override{if(!out)return E_POINTER;*out=nullptr;return index?E_INVALIDARG:E_NOTIMPL;}
    HRESULT STDMETHODCALLTYPE GetNumTimeFormats(DWORD* n)override{if(!n)return E_POINTER;*n=1;return S_OK;}
    HRESULT STDMETHODCALLTYPE GetSupportedTimeFormat(DWORD i,GUID* out)override{if(!out)return E_POINTER;if(i)return E_INVALIDARG;std::memcpy(out,param_time_music.data(),16);return S_OK;}
    HRESULT STDMETHODCALLTYPE GetCurrentTimeFormat(GUID* out,MP_TIMEDATA* data)override{if(!out||!data)return E_POINTER;std::lock_guard<std::mutex> guard(trace.lock);*out=timeFormat;*data=0;return S_OK;}
    HRESULT STDMETHODCALLTYPE ProcessPMsg(producer::runtime::Performance*,producer::runtime::Message* p)override{if(!p)return E_POINTER;if(p->type==1&&p->size>=sizeof(producer::runtime::NoteMessage)){std::lock_guard<std::mutex> guard(trace.lock);float gain=value;for(const auto& e:trace.segments)if(p->musicTime>=e.rtStart){gain=e.valEnd;if(p->musicTime<e.rtEnd){if(e.iCurve==MP_CURVE_JUMP)gain=e.valStart;else if(e.iCurve==MP_CURVE_LINEAR&&e.rtEnd>e.rtStart)gain=e.valStart+(e.valEnd-e.valStart)*static_cast<float>(p->musicTime-e.rtStart)/static_cast<float>(e.rtEnd-e.rtStart);}}auto& note=*reinterpret_cast<producer::runtime::NoteMessage*>(p);trace.notes.push_back({p->musicTime,gain});std::cerr<<"parameter note "<<p->musicTime<<" gain="<<gain<<"\n";note.velocity=static_cast<BYTE>(std::clamp(std::lround(note.velocity*gain),0l,127l));}return p->graph&&SUCCEEDED(p->graph->StampPMsg(p))?DMUS_S_REQUEUE:DMUS_S_FREE;}
    HRESULT STDMETHODCALLTYPE Flush(producer::runtime::Performance*,producer::runtime::Message*,LONGLONG)override{return DMUS_S_FREE;}
};
void param_control_runtime_tests(const std::filesystem::path& dir){
    ParamGuid id{};id[0]=0x94;GUID toolId;std::memcpy(&toolId,id.data(),16);ParamAutomationTrace trace;
    ToolGraphDocument graph;graph.add_tool(id,{0});AudioPathDocument path;path.set_tool_graph(graph.save_bytes());auto d=SegmentDocument::playback_test();d.set_audio_path(path.save_bytes());ParamObject a;a.timeFormat=param_time_music;a.objectClass=id;
    require(d.add_parameter_object(a)&&d.add_parameter(0,0)&&d.add_parameter_curve(0,0,{0,3072,.25f,.25f,1,0})&&d.add_parameter_curve(0,0,{3072,6144,.75f,.75f,1,0}),"Authored AudioPath Tool velocity parameter curves");const auto source=d.save_bytes();write_file_atomic((dir/L"Automation.sgp").wstring(),source);
    Conductor c;c.set_tool_factories({{id,[&](const GraphTool&){return new SourceParameterTool(toolId,trace);}}});c.enable_note_observation();c.play(read_file((dir/L"Automation.sgp").wstring()),L"",nullptr);const auto deadline=GetTickCount64()+10000;bool started=false,finished=false;while(GetTickCount64()<deadline){auto p=c.position();started=started||p.playing;if(started&&!p.playing){finished=true;break;}Sleep(20);}require(finished,"Parameter Track actual playback starts and naturally completes");c.stop();const auto notes=c.observed_notes();
    {std::lock_guard<std::mutex> guard(trace.lock);require(trace.formats&&trace.envelopes&&trace.segments.size()>=2,"OS Parameter Track calls source IMediaParams with music envelopes");require(trace.notes.size()==8,"Source parameter Tool receives eight actual note messages");}
    require(notes.size()==8&&std::all_of(notes.begin(),notes.begin()+4,[](const PlaybackNote& n){return n.velocity==24;})&&std::all_of(notes.begin()+4,notes.end(),[](const PlaybackNote& n){return n.velocity==72;}),"Authored curves change generated velocities at measure boundary");require(d.save_bytes()==source&&read_file((dir/L"Automation.sgp").wstring())==source,"Automation retains owned and saved source bytes");require(!c.note_observation_overflow()&&!c.note_observation_forwarding_failed(),"Automation forwards notes without observation failure");c.shutdown();
}
