void script_document_tests(const std::filesystem::path& dir,const std::wstring& runtime,const std::wstring& design){
    for(const auto& path:{runtime,design}){
        const auto original=read_file(path);ScriptDocument d;d.load(original);const auto container=d.container_bytes();const auto source=d.source();
        require(d.save_bytes()==original&&!d.dirty(),"Original Script exact load and saved checkpoint");
        require(d.language()==L"VBScript"&&d.flags()==3&&source&&source->find(L"Sub ")!=std::wstring::npos,"Original Script typed language flags source");
        auto tree=Chunk::parse(original);auto metadata=tree;metadata.children.erase(std::remove_if(metadata.children.begin(),metadata.children.end(),[](const auto& c){return c.id=="scsr";}),metadata.children.end());
        require(d.set_source(*source+L"\r\n' source editor Unicode \x65e5\x672c\r\n"),"Script source edit");const auto edited=d.save_bytes();auto after=Chunk::parse(edited);after.children.erase(std::remove_if(after.children.begin(),after.children.end(),[](const auto& c){return c.id=="scsr";}),after.children.end());
        require(after.encode()==metadata.encode()&&d.container_bytes()==container,"Source edit changes only scsr and retains whole embedded Container");
        require(d.undo()&&d.save_bytes()==original&&!d.dirty(),"Source Undo restores original saved checkpoint");
        require(d.redo()&&d.save_bytes()==edited&&d.dirty(),"Source Redo restores Unicode whole text");
        auto broken=tree;broken.find("scsr")->data.pop_back();rejected([&]{d.load(broken.encode());},"Truncated source UTF16 rejected");
        require(d.save_bytes()==edited&&d.undo()&&d.save_bytes()==original,"Rejected load retains document and Undo history");d.redo();
        const std::wstring nul(L"bad\0text",8);require(!d.set_source(nul)&&d.save_bytes()==edited,"Embedded NUL edit retains document");
        std::wstring surrogate(1,static_cast<wchar_t>(0xd800));require(!d.set_source(surrogate)&&d.save_bytes()==edited,"Unpaired surrogate edit retains document");
        broken=tree;broken.children.push_back(*tree.find("scsr"));rejected([&]{d.load(broken.encode());},"Ambiguous source rejected");
        broken=tree;broken.find("schd")->data.resize(3);rejected([&]{d.load(broken.encode());},"Truncated header rejected");
        require(d.set_properties(L"Script edited",L"VBScript",false,true)&&d.flags()==2&&d.name()==L"Script edited"&&d.container_bytes()==container,"Typed properties change source-independent flags and name");
        require(!d.set_properties(L"bad",L"",true,true)&&d.name()==L"Script edited"&&d.flags()==2,"Invalid combined properties are atomic");
        const auto final=d.save_bytes();const auto output=dir/(std::filesystem::path(path).extension()==L".spt"?L"edited.spt":L"edited.spp");d.save(output.wstring());ScriptDocument restored;restored.load(read_file(output.wstring()));
        require(!d.dirty()&&restored.save_bytes()==final&&restored.source()==d.source()&&restored.name()==d.name(),"Disk save and separate document restore typed properties and source");
        auto external=tree;external.children.erase(std::remove_if(external.children.begin(),external.children.end(),[](const auto& c){return c.id=="scsr";}),external.children.end());Chunk ref;ref.id="LIST";ref.type="DMRF";Chunk h;h.id="refh";h.data.resize(20);put32(h.data,16,18);ref.children.push_back(h);Chunk file;file.id="file";file.data=utf16(L"FarmMusic.vbs");ref.children.push_back(file);external.children.push_back(ref);
        const auto ext=external.encode();d.load(ext);require(!d.source()&&d.source_reference()==ref.encode(),"External source reference retained without executing or reading external file");
        require(d.set_source(L"Sub Main\r\nEnd Sub\r\n")&&d.source_reference().empty()&&d.container_bytes()==container,"Explicit source replacement adopts owned text and retains Container");
        require(d.undo()&&d.save_bytes()==ext,"Undo restores external source representation exactly");
        auto extended=tree;put32(extended.find("schd")->data,0,0x80000003);extended.find("schd")->data.push_back(0x5a);d.load(extended.encode());require(d.set_properties(d.name(),d.language(),false,false)&&d.flags()==0x80000000&&Chunk::parse(d.save_bytes()).find("schd")->data.back()==0x5a,"Known flag edit retains unknown flags and extended header bytes");
        require(read_file(path)==original,"Original Script fixture stays unchanged");
    }
    // Container graph edits share the owning Script history and preserve source.
    ScriptDocument graphDoc;const auto graphOriginal=read_file(runtime);graphDoc.load(graphOriginal);auto graphObjects=graphDoc.container().objects();
    require(graphObjects.size()==10&&graphObjects[0].alias==std::optional<std::wstring>(L"BGDawn")&&graphObjects[0].reference&&graphDoc.container().flags()==2,"Original Container exposes alias reference flags and ten objects");
    const auto graphSource=graphDoc.source();const auto payload=graphObjects[0].payload.encode();
    require(graphDoc.set_contained_properties(0,L"Alias Unicode \x65e5\x672c",true),"Container alias and KEEP edit");
    require(graphDoc.container().objects()[0].flags==1&&graphDoc.container().objects()[0].payload.encode()==payload&&graphDoc.source()==graphSource,"Container edit preserves reference payload and Script source");
    require(graphDoc.undo()&&graphDoc.save_bytes()==graphOriginal,"Container Undo restores complete original Script");require(graphDoc.redo()&&graphDoc.dirty(),"Container Redo restores edited graph");
    require(graphDoc.set_container_no_loads(false)&&graphDoc.container().flags()==0,"Container NOLOADS edit");const auto graphEdited=graphDoc.save_bytes();
    require(!graphDoc.set_contained_properties(10,L"invalid index",false)&&graphDoc.save_bytes()==graphEdited,"Invalid Container object index keeps document");
    require(!graphDoc.set_contained_properties(0,std::wstring(1,static_cast<wchar_t>(0xd800)),false)&&graphDoc.save_bytes()==graphEdited,"Invalid Container alias keeps whole document");
    auto malformed=Chunk::parse(graphOriginal);auto graphRoot=malformed.find("RIFF","DMCN");auto objectList=graphRoot->find("LIST","cosl");objectList->children[0].find("cobh")->data.resize(27);rejected([&]{graphDoc.load(malformed.encode());},"Short contained object header rejected before adoption");require(graphDoc.save_bytes()==graphEdited&&graphDoc.undo(),"Rejected graph retains document and existing Undo");graphDoc.redo();
    malformed=Chunk::parse(graphOriginal);objectList=malformed.find("RIFF","DMCN")->find("LIST","cosl");objectList->children[0].find("LIST","DMRF")->find("refh")->data[0]^=1;rejected([&]{graphDoc.load(malformed.encode());},"Container reference class mismatch rejected");
    malformed=Chunk::parse(graphOriginal);objectList=malformed.find("RIFF","DMCN")->find("LIST","cosl");objectList->children[0].children.push_back(*objectList->children[0].find("LIST","DMRF"));rejected([&]{graphDoc.load(malformed.encode());},"Ambiguous Container payload rejected");
    require(graphDoc.save_bytes()==graphEdited,"Malformed graph rejections preserve Script bytes");
    graphDoc.save((dir/L"graph.spp").wstring());ScriptDocument graphReload;graphReload.load(read_file((dir/L"graph.spp").wstring()));require(graphReload.container().objects()[0].alias==graphDoc.container().objects()[0].alias&&!graphDoc.dirty(),"Container typed alias persists with Script save checkpoint");
    ScriptDocument empty;ScriptDocument reload;reload.load(empty.save_bytes());require(reload.source()==std::optional<std::wstring>(L"")&&reload.flags()==0&&reload.language()==L"VBScript","New Script has valid empty owned source and explicit load flags");
    const auto scenario=dir/L"Scenario";std::filesystem::create_directories(scenario);const auto authored=scenario/L"Authored.spp",original=scenario/L"FarmMusic.spp",project=scenario/L"Scenario.pro";
    write_file_atomic(original.wstring(),read_file(design));Framework host;host.new_script();require(host.scripts().size()==1&&host.dirty(),"Framework new Script owns dirty unsaved document");
    auto& owned=host.script_document(0);owned.set_properties(L"Authored",L"VBScript",true,false);owned.set_source(L"Sub Main\r\nEnd Sub\r\n");host.save_script(0,authored.wstring());
    require(host.open_script(authored.wstring())==0&&host.scripts().size()==1,"Script catalog has one owner per case-insensitive path");
    const auto originalIndex=host.open_script(original.wstring());require(originalIndex==1&&host.script_document(1).save_bytes()==read_file(design),"Framework owns original Script including embedded Container");
    require(host.script_document(1).set_contained_properties(0,L"Project alias",true),"Framework owns editable Container alias");host.save_script(1,original.wstring());
    host.save_project(project.wstring());const auto savedProject=read_file(project.wstring());const auto root=Chunk::parse(savedProject);size_t entries=0;for(const auto& f:root.children)if(f.id=="LIST"&&f.type=="file"){++entries;require(f.find("LIST","UNFO")&&f.find("LIST","UNFO")->find("rnam")&&std::filesystem::path(decode_utf16(f.find("LIST","UNFO")->find("rnam")->data)).extension()==L".spt","Native Script file metadata uses runtime .spt");}
    require(entries==2&&!host.dirty(),"Native Project owns authored and original Script entries");
    Framework restored;restored.open_project(project.wstring());require(restored.scripts().size()==2&&restored.script_document(0).source()==owned.source()&&restored.script_document(1).container_bytes()==host.script_document(1).container_bytes()&&!restored.dirty(),"Native Project reload owns source properties and embedded Container");
    owned.set_source(L"Sub Main\r\n' Changed\r\nEnd Sub\r\n");rejected([&]{host.save_project(project.wstring());},"Dirty Script prevents Project metadata replacement");require(read_file(project.wstring())==savedProject,"Failed Project save keeps whole destination");
    const auto changed=owned.save_bytes();host.save_script(0,authored.wstring());host.save_project(project.wstring());Framework changedReload;changedReload.open_project(project.wstring());require(changedReload.script_document(0).save_bytes()==changed,"Document save journal restores changed source in native Project");
    const auto before=host.scripts().size();rejected([&]{host.save_script(0,original.wstring());},"Another Script destination owner rejects Save As");require(host.scripts().size()==before&&owned.save_bytes()==changed,"Failed Script Save As keeps ownership and whole document");

    // Fresh Reference Runtime authoring uses native Project file identity, not a cloned old entry.
    const auto refDir=dir/L"Reference";std::filesystem::create_directories(refDir);const auto contentPath=refDir/L"Content.sgp",scriptPath=refDir/L"Reference.spp",refProject=refDir/L"Reference.pro";
    auto content=SegmentDocument::playback_test(60);write_file_atomic(contentPath.wstring(),content.save_bytes());Framework refs;const auto si=refs.open_segment(contentPath.wstring()),di=refs.new_script();auto& authoredRef=refs.script_document(di);authoredRef.set_properties(L"Reference",L"VBScript",true,false);authoredRef.set_source(L"Sub LoadContent()\r\nContent.Load\r\nEnd Sub\r\n");refs.save_script(di,scriptPath.wstring());refs.save_project(refProject.wstring());const auto refBefore=authoredRef.save_bytes(),sourceBefore=content.save_bytes(),projectBefore=read_file(refProject.wstring());
    require(refs.add_script_segment_reference(di,si,L"Content",true),"Fresh owned Project Segment reference authored without cloning");const auto refAdded=authoredRef.save_bytes();auto authoredObjects=authoredRef.container().objects();require(authoredObjects.size()==1&&authoredObjects[0].reference&&authoredObjects[0].alias==std::optional<std::wstring>(L"Content")&&authoredObjects[0].flags==1,"Fresh reference typed alias KEEP and membership");
    auto authoredTree=Chunk::parse(refAdded);const auto& authoredEntry=authoredTree.find("RIFF","DMCN")->find("LIST","cosl")->children[0];const auto projectTree=Chunk::parse(projectBefore);const Chunk* projectFile=nullptr;for(const auto& f:projectTree.children)if(f.type=="file"&&decode_utf16(f.find("name")->data)==L"Content.sgp")projectFile=&f;
    require(projectFile&&authoredEntry.find("cobu")->data==Bytes({1,0})&&authoredEntry.find("jzfr")->data.size()==32&&std::equal(projectFile->find("filh")->data.begin(),projectFile->find("filh")->data.begin()+16,authoredEntry.find("jzfr")->data.begin()),"Design reference uses observed cobu membership and actual native file identity");
    const auto refPayload=authoredEntry.find("LIST","DMRF");require(read32(refPayload->find("refh")->data,16)==0x13&&refPayload->find("guid")->data==Chunk::parse(sourceBefore).find("guid")->data&&decode_utf16(refPayload->find("file")->data)==L"Content.sgp","Fresh DMRF declares exactly class object GUID and filename");
    require(authoredRef.undo()&&authoredRef.save_bytes()==refBefore&&authoredRef.redo()&&authoredRef.save_bytes()==refAdded,"Fresh reference is one shared Script history action");
    require(!refs.add_script_segment_reference(di,si,L"OtherAlias")&&authoredRef.save_bytes()==refAdded,"Duplicate object with different alias rejected without byte change");
    require(!authoredRef.remove_contained_object(1)&&authoredRef.save_bytes()==refAdded,"Invalid removal preserves graph and history");
    require(authoredRef.remove_contained_object(0)&&authoredRef.container().objects().empty()&&authoredRef.source()==std::optional<std::wstring>(L"Sub LoadContent()\r\nContent.Load\r\nEnd Sub\r\n"),"Removal changes only selected object and retains Script source");
    require(authoredRef.undo()&&authoredRef.save_bytes()==refAdded&&authoredRef.redo()&&authoredRef.container().objects().empty()&&authoredRef.undo()&&authoredRef.save_bytes()==refAdded,"Remove Undo Redo restores whole reference including Producer metadata");
    std::array<std::uint8_t,16> objectId{},fileId{};objectId[0]=0x77;fileId[0]=0x66;
    for(const auto& name:{L"../Escape.sgp",L"a\\b.sgp",L"a:stream.sgp",L"Runtime.sgt"})require(!authoredRef.add_segment_reference(objectId,fileId,name,L"Second")&&authoredRef.save_bytes()==refAdded,"Invalid design filename preserves document");
    require(!authoredRef.add_segment_reference(objectId,fileId,L"Second.sgp",L"content")&&authoredRef.save_bytes()==refAdded,"Case insensitive duplicate alias rejected atomically");
    auto emptyId=objectId;emptyId.fill(0);require(!authoredRef.add_segment_reference(emptyId,fileId,L"Second.sgp",L"Second")&&!authoredRef.add_segment_reference(objectId,emptyId,L"Second.sgp",L"Second")&&authoredRef.save_bytes()==refAdded,"Null object or native file identity rejected atomically");
    auto oldGraph=Chunk::parse(refAdded);Chunk opaque;opaque.id="zzzz";opaque.data={1,2,3};oldGraph.find("RIFF","DMCN")->find("LIST","cosl")->children.insert(oldGraph.find("RIFF","DMCN")->find("LIST","cosl")->children.begin(),opaque);ScriptDocument opaqueDoc;opaqueDoc.load(oldGraph.encode());require(opaqueDoc.add_segment_reference(objectId,fileId,L"Second.sgp",L"Second")&&opaqueDoc.remove_contained_object(0)&&Chunk::parse(opaqueDoc.save_bytes()).find("RIFF","DMCN")->find("LIST","cosl")->children[0].encode()==opaque.encode(),"Object indices skip opaque siblings and preserve their exact bytes");
    refs.save_script(di,scriptPath.wstring());refs.save_project(refProject.wstring());Framework refRestore;refRestore.open_project(refProject.wstring());require(refRestore.scripts().size()==1&&refRestore.documents().size()==1&&refRestore.script_document(0).save_bytes()==refAdded&&!refRestore.dirty(),"Native Project separate owner reload restores fresh reference metadata and source");
    require(read_file(contentPath.wstring())==sourceBefore&&refs.documents()[si].document->save_bytes()==sourceBefore,"Reference authoring never changes referenced Segment bytes");
    refs.documents()[si].document->add_tempo(768,90);require(!refs.add_script_segment_reference(di,si,L"Unsafe")&&authoredRef.save_bytes()==refAdded,"Unsaved source cannot produce stale reference identity");
    host.new_project();require(host.scripts().empty(),"New Project clears previous Script ownership");
    // External source closure belongs to the copied Project even though the
    // document model never loads or executes the text file.
    const auto externalDir=dir/L"External";std::filesystem::create_directories(externalDir);auto ext=Chunk::parse(empty.save_bytes());ext.children.erase(std::remove_if(ext.children.begin(),ext.children.end(),[](const auto& c){return c.id=="scsr";}),ext.children.end());Chunk ref;ref.id="LIST";ref.type="DMRF";Chunk rh;rh.id="refh";rh.data.resize(20);put32(rh.data,16,18);ref.children.push_back(rh);Chunk rf;rf.id="file";rf.data=utf16(L"Source.vbs");ref.children.push_back(rf);ext.children.push_back(ref);write_file_atomic((externalDir/L"External.spp").wstring(),ext.encode());const Bytes externalText={'\'', ' ', 'c', 'o', 'p', 'y'};write_file_atomic((externalDir/L"Source.vbs").wstring(),externalText);Framework externalHost;externalHost.open_script((externalDir/L"External.spp").wstring());externalHost.save_project((externalDir/L"External.pro").wstring());externalHost.copy_project((dir/L"Copied"/L"Copied.pro").wstring());Framework copy;copy.open_project((dir/L"Copied"/L"Copied.pro").wstring());require(copy.scripts().size()==1&&!copy.script_document(0).source()&&read_file((dir/L"Copied"/L"Source.vbs").wstring())==externalText,"Native Project copy preserves Script and external source closure");
}
