// Diagnostic matrix records actual sender bytes. It does not replace the exact
// Trace acceptance assertion below or count empty strings as correct output.
void script_sender_diagnostic_tests(const std::filesystem::path& dir){
    const std::array<std::wstring,3> texts={L"ASCII Trace",L"\u65e5\u672c",L"\u03a9 \xd83c\xdfb5"};
    for(size_t i=0;i<texts.size();++i){
        ScriptDocument doc;doc.set_properties(L"Sender diagnostic",L"VBScript",false,false);
        doc.set_source(L"Dim Score\r\nScore = 0\r\nSub Emit()\r\nTrace \""+texts[i]+L"\"\r\nScore = Score + 1\r\nEnd Sub\r\nSub Fault()\r\nScore = 1 / 0\r\nEnd Sub\r\n");
        const auto source=doc.save_bytes();const auto prefix=dir/(L"sender-"+std::to_wstring(i));write_file_atomic(prefix.wstring()+L".spp",source);
        Conductor player;player.enable_script_message_observation();require(player.load_script(source,L"",nullptr).passed(),"Sender matrix initializes owned Script");require(player.script_session().call(L"Emit").passed(),"Sender matrix actual Emit succeeds");script_track_wait(400);
        const auto messages=player.observed_script_messages();std::cerr<<"sender case="<<i<<" expectedChars="<<texts[i].size()<<" messages="<<messages.size()<<"\n";
        for(size_t j=0;j<messages.size();++j){const auto& m=messages[j];std::cerr<<"sender case="<<i<<" message="<<j<<" chars="<<m.text.size()<<" bytes="<<m.payloadBytes<<" flags="<<m.flags<<" exact="<<(m.text==texts[i])<<"\n";write_file_atomic(prefix.wstring()+L"-"+std::to_wstring(j)+L".bin",Bytes(m.payloadPrefix.begin(),m.payloadPrefix.end()));}
        require(messages.size()==1&&!player.script_message_observation_failed(),"Sender matrix receives one well-formed diagnostic message; text correctness separate");
        const auto fault=player.script_session().call(L"Fault");const auto history=player.script_diagnostics();require(!fault.passed()&&fault.error.line>0&&history.size()==1&&std::memcmp(&history[0].result.error,&fault.error,sizeof(fault.error))==0,"Independent SDK fault owns exact error and source position");
        LONG score=99;require(!player.script_session().get_number(L"Missing",score).passed()&&score==99&&player.script_diagnostics().size()==2,"Independent failed variable read preserves caller value");
        auto bad=doc;bad.set_source(L"Sub Broken(\r\n");require(!player.load_script(bad.save_bytes(),L"",nullptr).passed()&&player.script_diagnostics().size()==3,"Independent rejected initialization records diagnostic");require(player.script_session().get_number(L"Score",score).passed()&&score==1,"Independent rejected initialization preserves old session effect");
        const auto ordered=player.script_diagnostics();require(ordered[0].sequence<ordered[1].sequence&&ordered[1].sequence<ordered[2].sequence&&!player.script_diagnostic_overflow(),"Independent diagnostics retain order across replacement failure");
        require(doc.save_bytes()==source&&read_file(prefix.wstring()+L".spp")==source,"Sender matrix and faults preserve document and saved source");player.shutdown();
    }
}
void script_message_tests(const std::filesystem::path& dir){
    struct Payload {producer::runtime::Message header{};wchar_t text[8]{};};
    LyricStampGraph stamp;Payload payload;payload.header.size=sizeof(payload);payload.header.type=14;payload.header.graph=&stamp;payload.header.pchannel=0xffffffff;std::copy_n(L"\u6b4c\xd83c\xdfb5",4,payload.text);
    auto* tool=new LyricObserver(14,4,true);DWORD media=0;DWORD* mediaPtr=&media;require(tool->GetMediaTypes(&mediaPtr,1)==S_OK&&media==14,"Script Trace listener registers frozen SDK type14");const auto before=payload;
    require(tool->ProcessPMsg(nullptr,&payload.header)==DMUS_S_REQUEUE&&std::memcmp(&payload,&before,sizeof(payload))==0&&stamp.stamps==1,"Script Trace raw Unicode forwards graph unchanged");
    require(tool->snapshot().size()==1&&tool->snapshot()[0].text==L"\u6b4c\xd83c\xdfb5"&&tool->snapshot()[0].visible,"Script Trace owns Unicode broadcast value");tool->set_visible(false);require(tool->ProcessPMsg(nullptr,&payload.header)==DMUS_S_REQUEUE&&!tool->snapshot().back().visible,"Playback without PChannel1 suppresses Trace display while forwarding");tool->Release();
    ScriptDocument script;script.set_properties(L"Script Messages",L"VBScript",false,false);script.set_source(L"Dim Score\r\nScore = 0\r\nSub TraceIt()\r\nTrace \"Manual \u65e5\u672c \u03a9 \xd83c\xdfb5\"\r\nScore = Score + 1\r\nEnd Sub\r\nSub Fault()\r\nScore = 1 / 0\r\nEnd Sub\r\n");const auto source=script.save_bytes();write_file_atomic((dir/L"Manual.spp").wstring(),source);
    Conductor manual;manual.enable_script_message_observation();require(manual.load_script(source,L"",nullptr).passed(),"Manual Script with Trace initializes on declared OS runtime");
    require(manual.script_session().call(L"TraceIt").passed(),"Actual manual Trace routine succeeds");script_track_wait(400);const auto traced=manual.observed_script_messages();if(!traced.empty()){const auto& m=traced[0];write_file_atomic((dir/L"script-trace-payload.bin").wstring(),Bytes(m.payloadPrefix.begin(),m.payloadPrefix.end()));std::cerr<<"Trace payload bytes="<<m.payloadBytes<<" flags="<<m.flags<<"\n";}for(const auto& m:traced)std::cerr<<"script trace channel="<<m.channel<<" group="<<m.group<<" chars="<<m.text.size()<<" visible="<<m.visible<<"\n";
    require(traced.size()==1&&traced[0].text==L"Manual \u65e5\u672c \u03a9 \xd83c\xdfb5"&&traced[0].visible&&!manual.script_message_observation_failed(),"OS Performance.Trace delivers exact Unicode to source type14 Tool");
    const auto fault=manual.script_session().call(L"Fault");std::cerr<<"manual fault line="<<fault.error.line<<" char="<<fault.error.character<<" hr="<<fault.result<<"\n";const auto diagnostics=manual.script_diagnostics();
    require(!fault.passed()&&fault.error.line>0&&diagnostics.size()==1&&diagnostics[0].name==L"Fault"&&std::memcmp(&diagnostics[0].result.error,&fault.error,sizeof(fault.error))==0,"Manual routine error copies SDK description line and character without reinterpretation");
    Bytes error(sizeof(fault.error));std::memcpy(error.data(),&fault.error,error.size());write_file_atomic((dir/L"manual-error-info.bin").wstring(),error);
    LONG value=99;require(!manual.script_session().get_number(L"Missing",value).passed()&&value==99&&manual.script_diagnostics().size()==2,"Manual failed variable read retains value and records one diagnostic");
    auto bad=script;bad.set_source(L"Sub Broken(\r\n");require(!manual.load_script(bad.save_bytes(),L"",nullptr).passed()&&manual.script_diagnostics().size()==3,"Failed new Script initialization reports diagnostics and preserves previous session");
    require(manual.script_session().get_number(L"Score",value).passed()&&value==1,"Previous manual Script effect survives rejected replacement");const auto ds=manual.script_diagnostics();require(ds[0].sequence<ds[1].sequence&&ds[1].sequence<ds[2].sequence&&!manual.script_diagnostic_overflow(),"Diagnostic history keeps operation order across failed replacement");
    write_file_atomic((dir/L"Manual.spp").wstring(),source);ScriptDocument restored;restored.load(read_file((dir/L"Manual.spp").wstring()));require(manual.load_script(restored.save_bytes(),L"",nullptr).passed()&&manual.script_session().get_number(L"Score",value).passed()&&value==0&&manual.script_diagnostics().size()==3,"Saved source reload resets runtime and preserves error history");require(script.save_bytes()==source&&read_file((dir/L"Manual.spp").wstring())==source,"Trace and faults never mutate manual document or saved source");manual.shutdown();
    const auto folder=dir/L"ScriptMessages";std::filesystem::create_directories(folder);Framework host;host.new_segment();host.document(0).load(SegmentDocument::playback_test().save_bytes());require(host.document(0).add_lyric({2304,2304,16,L"Lyric alongside Trace"}),"Concurrent Lyric fixture authored");host.save_segment(0,(folder/L"Parent.sgp").wstring());host.new_script();host.script_document(0).load(source);host.save_script(0,(folder/L"Calls.spp").wstring());
    require(host.assign_script_call(0,0,L"TraceIt",0,768,4)&&host.assign_script_call(0,0,L"Fault",768,1536,4),"Owned ScriptTrack Trace and error events authored");host.save_segment(0,(folder/L"Parent.sgp").wstring());host.save_project((folder/L"ScriptMessages.pro").wstring());Framework reopened;reopened.open_project((folder/L"ScriptMessages.pro").wstring());const auto parent=reopened.document(0).save_bytes(),callsSource=reopened.script_document(0).save_bytes();const auto graph=reopened.trigger_playback(0);
    Conductor player;player.enable_script_message_observation();player.enable_lyric_observation();player.enable_note_observation();auto play=[&]{player.play(parent,folder.wstring(),nullptr,{},{},{},{},graph);const auto id=player.current_playback_id();script_track_wait(4500);player.stop();return id;};const auto first=play();
    const auto calls=player.track_script_calls(first);const auto messages=player.observed_script_messages();require(calls.size()==2&&calls[0].messageVisible&&calls[1].messageVisible&&calls[0].result.passed()&&!calls[1].result.passed()&&calls[1].result.error.line>0,"Actual scheduled ScriptTrack invokes Trace and retains SDK fault line");require(messages.size()==1&&messages[0].text==traced[0].text&&messages[0].visible,"Scheduled Performance.Trace reaches shared observer exactly once");
    require(player.observed_lyrics().size()==1&&player.observed_lyrics()[0].text==L"Lyric alongside Trace","Distinct SDK13/14 Tools both receive their actual runtime messages");
    const auto second=play();require(second!=first&&player.track_script_calls(second).size()==2&&player.observed_script_messages().size()==2&&player.observed_script_messages().back().text==traced[0].text,"Replay sends new Trace and errors with distinct playback identity");
    script_track_wait(400);require(player.observed_script_messages().size()==2,"Stopped ScriptTrack emits no delayed extra Trace");require(player.observed_notes().size()==16&&!player.note_observation_forwarding_failed()&&!player.script_message_observation_failed()&&!player.track_script_observation_overflow(),"Trace/Lyric observation leaves both saved Sequence replays intact");
    require(reopened.document(0).save_bytes()==parent&&reopened.script_document(0).save_bytes()==callsSource&&read_file((folder/L"Calls.spp").wstring())==callsSource,"Scheduled Trace/errors preserve Project-owned saved documents");player.shutdown();
    AudioPathDocument disconnected;require(disconnected.set_port_range(0,16,16),"AudioPath excludes local Message Window PChannel1");Conductor hidden;hidden.enable_script_message_observation();hidden.set_default_audio_path(disconnected.save_bytes());hidden.play(parent,folder.wstring(),nullptr,{},{},{},{},graph);require(!hidden.performance_channel(0),"Public AudioPath confirms Message Window channel missing");script_track_wait(4500);hidden.stop();const auto hiddenCalls=hidden.track_script_calls();const auto hiddenMessages=hidden.observed_script_messages();require(hiddenCalls.size()==2&&std::all_of(hiddenCalls.begin(),hiddenCalls.end(),[](const auto& c){return !c.messageVisible;}),"Unmapped playback retains routine diagnostics with display suppressed");require(hiddenMessages.size()==1&&!hiddenMessages[0].visible,"Actual unmapped Script Trace forwards but is hidden");hidden.shutdown();
}
