void script_track_wait(unsigned milliseconds){const auto until=GetTickCount64()+milliseconds;do{MSG message{};while(PeekMessageW(&message,nullptr,0,0,PM_REMOVE)){if(message.message==WM_QUIT)throw std::runtime_error("Script Track test unexpected quit");TranslateMessage(&message);DispatchMessageW(&message);}Sleep(2);}while(GetTickCount64()<until);}
void script_track_document_tests(const std::filesystem::path& dir){
    SegmentDocument doc;const auto empty=doc.save_bytes();ScriptEvent e;e.logical=768;e.physical=1536;e.filename=L"Calls.spp";e.routine=L"Bump";
    require(doc.add_script_call(e)&&doc.script_calls().size()==1,"Script Track typed routine and independent clocks");const auto one=doc.save_bytes();
    const auto root=Chunk::parse(one);const auto& t=root.find("LIST","trkl")->children.back();const auto& item=t.find("LIST","scrt")->find("LIST","scrl")->children[0];const auto h=item.find("scrh");
    require(h->data.size()==12&&read32(h->data,0)==1&&read32(h->data,4)==768&&read32(h->data,8)==1536,"SDK 12-byte flags logical physical header");
    require(read32(t.find("trkh")->data,16)==1&&read32(t.find("trkh")->data,20)==1&&decode_utf16(item.find("scrn")->data)==L"Bump","track position groups and WCHAR routine");
    require(doc.undo()&&doc.save_bytes()==empty&&doc.redo()&&doc.save_bytes()==one,"whole document add history");
    for(auto timing:{2u,4u}){e.timing=timing;require(doc.edit_script_call(0,e)&&doc.script_calls()[0].timing==timing,"QUEUE and ATTIME authoring");}
    const auto stable=doc.save_bytes();for(auto timing:{0u,3u,8u,0xffffffffu}){auto bad=e;bad.timing=timing;require(!doc.edit_script_call(0,bad)&&doc.save_bytes()==stable,"invalid timing retains document");}
    auto bad=e;bad.logical=-1;require(!doc.add_script_call(bad)&&doc.save_bytes()==stable,"negative authored logical clock rejected");bad=e;bad.physical=doc.length()+1;require(!doc.add_script_call(bad)&&doc.save_bytes()==stable,"out of range physical rejected");bad=e;bad.routine.clear();require(!doc.edit_script_call(0,bad)&&doc.save_bytes()==stable,"empty routine rejected");bad=e;bad.hasId=true;require(!doc.edit_script_call(0,bad)&&doc.save_bytes()==stable,"zero GUID rejected");
    require(!doc.add_script_call(e,2)&&doc.save_bytes()==stable,"track index hole rejected");
    require(doc.delete_script_call(0)&&doc.script_calls().empty()&&doc.undo()&&doc.save_bytes()==stable&&doc.redo()&&doc.script_calls().empty(),"delete whole document history");
    auto future=Chunk::parse(one);auto& fi=future.find("LIST","trkl")->children.back().find("LIST","scrt")->find("LIST","scrl")->children[0];fi.find("scrh")->data.push_back(0x77);Chunk unknown;unknown.id="zzzz";unknown.data={1,2,3};unknown.padding=0xab;fi.children.push_back(unknown);
    SegmentDocument retained;retained.load(future.encode());auto change=retained.script_calls()[0];change.physical=1537;require(retained.edit_script_call(0,change),"future fields editable");auto expected=future;put32(expected.find("LIST","trkl")->children.back().find("LIST","scrt")->find("LIST","scrl")->children[0].find("scrh")->data,8,1537);require(retained.save_bytes()==expected.encode(),"only physical DWORD changes unknown padding tails retained");
    auto broken=future;broken.find("LIST","trkl")->children.back().find("LIST","scrt")->find("LIST","scrl")->children[0].find("scrh")->data.resize(11);rejected([&]{retained.load(broken.encode());},"truncated Script header rejected");require(retained.save_bytes()==expected.encode(),"failed load retains prior document");
    auto pickup=future;put32(pickup.find("LIST","trkl")->children.back().find("LIST","scrt")->find("LIST","scrl")->children[0].find("scrh")->data,4,0xffffffff);retained.load(pickup.encode());require(retained.script_calls()[0].logical==-1&&retained.save_bytes()==pickup.encode(),"signed imported pickup preserved");
    doc.select_track_group(2);require(doc.add_script_call(e)&&doc.script_calls().size()==1,"second group authored");doc.select_track_group(1);require(doc.script_calls().empty(),"groups remain independent");
}
void script_track_owned_tests(const std::filesystem::path& dir,bool runtime){
    const auto folder=dir/L"ScriptTrack";std::filesystem::create_directories(folder);Framework host;host.new_segment();host.save_segment(0,(folder/L"Parent.sgp").wstring());host.new_script();auto& script=host.script_document(0);
    script.set_properties(L"Calls",L"VBScript",false,false);script.set_source(L"Dim Score\r\nScore = 0\r\nSub Bump()\r\nScore = Score + 1\r\nEnd Sub\r\n");host.save_script(0,(folder/L"Calls.spp").wstring());const auto disk=script.save_bytes();
    require(host.assign_script_call(0,0,L"Bump",768,3072,4),"owned Script routine assigned");auto graph=host.trigger_playback(0);require(graph.scripts.size()==1&&graph.scripts[0].routines==std::vector<std::wstring>{L"Bump"},"one owned snapshot and required routine");
    script.set_source(L"Dim Score\r\nScore = 10\r\nSub Bump()\r\nScore = Score + 1\r\nEnd Sub\r\nSub Fault()\r\nScore = 1 / 0\r\nEnd Sub\r\n");graph=host.trigger_playback(0);require(graph.scripts[0].bytes==script.save_bytes()&&graph.scripts[0].bytes!=disk&&read_file((folder/L"Calls.spp").wstring())==disk,"unsaved Script snapshot owns runtime source without disk mutation");
    require(host.document(0).save_bytes()==graph.source&&graph.parent!=graph.source,"private GUID reference rewrite leaves source unchanged");
    auto invalid=host.document(0).script_calls()[0];invalid.filename=L"Other.spp";require(host.document(0).edit_script_call(0,invalid),"mismatched filename fixture");rejected([&]{host.trigger_playback(0);},"GUID filename disagreement rejected");require(host.undo_segment(0),"restore owned reference");
    if(runtime){
        for(const auto timing:{1u,2u,4u}){
            require(host.assign_script_call(0,0,L"Bump",768,3072,timing,0),"dispatch timing fixture");graph=host.trigger_playback(0);Conductor player;player.play(host.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{},{},{},{},graph);
            const auto id=player.current_playback_id();LONG value=-1;require(player.track_script_number(id,graph.scripts[0].objectId,L"Score",value).passed()&&value==10,"Track Script initialized unsaved source");
            LONG changedAt=-1;const auto start=player.playback_request().actualStart;for(unsigned i=0;i<1100;++i){script_track_wait(5);if(!player.track_script_number(id,graph.scripts[0].objectId,L"Score",value).passed())throw std::runtime_error("Track Script variable query failed");if(value==11){changedAt=player.position().clocks-start;break;}}
            std::ostringstream evidence;evidence<<"{\"timing\":"<<timing<<",\"changedAtClock\":"<<changedAt<<",\"physicalClock\":3072,\"value\":"<<value<<"}";const auto json=evidence.str();write_file_atomic((dir/(L"script-timing-"+std::to_wstring(timing)+L".json")).wstring(),Bytes(json.begin(),json.end()));
            std::ostringstream calls;calls<<"[";bool comma=false;for(const auto& call:player.calls()){if(comma)calls<<",";comma=true;calls<<"{\"operation\":\""<<call.operation<<"\",\"hr\":"<<call.result<<"}";}calls<<"]";const auto callJson=calls.str();write_file_atomic((dir/(L"script-calls-"+std::to_wstring(timing)+L".json")).wstring(),Bytes(callJson.begin(),callJson.end()));
            require(value==11&&changedAt>=0,"actual source Script Track routine effect");const auto delivered=player.track_script_calls(id);require(delivered.size()==1&&delivered[0].objectId==graph.scripts[0].objectId&&delivered[0].routine==L"Bump"&&delivered[0].timing==timing&&delivered[0].physical==3072&&delivered[0].logical==768&&delivered[0].result.passed(),"actual PMSG dispatch invokes exactly the owned routine");require(delivered[0].invokeClock>=delivered[0].dispatchClock&&delivered[0].invokeClock-delivered[0].dispatchClock<=160&&!player.track_script_observation_overflow(),"UI-thread invocation follows real Performance delivery within bound");
            std::ostringstream trace;trace<<"{\"timing\":"<<timing<<",\"start\":"<<delivered[0].start<<",\"dispatchClock\":"<<delivered[0].dispatchClock<<",\"invokeClock\":"<<delivered[0].invokeClock<<",\"physical\":"<<delivered[0].physical<<"}";const auto traceJson=trace.str();write_file_atomic((dir/(L"script-delivery-"+std::to_wstring(timing)+L".json")).wstring(),Bytes(traceJson.begin(),traceJson.end()));if(timing==1)require(changedAt<2500,"PREPARE calls before physical timestamp");else if(timing==4)require(changedAt>=3000&&changedAt<3400,"ATTIME dispatch at physical timestamp");else require(changedAt<3400,"QUEUE dispatch by physical timestamp");player.stop();player.shutdown();
        }
        const auto stopFixtureBefore=host.document(0).save_bytes();require(host.document(0).script_calls()[0].timing==4,"Stop fixture retains ATTIME");require(!host.assign_script_call(0,0,L"Bump",768,3072,4,0)&&host.document(0).save_bytes()==stopFixtureBefore,"identical Stop fixture assignment is a document-preserving no-op");graph=host.trigger_playback(0);Conductor player;player.play(host.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{},{},{},{},graph);const auto stoppedId=player.current_playback_id();script_track_wait(300);require(player.track_script_calls(stoppedId).empty(),"future ATTIME routine not invoked before Stop");player.stop();script_track_wait(3300);require(!player.position().playing&&player.track_script_calls(stoppedId).empty(),"Stop cancels routine beyond its original scheduled time");player.play(host.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{},{},{},{},graph);LONG value=-1;require(player.track_script_number(player.current_playback_id(),graph.scripts[0].objectId,L"Score",value).passed()&&value==10,"Replay initializes fresh Script state");script_track_wait(3300);require(player.track_script_number(player.current_playback_id(),graph.scripts[0].objectId,L"Score",value).passed()&&value==11,"Replay dispatches owned routine");player.stop();player.shutdown();
        require(host.assign_script_call(0,0,L"Fault",768,1536,4,0),"fault routine authored");const auto faultGraph=host.trigger_playback(0);const auto unchangedParent=host.document(0).save_bytes(),unchangedScript=script.save_bytes();Conductor faultPlayer;faultPlayer.play(unchangedParent,folder.wstring(),GetDesktopWindow(),{},{},{},{},faultGraph);script_track_wait(2300);const auto faultCalls=faultPlayer.track_script_calls();require(faultCalls.size()==1&&!faultCalls[0].result.passed()&&FAILED(faultCalls[0].result.error.result)&&faultCalls[0].result.error.description[0],"scheduled routine errors preserve SDK error details");require(host.document(0).save_bytes()==unchangedParent&&script.save_bytes()==unchangedScript,"runtime fault does not mutate owned documents");faultPlayer.stop();faultPlayer.shutdown();require(host.undo_segment(0),"restore Bump after fault fixture");
        require(host.assign_script_call(0,0,L"MissingRoutine",768,3072,4,0),"missing routine fixture");const auto missing=host.trigger_playback(0);Conductor missingPlayer;rejected([&]{missingPlayer.play(host.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{},{},{},{},missing);},"required routine absent refused before playback");require(!missingPlayer.position().playing,"missing routine emits no playable partial graph");missingPlayer.shutdown();require(host.undo_segment(0),"restore final native fixture routine");
    }
    host.save_segment(0,(folder/L"Parent.sgp").wstring());host.save_script(0,(folder/L"Calls.spp").wstring());host.save_project((folder/L"ScriptTrack.pro").wstring());Framework reload;reload.open_project((folder/L"ScriptTrack.pro").wstring());require(reload.document(0).script_calls().size()==1&&reload.trigger_playback(0).scripts[0].bytes==script.save_bytes(),"native Project reload owns Script and routine");
}
