void script_runtime_tests(const std::filesystem::path& dir){
    ScriptDocument doc;doc.set_properties(L"Runtime 日本",L"VBScript",true,false);doc.set_source(L"Dim Score\r\nScore = 7\r\nSub Bump()\r\nScore = Score + 5\r\nEnd Sub\r\nSub Fault()\r\nScore = 1 / 0\r\nEnd Sub\r\nSub LoadContent()\r\nContent.Load\r\nEnd Sub\r\n");
    const auto bytes=doc.save_bytes();Conductor conductor;auto loaded=conductor.load_script(bytes,L"",nullptr);require(loaded.passed(),"Source Script initialized by declared OS runtime");
    auto& session=conductor.script_session();auto routines=session.routines(),variables=session.variables();require(std::find(routines.begin(),routines.end(),L"Bump")!=routines.end()&&std::find(routines.begin(),routines.end(),L"Fault")!=routines.end(),"Script routine enumeration");
    require(std::find(variables.begin(),variables.end(),L"Score")!=variables.end(),"Script variable enumeration");LONG value=-1;require(session.get_number(L"Score",value).passed()&&value==7,"Script initial source execution");
    require(session.set_number(L"Score",37).passed()&&session.call(L"Bump").passed()&&session.get_number(L"Score",value).passed()&&value==42,"Script variable write and routine effect");
    auto fault=session.call(L"Fault");require(!fault.passed()&&FAILED(fault.error.result)&&fault.error.description[0],"Script runtime error details retained");
    value=123;require(!session.get_number(L"MissingVariable",value).passed()&&value==123,"Failed Script variable read keeps caller value");
    rejected([&]{session.call(std::wstring(L"Bump\0other",10));},"NUL routine name rejected");
    auto invalid=doc;invalid.set_source(L"Sub Broken(\r\n");auto failed=conductor.load_script(invalid.save_bytes(),L"",nullptr);require(!failed.passed(),"Script syntax failure rejected");
    require(conductor.script_session().get_number(L"Score",value).passed()&&value==42,"Failed Script initialization retains previous session");
    auto unsupported=doc;unsupported.set_properties(unsupported.name(),L"UndeclaredEngine",false,false);rejected([&]{conductor.load_script(unsupported.save_bytes(),L"",nullptr);},"Undeclared language rejected before COM activation");require(conductor.script_session().get_number(L"Score",value).passed()&&value==42,"Rejected engine preserves Script session");
    auto malformed=bytes;malformed.resize(11);rejected([&]{conductor.load_script(malformed,L"",nullptr);},"Malformed Script rejected before runtime replacement");
    require(doc.save_bytes()==bytes,"Execution does not mutate source document");
    write_file_atomic((dir/L"Runtime.spp").wstring(),bytes);ScriptDocument reload;reload.load(read_file((dir/L"Runtime.spp").wstring()));require(conductor.load_script(reload.save_bytes(),L"",nullptr).passed()&&conductor.script_session().get_number(L"Score",value).passed()&&value==7,"Saved Script reload resets execution state from source");
    auto contained=Chunk::parse(bytes);auto segment=SegmentDocument::playback_test(60);auto segmentRoot=Chunk::parse(segment.save_bytes());
    Chunk entry;entry.id="LIST";entry.type="cobl";Chunk h;h.id="cobh";h.data.resize(28);std::memcpy(h.data.data(),&producer::runtime::segmentClass,16);std::copy_n("RIFF",4,h.data.begin()+20);std::copy_n("DMSG",4,h.data.begin()+24);entry.children.push_back(h);Chunk alias;alias.id="coba";alias.data=utf16(L"Content");entry.children.push_back(alias);entry.children.push_back(segmentRoot);contained.find("RIFF","DMCN")->find("LIST","cosl")->children.push_back(entry);
    auto checkAlias=[&]{void* object=nullptr;auto aliasResult=conductor.script_session().get_object(L"Content",producer::runtime::segment8Id,object);std::wcerr<<L"alias result=0x"<<std::hex<<static_cast<unsigned long>(aliasResult.result)<<L" error=0x"<<static_cast<unsigned long>(aliasResult.error.result)<<L" description="<<aliasResult.error.description<<L" pointer="<<object<<std::dec<<L"\n";require(aliasResult.passed()&&object,"Container alias exposes owned Segment interface");auto loadedSegment=static_cast<producer::runtime::Segment*>(object);LONG length=-1;const auto hr=loadedSegment->GetLength(&length);loadedSegment->Release();require(SUCCEEDED(hr)&&length==segment.length(),"Container Segment length matches source snapshot");};
    require(conductor.load_script(contained.encode(),L"",nullptr).passed(),"Embedded source Segment Container Script initialized");checkAlias();auto lazy=contained;put32(lazy.find("schd")->data,0,0);require(conductor.load_script(lazy.encode(),L"",nullptr).passed(),"Lazy Container source Script initialized without LOAD_ALL");auto lazyLoad=conductor.script_session().call(L"LoadContent");std::wcerr<<L"lazy LoadContent result=0x"<<std::hex<<static_cast<unsigned long>(lazyLoad.result)<<L" description="<<lazyLoad.error.description<<std::dec<<L"\n";require(lazyLoad.passed(),"Explicit script Content.Load realizes lazy alias");checkAlias();
    void* unchanged=reinterpret_cast<void*>(1);require(!conductor.script_session().get_object(L"MissingObject",IID_IUnknown,unchanged).passed()&&unchanged==reinterpret_cast<void*>(1),"Failed object Get keeps caller output");
    write_file_atomic((dir/L"Content.sgp").wstring(),segment.save_bytes());auto referenced=contained;auto& refEntry=referenced.find("RIFF","DMCN")->find("LIST","cosl")->children.back();refEntry.children.pop_back();auto refHeader=refEntry.find("cobh");std::copy_n("LIST",4,refHeader->data.begin()+20);std::copy_n("DMRF",4,refHeader->data.begin()+24);Chunk ref;ref.id="LIST";ref.type="DMRF";Chunk rh;rh.id="refh";rh.data.resize(20);std::memcpy(rh.data.data(),&producer::runtime::segmentClass,16);put32(rh.data,16,2|16);ref.children.push_back(rh);Chunk file;file.id="file";file.data=utf16(L"Content.sgp");ref.children.push_back(file);refEntry.children.push_back(ref);const auto referenceBytes=referenced.encode();
    require(conductor.load_script(referenceBytes,dir.wstring(),nullptr).passed(),"Referenced Segment materialized from source before Init");checkAlias();auto deferred=referenced;put32(deferred.find("RIFF","DMCN")->find("conh")->data,0,2);put32(deferred.find("RIFF","DMCN")->find("LIST","cosl")->children.back().find("cobh")->data,16,1);require(conductor.load_script(deferred.encode(),dir.wstring(),nullptr).passed(),"NOLOADS KEEP Container initialized with session-owned Loader cache");checkAlias();void* retainedAlias=nullptr;require(conductor.script_session().get_object(L"Content",producer::runtime::segment8Id,retainedAlias).passed()&&retainedAlias,"Caller retains explicit alias interface");require(conductor.load_script(bytes,L"",nullptr).passed(),"Replace contained Script with empty source session");LONG retainedLength=-1;auto retainedSegment=static_cast<producer::runtime::Segment*>(retainedAlias);auto retainedHr=retainedSegment->GetLength(&retainedLength);retainedSegment->Release();require(SUCCEEDED(retainedHr)&&retainedLength==segment.length(),"Caller interface survives prior Script and Loader release");require(conductor.load_script(referenceBytes,dir.wstring(),nullptr).passed(),"Referenced Container reinitialized after replacement");checkAlias();require(referenced.encode()==referenceBytes,"Runtime materialization leaves saved DMRF unchanged");
    write_file_atomic((dir/L"ContainerRuntime.spp").wstring(),referenceBytes);
    auto missing=referenced;missing.find("RIFF","DMCN")->find("LIST","cosl")->children.back().find("LIST","DMRF")->find("file")->data=utf16(L"Missing.sgp");rejected([&]{conductor.load_script(missing.encode(),dir.wstring(),nullptr);},"Missing Container source rejected before session replacement");checkAlias();
    auto unknown=contained;unknown.find("RIFF","DMCN")->find("LIST","cosl")->children.back().find("cobh")->data[0]^=1;rejected([&]{conductor.load_script(unknown.encode(),L"",nullptr);},"Undeclared contained class rejected before activation");checkAlias();
    for(const auto& server:conductor.servers())std::wcerr<<L"script runtime server="<<server<<L"\n";conductor.shutdown();
}
