void script_constants_and_secondary_tests(const std::filesystem::path& dir,const Bytes& playableBytes,const Chunk& entry,Conductor& conductor){
    ScriptDocument coexistence;coexistence.load(playableBytes);
    coexistence.set_source(*coexistence.source()+L"\r\nDim SecondaryFlags, BeatFlags, IntroFlags, CutoffFlags, ImmediateFlags, PrimaryPlaying, PrimaryActive, SecondaryActive\r\nSecondaryFlags = IsSecondary\r\nBeatFlags = AtBeat\r\nIntroFlags = PlayIntro\r\nCutoffFlags = NoCutoff\r\nImmediateFlags = AtImmediate\r\nSub PlayPrimary()\r\nSet PrimaryPlaying = Background.Play()\r\nEnd Sub\r\nSub CheckPrimary()\r\nPrimaryActive = PrimaryPlaying.IsPlaying\r\nEnd Sub\r\nSub CheckSecondary()\r\nSecondaryActive = LastPlaying.IsPlaying\r\nEnd Sub\r\nSub StopPrimary()\r\nPrimaryPlaying.Stop AtImmediate\r\nEnd Sub\r\nSub StopSecondaryInstance()\r\nLastPlaying.Stop AtImmediate\r\nEnd Sub\r\n");
    auto tree=Chunk::parse(coexistence.save_bytes()),background=entry; background.find("coba")->data=utf16(L"Background");
    auto& backgroundSegment=background.children.back();backgroundSegment.find("guid")->data[0]^=0x40;put32(backgroundSegment.find("segh")->data,0,0xffffffff);
    tree.find("RIFF","DMCN")->find("LIST","cosl")->children.push_back(background);const auto bytes=tree.encode();
    require(conductor.load_script(bytes,L"",nullptr).passed(),"Primary/secondary source Script initializes unchanged named constants");auto& session=conductor.script_session();LONG number=0;
    for(const auto name:{L"SecondaryFlags",L"BeatFlags",L"IntroFlags",L"CutoffFlags"}){const auto result=session.get_number(name,number);std::wcerr<<L"source constant "<<name<<L"="<<number<<L"\n";require(result.passed()&&number!=0,"Documented nonzero playback flag is a numeric constant, not implicit Empty");}
    // Independently observed from the direct OS Script API, not DMUS_SEGF_*.
    require(session.get_number(L"ImmediateFlags",number).passed()&&number==128,"Immediate playback constant preserves the actual OS scripting value");
    auto waitState=[&](const wchar_t* routine,const wchar_t* variable,bool active){const auto deadline=GetTickCount64()+5000;do{const auto call=session.call(routine);LONG value=0;const auto read=session.get_number(variable,value);if(!call.passed()||!read.passed())return false;if((value!=0)==active)return true;Sleep(20);}while(GetTickCount64()<deadline);return false;};
    require(session.call(L"PlayPrimary").passed()&&waitState(L"CheckPrimary",L"PrimaryActive",true),"Infinite primary instance actually starts before secondary request");
    require(session.call(L"PlayContent").passed()&&waitState(L"CheckSecondary",L"SecondaryActive",true),"Named IsSecondary request starts an actual secondary instance");
    require(session.call(L"CheckPrimary").passed()&&session.get_number(L"PrimaryActive",number).passed()&&number!=0,"Primary remains playing after secondary has actually started");
    require(session.call(L"StopSecondaryInstance").passed()&&waitState(L"CheckSecondary",L"SecondaryActive",false),"Authored immediate Stop ends the secondary instance");
    require(session.call(L"CheckPrimary").passed()&&session.get_number(L"PrimaryActive",number).passed()&&number!=0,"Stopping secondary preserves the independently playing primary");
    require(session.call(L"StopPrimary").passed()&&waitState(L"CheckPrimary",L"PrimaryActive",false),"Primary stops through the same owning Script context");
    require(tree.encode()==bytes,"OS constant namespace and coexistence leave native source bytes unchanged");write_file_atomic((dir/L"PrimarySecondary.spp").wstring(),bytes);
    ScriptDocument javascript;javascript.set_properties(L"Named constants",L"JScript",false,false);javascript.set_source(L"var SecondaryFlags = IsSecondary; var BeatFlags = AtBeat; var IntroFlags = PlayIntro; var CutoffFlags = NoCutoff;\r\n");
    require(conductor.load_script(javascript.save_bytes(),L"",nullptr).passed(),"Declared JScript engine imports the same OS playback constants");
    for(const auto name:{L"SecondaryFlags",L"BeatFlags",L"IntroFlags",L"CutoffFlags"})require(conductor.script_session().get_number(name,number).passed()&&number!=0,"JScript playback constants do not become undefined values");
    auto unknown=javascript;unknown.set_source(L"var Value = UndocumentedPlaybackFlag;\r\n");const auto initializationFault=conductor.load_script(unknown.save_bytes(),L"",nullptr);
    require(!initializationFault.passed()&&FAILED(initializationFault.error.result)&&initializationFault.error.description[0],"Unknown JScript names retain actual ReferenceError during global initialization");
    require(conductor.script_session().get_number(L"SecondaryFlags",number).passed()&&number==1,"Aborted JScript initialization preserves the previous valid session");
    ScriptDocument shadow;shadow.set_source(L"Const IsSecondary = 77\r\nDim AuthoredValue\r\nAuthoredValue = IsSecondary\r\n");const auto duplicate=conductor.load_script(shadow.save_bytes(),L"",nullptr);
    // The declared VBScript engine reports Name redefined for a host global.
    require(!duplicate.passed()&&duplicate.error.result==static_cast<HRESULT>(0x800a0411u),"Duplicate library constant definition retains the actual VBScript Name redefined error");
    require(conductor.script_session().get_number(L"SecondaryFlags",number).passed()&&number==1,"Duplicate constant failure preserves the previous valid namespace");
    ScriptDocument authored;authored.set_source(L"Const AuthoredBase = 77\r\nDim AuthoredValue\r\nAuthoredValue = AuthoredBase\r\n");
    require(conductor.load_script(authored.save_bytes(),L"",nullptr).passed()&&conductor.script_session().get_number(L"AuthoredValue",number).passed()&&number==77,"Independent authored VBScript constants remain available unchanged");
}
void script_runtime_tests(const std::filesystem::path& dir){
    ScriptDocument doc;doc.set_properties(L"Runtime 日本",L"VBScript",true,false);doc.set_source(L"Dim Score\r\nScore = 7\r\nSub Bump()\r\nScore = Score + 5\r\nEnd Sub\r\nSub Fault()\r\nScore = 1 / 0\r\nEnd Sub\r\nSub LoadContent()\r\nContent.Load\r\nEnd Sub\r\n");
    const auto bytes=doc.save_bytes();Conductor conductor;auto loaded=conductor.load_script(bytes,L"",nullptr);require(loaded.passed(),"Source Script initialized by declared OS runtime");
    auto& session=conductor.script_session();auto routines=session.routines(),variables=session.variables();require(std::find(routines.begin(),routines.end(),L"Bump")!=routines.end()&&std::find(routines.begin(),routines.end(),L"Fault")!=routines.end(),"Script routine enumeration");
    require(std::find(variables.begin(),variables.end(),L"Score")!=variables.end(),"Script variable enumeration");LONG value=-1;require(session.get_number(L"Score",value).passed()&&value==7,"Script initial source execution");
    require(session.set_number(L"Score",37).passed()&&session.call(L"Bump").passed()&&session.get_number(L"Score",value).passed()&&value==42,"Script variable write and routine effect");
    auto fault=session.call(L"Fault");require(!fault.passed()&&FAILED(fault.error.result)&&fault.error.description[0],"Script runtime error details retained");
    value=123;require(!session.get_number(L"MissingVariable",value).passed()&&value==123,"Failed Script variable read keeps caller value");
    rejected([&]{session.call(std::wstring(L"Bump\0other",10));},"NUL routine name rejected");
    auto invalid=doc;invalid.set_source(L"Sub Broken(\r\n");auto failed=conductor.load_script(invalid.save_bytes(),L"",nullptr);require(!failed.passed(),"Script syntax failure rejected");
    require(conductor.script_session().get_number(L"Score",value).passed()&&value==42,"Failed Script initialization retains previous session");
    auto unsupported=doc;unsupported.set_properties(unsupported.name(),L"UndeclaredEngine",false,false);rejected([&]{conductor.load_script(unsupported.save_bytes(),L"",nullptr);},"Undeclared language rejected before COM activation");require(conductor.script_session().get_number(L"Score",value).passed()&&value==42,"Rejected engine preserves Script session");
    auto malformed=bytes;malformed.resize(11);rejected([&]{conductor.load_script(malformed,L"",nullptr);},"Malformed Script rejected before runtime replacement");
    require(doc.save_bytes()==bytes,"Execution does not mutate source document");
    write_file_atomic((dir/L"Runtime.spp").wstring(),bytes);ScriptDocument reload;reload.load(read_file((dir/L"Runtime.spp").wstring()));require(conductor.load_script(reload.save_bytes(),L"",nullptr).passed()&&conductor.script_session().get_number(L"Score",value).passed()&&value==7,"Saved Script reload resets execution state from source");
    auto contained=Chunk::parse(bytes);auto segment=SegmentDocument::playback_test(60);auto segmentRoot=Chunk::parse(segment.save_bytes());
    Chunk entry;entry.id="LIST";entry.type="cobl";Chunk h;h.id="cobh";h.data.resize(28);std::memcpy(h.data.data(),&producer::runtime::segmentClass,16);std::copy_n("RIFF",4,h.data.begin()+20);std::copy_n("DMSG",4,h.data.begin()+24);entry.children.push_back(h);Chunk alias;alias.id="coba";alias.data=utf16(L"Content");entry.children.push_back(alias);entry.children.push_back(segmentRoot);contained.find("RIFF","DMCN")->find("LIST","cosl")->children.push_back(entry);
    auto checkAlias=[&]{void* object=nullptr;auto aliasResult=conductor.script_session().get_object(L"Content",producer::runtime::segment8Id,object);std::wcerr<<L"alias result=0x"<<std::hex<<static_cast<unsigned long>(aliasResult.result)<<L" error=0x"<<static_cast<unsigned long>(aliasResult.error.result)<<L" description="<<aliasResult.error.description<<L" pointer="<<object<<std::dec<<L"\n";require(aliasResult.passed()&&object,"Container alias exposes owned Segment interface");auto loadedSegment=static_cast<producer::runtime::Segment*>(object);LONG length=-1;const auto hr=loadedSegment->GetLength(&length);loadedSegment->Release();require(SUCCEEDED(hr)&&length==segment.length(),"Container Segment length matches source snapshot");};
    require(conductor.load_script(contained.encode(),L"",nullptr).passed(),"Embedded source Segment Container Script initialized");checkAlias();auto lazy=contained;put32(lazy.find("schd")->data,0,0);require(conductor.load_script(lazy.encode(),L"",nullptr).passed(),"Lazy Container source Script initialized without LOAD_ALL");auto lazyLoad=conductor.script_session().call(L"LoadContent");std::wcerr<<L"lazy LoadContent result=0x"<<std::hex<<static_cast<unsigned long>(lazyLoad.result)<<L" description="<<lazyLoad.error.description<<std::dec<<L"\n";require(lazyLoad.passed(),"Explicit script Content.Load realizes lazy alias");checkAlias();
    auto playback=doc;playback.set_properties(playback.name(),L"VBScript",true,true);playback.set_source(L"Dim LastPlaying, HasPlaying\r\nSub PlayContent()\r\nSet LastPlaying = Content.Play(IsSecondary)\r\nHasPlaying = IsObject(LastPlaying)\r\nEnd Sub\r\nSub PlayDefault()\r\nSet LastPlaying = Content.Play()\r\nEnd Sub\r\nSub ReplaceInstance()\r\nSet LastPlaying = Content.Play(IsSecondary, , , LastPlaying)\r\nEnd Sub\r\nSub StopContent()\r\nContent.Stop AtImmediate\r\nEnd Sub\r\nSub StopDefault()\r\nContent.Stop\r\nEnd Sub\r\nSub BadPlay()\r\nContent.Play \"invalid flags\"\r\nEnd Sub\r\n");
    auto playable=Chunk::parse(playback.save_bytes());playable.find("RIFF","DMCN")->find("LIST","cosl")->children.push_back(entry);const auto playableBytes=playable.encode();
    require(conductor.load_script(playableBytes,L"",nullptr).passed(),"Source Segment playback Script owns loaded/downloaded content");
    auto playResult=conductor.script_session().call(L"PlayContent");std::wcerr<<L"source Play result=0x"<<std::hex<<static_cast<unsigned long>(playResult.result)<<L" error=0x"<<static_cast<unsigned long>(playResult.error.result)<<L" description="<<playResult.error.description<<std::dec<<L"\n";
    require(playResult.passed()&&conductor.script_session().get_number(L"HasPlaying",value).passed()&&value!=0,"Source alias Play returns actual OS PlayingSegment object");
    require(conductor.script_session().call(L"ReplaceInstance").passed(),"Play preserves omitted AudioPath/transition slots and from-instance object");
    require(conductor.script_session().call(L"StopContent").passed(),"Source alias Stop uses owning Script context with authored immediate flag");
    require(conductor.script_session().call(L"PlayDefault").passed()&&conductor.script_session().call(L"StopDefault").passed(),"Play and Stop preserve absent optional flags");
    auto badPlay=conductor.script_session().call(L"BadPlay");require(!badPlay.passed()&&FAILED(badPlay.error.result)&&badPlay.error.description[0],"Invalid Play retains actual OS error details without successful fallback");
    require(conductor.script_session().call(L"PlayContent").passed()&&conductor.script_session().call(L"StopContent").passed(),"Failed Play releases bridge arguments and leaves subsequent playback available");
    require(playable.encode()==playableBytes,"Context bridging preserves exact native Script/Container/Segment source");
    require(conductor.load_script(lazy.encode(),L"",nullptr).passed()&&conductor.script_session().call(L"LoadContent").passed(),"Explicit lazy Load still succeeds after playback context replacement");
    void* unchanged=reinterpret_cast<void*>(1);require(!conductor.script_session().get_object(L"MissingObject",IID_IUnknown,unchanged).passed()&&unchanged==reinterpret_cast<void*>(1),"Failed object Get keeps caller output");
    write_file_atomic((dir/L"Content.sgp").wstring(),segment.save_bytes());auto referenced=contained;auto& refEntry=referenced.find("RIFF","DMCN")->find("LIST","cosl")->children.back();refEntry.children.pop_back();auto refHeader=refEntry.find("cobh");std::copy_n("LIST",4,refHeader->data.begin()+20);std::copy_n("DMRF",4,refHeader->data.begin()+24);Chunk ref;ref.id="LIST";ref.type="DMRF";Chunk rh;rh.id="refh";rh.data.resize(20);std::memcpy(rh.data.data(),&producer::runtime::segmentClass,16);put32(rh.data,16,2|16);ref.children.push_back(rh);Chunk file;file.id="file";file.data=utf16(L"Content.sgp");ref.children.push_back(file);refEntry.children.push_back(ref);const auto referenceBytes=referenced.encode();
    require(conductor.load_script(referenceBytes,dir.wstring(),nullptr).passed(),"Referenced Segment materialized from source before Init");checkAlias();auto deferred=referenced;put32(deferred.find("RIFF","DMCN")->find("conh")->data,0,2);put32(deferred.find("RIFF","DMCN")->find("LIST","cosl")->children.back().find("cobh")->data,16,1);require(conductor.load_script(deferred.encode(),dir.wstring(),nullptr).passed(),"NOLOADS KEEP Container initialized with session-owned Loader cache");checkAlias();void* retainedAlias=nullptr;require(conductor.script_session().get_object(L"Content",producer::runtime::segment8Id,retainedAlias).passed()&&retainedAlias,"Caller retains explicit alias interface");require(conductor.load_script(bytes,L"",nullptr).passed(),"Replace contained Script with empty source session");LONG retainedLength=-1;auto retainedSegment=static_cast<producer::runtime::Segment*>(retainedAlias);auto retainedHr=retainedSegment->GetLength(&retainedLength);retainedSegment->Release();require(SUCCEEDED(retainedHr)&&retainedLength==segment.length(),"Caller interface survives prior Script and Loader release");require(conductor.load_script(referenceBytes,dir.wstring(),nullptr).passed(),"Referenced Container reinitialized after replacement");checkAlias();require(referenced.encode()==referenceBytes,"Runtime materialization leaves saved DMRF unchanged");
    write_file_atomic((dir/L"ContainerRuntime.spp").wstring(),referenceBytes);
    auto missing=referenced;missing.find("RIFF","DMCN")->find("LIST","cosl")->children.back().find("LIST","DMRF")->find("file")->data=utf16(L"Missing.sgp");rejected([&]{conductor.load_script(missing.encode(),dir.wstring(),nullptr);},"Missing Container source rejected before session replacement");checkAlias();
    auto unknown=contained;unknown.find("RIFF","DMCN")->find("LIST","cosl")->children.back().find("cobh")->data[0]^=1;rejected([&]{conductor.load_script(unknown.encode(),L"",nullptr);},"Undeclared contained class rejected before activation");checkAlias();
    script_constants_and_secondary_tests(dir,playableBytes,entry,conductor);
    for(const auto& server:conductor.servers())std::wcerr<<L"script runtime server="<<server<<L"\n";conductor.shutdown();
}
