#include <sstream>
void segment_trigger_document_tests(const std::filesystem::path& dir){
    SegmentDocument doc;const auto empty=doc.save_bytes();SegmentTrigger e;e.logical=768;e.physical=769;e.filename=L"Child.sgp";e.name=L"Child";e.playFlags=0x80;
    require(doc.add_trigger(e)&&doc.triggers().size()==1,"Segment Trigger owns precise and logical times");const auto one=doc.save_bytes();
    const auto root=Chunk::parse(one);const auto& t=root.find("LIST","trkl")->children.back();const auto p=t.find("LIST","segt");const auto h=p->find("LIST","lsgl")->children[0].find("sgih");
    require(h->data.size()==16&&read32(h->data,0)==768&&read32(h->data,4)==769&&read32(h->data,8)==0x80&&read32(h->data,12)==0,"SDK 16-byte trigger fields");
    require(read32(t.find("trkh")->data,16)==1&&read32(t.find("trkh")->data,20)==1&&read32(p->find("sgth")->data,0)==0,"unique position and reserved header zero");
    require(doc.undo()&&doc.save_bytes()==empty&&doc.redo()&&doc.save_bytes()==one,"whole document add Undo Redo");
    e.physical=770;e.playFlags=0x80|0x200|0x2000;
    require(doc.edit_trigger(0,e)&&doc.triggers()[0].logical==768&&doc.triggers()[0].physical==770&&doc.triggers()[0].playFlags==0x2280,"independent logical time control secondary boundary");const auto changed=doc.save_bytes();
    require(doc.undo()&&doc.save_bytes()==one,"edit Undo exact");auto bad=e;bad.playFlags=0x200;
    require(!doc.add_trigger(bad)&&!doc.edit_trigger(0,bad),"control primary rejected");
    bad=e;bad.playFlags=0x180;require(!doc.add_trigger(bad),"QUEUE secondary rejected");
    bad=e;bad.playFlags=0x20000;require(!doc.add_trigger(bad),"valid-start boundary requires ALIGN");
    bad=e;bad.playFlags=0x40;require(!doc.add_trigger(bad),"reference-time flag cannot reinterpret MUSIC_TIME");
    bad=e;bad.playFlags=1;require(!doc.add_trigger(bad),"reserved play flags rejected");
    bad=e;bad.itemFlags=2;require(!doc.add_trigger(bad),"reserved author item flags rejected");
    bad=e;bad.logical=-1;require(!doc.add_trigger(bad),"negative author logical position rejected");
    bad=e;bad.physical=doc.length();require(!doc.add_trigger(bad),"physical end boundary rejected");
    bad=e;bad.logical=doc.length();require(!doc.add_trigger(bad),"logical end boundary rejected");
    bad=e;bad.hasId=true;require(!doc.add_trigger(bad),"zero authored identity rejected");
    bad=e;bad.filename=std::wstring(L"bad\0file",8);require(!doc.add_trigger(bad),"embedded NUL filename rejected");
    bad=e;bad.filename=std::wstring(1,static_cast<wchar_t>(0xd800));require(!doc.add_trigger(bad),"invalid UTF16 rejected");
    bad=e;bad.motif=L"Motif";require(!doc.add_trigger(bad),"Segment event cannot author motif name");
    bad=e;bad.itemFlags=1;require(!doc.add_trigger(bad),"Motif requires name");
    require(!doc.delete_trigger(999)&&!doc.edit_trigger(999,e)&&doc.save_bytes()==one&&doc.redo()&&doc.save_bytes()==changed,"invalid inputs leave bytes and redo intact");
    require(!doc.edit_trigger(0,e),"no-op has no new history");
    require(doc.add_trigger(e)&&doc.triggers().size()==2,"simultaneous triggers have independent instances");
    require(doc.delete_trigger(0)&&doc.triggers().size()==1&&doc.undo()&&doc.triggers().size()==2,"delete one overlapping trigger whole-byte Undo");
    SegmentTrigger motif=e;motif.itemFlags=1;motif.motif=L"Intro";motif.filename=L"Owned.stp";motif.name=L"Style";motif.hasId=true;motif.objectId[0]=7;
    require(doc.add_trigger(motif)&&doc.triggers().back().motif==L"Intro","typed Style motif reference");
    const auto mr=Chunk::parse(doc.save_bytes());const auto rh=mr.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children.back().find("LIST","DMRF")->find("refh");
    require(rh->data[0]==0x8a&&read32(rh->data,16)==23,"SDK Style class and class GUID name filename validity");
    doc.select_track_group(2);require(doc.triggers().empty()&&doc.add_trigger(e),"new owned trigger group");doc.select_track_group(1);require(doc.triggers().size()==3,"other group retains all instances");
    auto opaque=Chunk::parse(one);auto& track=opaque.find("LIST","trkl")->children.back();auto& entries=*track.find("LIST","segt")->find("LIST","lsgl");Chunk unknown;unknown.id="zzzz";unknown.data={1,2,3};unknown.padding=0xab;entries.children.insert(entries.children.begin(),unknown);auto& item=entries.children[1];item.children.push_back(unknown);auto& ref=*item.find("LIST","DMRF");ref.children.push_back(unknown);item.find("sgih")->data.insert(item.find("sgih")->data.end(),{5,6});ref.find("refh")->data.insert(ref.find("refh")->data.end(),{7,8});put32(ref.find("refh")->data,16,read32(ref.find("refh")->data,16)|0x10000);const auto before=opaque.encode();SegmentDocument retained;retained.load(before);
    auto moved=retained.triggers()[0];moved.physical=1000;require(retained.edit_trigger(0,moved),"future extensions editable without loss");auto expected=opaque;put32(expected.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1].find("sgih")->data,4,1000);
    require(retained.save_bytes()==expected.encode(),"one clock DWORD changes; opaque fields order padding and flags retained");
    require(retained.undo()&&retained.save_bytes()==before&&retained.redo()&&retained.save_bytes()==expected.encode(),"extended source whole-byte history");
    auto associated=opaque;Chunk association;association.id="jzfr";association.data=Bytes(32,0x45);associated.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1].find("LIST","DMRF")->children.push_back(association);SegmentDocument bound;bound.load(associated.encode());auto identityChange=bound.triggers()[0];identityChange.filename=L"Other.sgp";require(!bound.edit_trigger(0,identityChange)&&bound.save_bytes()==associated.encode(),"design association cannot silently point to a different source");identityChange=bound.triggers()[0];identityChange.physical=1001;require(bound.edit_trigger(0,identityChange),"bound reference timing remains editable");require(Chunk::parse(bound.save_bytes()).find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1].find("LIST","DMRF")->find("jzfr")->data==association.data,"timing edit retains exact Producer file binding");
    auto broken=opaque;broken.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1].find("sgih")->data.resize(15);
    rejected([&]{retained.load(broken.encode());},"truncated trigger load rejects");require(retained.save_bytes()==expected.encode(),"failed load retains previous document");
    broken=opaque;auto& be=broken.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1];be.children.push_back(*be.find("sgih"));rejected([&]{retained.load(broken.encode());},"duplicate item header rejects");
    broken=opaque;broken.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1].find("LIST","DMRF")->find("refh")->data[0]=0;rejected([&]{retained.load(broken.encode());},"reference class mismatch rejects");
    auto pickup=opaque;put32(pickup.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1].find("sgih")->data,0,0xffffffff);SegmentDocument legacy;legacy.load(pickup.encode());require(legacy.triggers()[0].logical==-1&&legacy.save_bytes()==pickup.encode(),"signed original pickup retained without reinterpreting");
    auto unassigned=opaque;auto& u=unassigned.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[1];u.children.erase(std::remove_if(u.children.begin(),u.children.end(),[](const Chunk& c){return c.id=="LIST"&&c.type=="DMRF";}),u.children.end());legacy.load(unassigned.encode());require(!legacy.triggers()[0].hasId&&legacy.triggers()[0].filename.empty()&&legacy.save_bytes()==unassigned.encode(),"unassigned no-effect marker retained");
    const auto folder=dir/L"Trigger";std::filesystem::create_directories(folder);Framework host;host.new_segment();host.document(0).load(doc.save_bytes());host.save_segment(0,(folder/L"Parent.sgp").wstring());host.new_segment();require(host.document(1).add_note({0,384,0,60,96}),"independent source Segment created");host.save_segment(1,(folder/L"Child.sgp").wstring());const auto child=read_file((folder/L"Child.sgp").wstring());host.save_project((folder/L"Trigger.pro").wstring());const auto project=read_file((folder/L"Trigger.pro").wstring());Framework reload;reload.open_project((folder/L"Trigger.pro").wstring());
    require(reload.documents().size()==2&&reload.document(0).save_bytes()==doc.save_bytes()&&reload.document(0).triggers().size()==3&&!reload.dirty(),"native Project reopens owned trigger groups and sources");
    reload.save_project((folder/L"Trigger.pro").wstring());require(read_file((folder/L"Trigger.pro").wstring())==project&&read_file((folder/L"Child.sgp").wstring())==child,"native Project resave and reference source byte exact");
}

void segment_trigger_owned_tests(const std::filesystem::path& dir,bool runtime=false){
    const auto folder=dir/L"Triggered";std::filesystem::create_directories(folder);Framework host;host.new_segment();const auto parent=host.document(0).save_bytes();host.save_segment(0,(folder/L"Parent.sgp").wstring());host.new_segment();auto& child=host.document(1);BandDocument band;require(band.add_gm_instrument(0,0,64,100)&&child.set_band(0,band.save_bytes()),"child GM Band owned");
    require(child.add_note({0,3072,0,60,100})&&child.add_note({3840,768,0,62,100}),"child pitches fixture");host.save_segment(1,(folder/L"Child.sgp").wstring());const auto childDisk=read_file((folder/L"Child.sgp").wstring());
    require(host.assign_segment_trigger(0,1,false,L"",1536,1536,0x80),"owned child assigned from catalog");const auto authored=host.document(0).save_bytes();auto graph=host.trigger_playback(0);
    require(graph.source==authored&&graph.parent!=authored&&graph.segments.size()==1&&graph.segments[0].bytes==childDisk,"private GUID-only parent and source child snapshots");
    auto root=Chunk::parse(graph.parent);const auto ref=root.find("LIST","trkl")->children.back().find("LIST","segt")->find("LIST","lsgl")->children[0].find("LIST","DMRF");require(read32(ref->find("refh")->data,16)==3&&ref->find("file")&&host.document(0).save_bytes()==authored,"loader filename inactive; serialized filename and source document retained");
    require(host.undo_segment(0)&&host.document(0).save_bytes()==parent&&host.redo_segment(0)&&host.document(0).save_bytes()==authored,"Framework shared trigger history");
    auto e=host.document(0).triggers()[0];auto wrong=e;wrong.filename=L"Other.sgp";require(host.document(0).edit_trigger(0,wrong),"mismatching descriptor fixture");const auto mismatch=host.document(0).save_bytes();rejected([&]{host.trigger_playback(0);},"GUID/path conflict refuses before playback");require(host.document(0).save_bytes()==mismatch&&host.undo_segment(0),"failed resolution leaves current state and undo");
    host.new_segment();host.document(2).load(childDisk);host.save_segment(2,(folder/L"Duplicate.sgp").wstring());rejected([&]{host.trigger_playback(0);},"duplicate owned GUID refuses ambiguous snapshot");
    Framework cycle;cycle.new_segment();cycle.save_segment(0,(folder/L"A.sgp").wstring());cycle.new_segment();cycle.save_segment(1,(folder/L"B.sgp").wstring());require(cycle.assign_segment_trigger(0,1,false,L"",0,0,0x80)&&cycle.assign_segment_trigger(1,0,false,L"",0,0,0x80),"cycle authored diagnostic");rejected([&]{cycle.trigger_playback(0);},"cycle refuses before loader");rejected([&]{cycle.assign_segment_trigger(0,0,false,L"",0,0,0x80);},"self trigger author refusal");
    Framework play;play.open_segment((folder/L"Parent.sgp").wstring());play.open_segment((folder/L"Child.sgp").wstring());play.document(0).load(authored);require(play.document(1).edit_note(0,{0,3072,0,65,100}),"unsaved child pitch distinguishes owned snapshot");graph=play.trigger_playback(0);
    require(graph.segments[0].bytes==play.document(1).save_bytes()&&graph.segments[0].bytes!=childDisk&&read_file((folder/L"Child.sgp").wstring())==childDisk,"owned unsaved child beats disk without mutation");
    const auto finish=[&]{play.save_segment(0,(folder/L"Parent.sgp").wstring());play.save_segment(1,(folder/L"Child.sgp").wstring());play.save_project((folder/L"Triggered.pro").wstring());Framework reload;reload.open_project((folder/L"Triggered.pro").wstring());require(reload.document(0).triggers().size()==1&&reload.document(1).notes()[0].pitch==65&&reload.trigger_playback(0).segments.size()==1,"native Project reload owns actual trigger source");};
    Framework motifs;motifs.new_segment();motifs.save_segment(0,(folder/L"MotifParent.sgp").wstring());motifs.new_style();
    require(motifs.new_style_motif(0,L"Intro",0)&&motifs.add_style_band_gm_instrument(0,{},0,0,64,100)&&motifs.assign_style_motif_band(0,0,0),"owned Motif and Band created");
    const auto part=motifs.style_document(0).part_references(0)[0].partIndex;require(motifs.insert_style_part_note(0,part,0,{0,768,0,0xffffffffu,0,100}),"owned Motif note");
    motifs.save_style(0,(folder/L"Motif.stp").wstring());require(motifs.assign_segment_trigger(0,0,true,L"Intro",768,768,0x80),"owned Style Motif assigned");const auto motifGraph=motifs.trigger_playback(0);
    require(motifGraph.motifs.size()==1&&motifGraph.styles.size()==1&&motifGraph.motifs[0].name==L"Intro"&&motifGraph.segments.empty(),"owned Motif private Style dependency");
    rejected([&]{motifs.assign_segment_trigger(0,0,true,L"Missing",0,0,0x80);},"missing owned Motif author refusal");
    if(!runtime){finish();return;}
    Conductor conductor;conductor.enable_note_observation();conductor.play(play.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{}, {},{}, {},graph);const auto start=conductor.playback_request().actualStart;Sleep(2600);const auto notes=conductor.observed_notes();
    require(std::any_of(notes.begin(),notes.end(),[&](const auto& n){return n.midiValue==65&&n.clocks>=start+1536;}),"actual triggered child emits unsaved pitch at trigger clocks");
    require(std::none_of(notes.begin(),notes.end(),[](const auto& n){return n.midiValue==60;}),"disk-only child pitch not emitted");
    conductor.stop();const auto stopped=conductor.observed_notes().size();Sleep(1800);{std::ostringstream out;out<<"{\"stoppedCount\":"<<stopped<<",\"notes\":[";bool first=true;for(const auto& n:conductor.observed_notes()){if(!first)out<<",";first=false;out<<"{\"clock\":"<<n.clocks<<",\"duration\":"<<n.duration<<",\"midi\":"<<unsigned(n.midiValue)<<",\"flags\":"<<unsigned(n.flags)<<"}";}out<<"],\"calls\":[";first=true;for(const auto& c:conductor.calls()){if(!first)out<<",";first=false;out<<"{\"operation\":\""<<c.operation<<"\",\"hr\":"<<c.result<<"}";}out<<"]}";const auto text=out.str();write_file_atomic((dir/L"trigger-stop-diagnostics.json").wstring(),Bytes(text.begin(),text.end()));}
    require(conductor.observed_notes().size()==stopped&&!conductor.position().playing,"owned triggered playback stopped and later messages absent");
    conductor.play(play.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{}, {},{}, {},graph);Sleep(2600);require(conductor.observed_notes().size()>stopped&&!conductor.note_observation_overflow()&&!conductor.note_observation_forwarding_failed(),"triggered graph replay emits new notes and forwards");conductor.stop();conductor.shutdown();
    Conductor motifPlayer;motifPlayer.enable_note_observation();motifPlayer.play(motifs.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{}, {},{}, {},motifGraph);Sleep(2200);require(!motifPlayer.observed_notes().empty(),"actual trigger Style Motif generates notes");motifPlayer.stop();motifPlayer.shutdown();
    require(play.assign_segment_trigger(0,1,false,L"",1536,1536,0,0),"primary trigger authored");const auto primary=play.trigger_playback(0);Conductor primaryPlayer;primaryPlayer.enable_note_observation();primaryPlayer.play(play.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{}, {},{}, {},primary);Sleep(2200);require(primaryPlayer.position().playing&&!primaryPlayer.observed_notes().empty(),"primary child keeps owned session active after replacing parent");primaryPlayer.stop();primaryPlayer.shutdown();require(play.undo_segment(0),"restore secondary trigger");
    require(play.assign_segment_trigger(0,1,false,L"",1536,1536,0x280,0),"control secondary trigger authored");const auto control=play.trigger_playback(0);Conductor controlPlayer;controlPlayer.enable_note_observation();controlPlayer.play(play.document(0).save_bytes(),folder.wstring(),GetDesktopWindow(),{}, {},{}, {},control);Sleep(2200);require(controlPlayer.position().playing&&!controlPlayer.observed_notes().empty(),"control secondary child emits notes in owned session");controlPlayer.stop();controlPlayer.shutdown();require(play.undo_segment(0),"restore saved secondary fixture");finish();
}
