void signpost_track_tests(const std::filesystem::path& dir){
    SegmentDocument doc;const auto clean=doc.save_bytes();SignpostEvent e{800,0x100,99};require(doc.set_signpost(e)&&doc.signposts().size()==1&&doc.signposts()[0].time==0&&doc.signposts()[0].measure==0,"SignPost insert derives and snaps Timeline measure");const auto inserted=doc.save_bytes();
    e={3000,0x8002,99};require(doc.set_signpost(e)&&doc.signposts().size()==1&&doc.signposts()[0].chords==0x8002,"SignPost occupied measure replaced with group and cadence");const auto replaced=doc.save_bytes();require(doc.undo()&&doc.save_bytes()==inserted&&doc.redo()&&doc.save_bytes()==replaced,"SignPost full document replacement Undo Redo");
    e={4000,0x4000,0};require(doc.set_signpost(e)&&doc.signposts()[1].time==3072&&doc.signposts()[1].measure==1,"SignPost second measure stored coordinates");const auto two=doc.save_bytes();e.time=20;size_t index=999;require(doc.edit_signpost(1,e,0,&index)&&index==0&&doc.signposts().size()==1&&doc.signposts()[0].chords==0x4000,"SignPost move replaces destination measure and returns index");require(doc.undo()&&doc.save_bytes()==two,"SignPost collision Undo restores both markers");
    const auto reject=[&](SignpostEvent bad){const auto before=doc.save_bytes();const auto dirty=doc.dirty();auto expected=doc;size_t index=999;require(!doc.edit_signpost(0,bad,0,&index)&&index==999&&doc.save_bytes()==before&&doc.dirty()==dirty,"Invalid SignPost leaves bytes dirty output unchanged");require(doc.undo()==expected.undo()&&doc.save_bytes()==expected.save_bytes()&&doc.redo()==expected.redo()&&doc.save_bytes()==expected.save_bytes(),"Invalid SignPost preserves full history");};
    reject({-1,1,0});reject({doc.length(),1,0});reject({0,0,0});reject({0,0x8000,0});reject({0,3,0});reject({0,0x80,0});reject({0,0x10000,0});
    const std::uint32_t groups[]={1,2,4,8,16,32,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000};for(const auto group:groups){e={0,group|0x8000,0};require(doc.set_signpost(e)&&doc.signposts()[0].chords==(group|0x8000),"All thirteen SignPost groups permit cadence");}
    const auto base=dir/L"signpost-track";std::filesystem::create_directories(base);doc.save((base/L"Song.sgp").wstring());SegmentDocument reload;reload.load(read_file((base/L"Song.sgp").wstring()));require(reload.save_bytes()==doc.save_bytes()&&!reload.dirty()&&reload.signposts().size()==2,"SignPost saved Segment restores typed values and checkpoint");
    Framework host;const auto owned=host.open_segment((base/L"Song.sgp").wstring());e={6144,1,0};require(host.document(owned).set_signpost(e),"Framework owns SignPost edit");host.save_segment(owned,(base/L"Song.sgp").wstring());host.save_project((base/L"signpost-track.pro").wstring());Framework restored;restored.open_project((base/L"signpost-track.pro").wstring());require(restored.document(0).save_bytes()==host.document(owned).save_bytes()&&restored.document(0).signposts().size()==3&&Chunk::parse(read_file((base/L"signpost-track.pro").wstring())).type=="JAZP","SignPost native Project restores edited saved Segment");
    auto fresh=signpost_track();auto& bytes=fresh.find("sgnp")->data;require(set_signpost_event(bytes,{0,1,0}),"Raw SignPost insertion");bytes[14]=0xa5;bytes[15]=0x5a;bytes.insert(bytes.end(),{0x12,0x34,0x56,0x78});put32(bytes,0,16);put32(bytes,8,0x10000001);e={3072,0x10008001,1};require(change_signpost_event(bytes,0,e)&&bytes[14]==0xa5&&bytes[15]==0x5a&&bytes[16]==0x12&&signpost_events(bytes)[0].chords==0x10008001,"SignPost known cadence edit preserves imported group reserved and extended bytes");
    const auto malformed=[&](Bytes broken){const auto before=broken;bool refused=false;try{(void)set_signpost_event(broken,{0,1,0});}catch(const std::exception&){refused=true;}require(refused&&broken==before,"Malformed SignPost refuses without mutation");};auto broken=bytes;put32(broken,0,0);malformed(broken);broken=bytes;put32(broken,0,9);malformed(broken);broken=bytes;put32(broken,0,UINT32_MAX);malformed(broken);broken=bytes;broken.pop_back();malformed(broken);
    doc.select_track_group(2);require(doc.signposts().empty()&&doc.set_signpost({0,2,0})&&doc.signposts().size()==1,"SignPost selected group owns independent track");doc.select_track_group(1);require(doc.signposts().size()==2&&doc.delete_signpost(0)&&doc.signposts().size()==1&&doc.undo()&&doc.signposts().size()==2,"SignPost group isolation delete Undo");require(doc.save_bytes()!=clean,"SignPost authored output retained");
}
