void source_tool_tests(const std::filesystem::path& dir){
    const auto factories=source_tool_factories();ToolGraphDocument graph;graph.add_tool(source_velocity_tool_class,{0});graph.add_tool(source_velocity_tool_class,{0});graph.set_tool_payload(1,source_velocity_payload(.5f));
    const auto baseline=graph.save_bytes();require(source_velocity_gain(graph.tools()[0])==1&&source_velocity_gain(graph.tools()[1])==.5f,"Source Tool neutral properties and distinct product class");
    require(graph.undo()&&source_velocity_gain(graph.tools()[1])==1&&graph.redo()&&graph.save_bytes()==baseline,"Tool properties are one graph undo/redo edit");
    auto invalid=graph.tools()[0];invalid.payload=source_velocity_payload(1);invalid.payload->data.push_back(0);rejected([&]{factories[0].validate(invalid);},"Extended malformed source properties rejected before activation");
    rejected([&]{source_velocity_payload(std::numeric_limits<float>::quiet_NaN());},"NaN source properties rejected");rejected([&]{source_velocity_payload(1.01f);},"Out of range source properties rejected");
    auto reserved=source_velocity_payload(1);reserved.id="tolh";require(!graph.set_tool_payload(0,reserved)&&graph.save_bytes()==baseline,"Reserved payload edit retains graph and history");
    AudioPathDocument path;path.set_tool_graph(baseline);const auto capabilities=discover_audio_path_tool_parameters(path.save_bytes());
    require(capabilities.size()==2&&capabilities[0].address.stage==0x2300&&capabilities[0].address.index==0&&capabilities[1].address.index==1,"Embedded AudioPath discovers class-specific Tool instances");
    require(capabilities[0].parameters.size()==1&&capabilities[0].parameters[0].index==0&&std::wstring(capabilities[0].parameters[0].info.szLabel)==L"Velocity gain"&&capabilities[0].parameters[0].info.mopCaps==3,"Parameter names and curve capabilities come from IMediaParamInfo");
    require(valid_tool_parameter_curve(capabilities[0].parameters[0],{0,768,0,1,2,0})&&!valid_tool_parameter_curve(capabilities[0].parameters[0],{0,768,0,1,4,0})&&!valid_tool_parameter_curve(capabilities[0].parameters[0],{0,768,-.1f,1,1,0})&&!valid_tool_parameter_curve(capabilities[0].parameters[0],{0,768,0,1,1,3}),"Source curve shape/range/flags admission follows capability");
    std::unique_ptr<producer::runtime::Tool,void(*)(producer::runtime::Tool*)> tool(factories[0].create(graph.tools()[0]),[](auto* p){if(p)p->Release();});IMediaParams* raw=nullptr;require(SUCCEEDED(tool->QueryInterface(__uuidof(IMediaParams),reinterpret_cast<void**>(&raw))),"Product source instance exposes actual IMediaParams");std::unique_ptr<IMediaParams,void(*)(IMediaParams*)> params(raw,[](auto* p){if(p)p->Release();});
    GUID musicTime{};std::memcpy(&musicTime,param_time_music.data(),16);require(params->SetTimeFormat(musicTime,768)==S_OK&&FAILED(params->SetTimeFormat(musicTime,1)),"Music time accepts actual DirectMusic768 PPQ and rejects wrong scale");
    MP_ENVELOPE_SEGMENT linear{100,200,.25f,.75f,MP_CURVE_LINEAR,0};require(params->AddEnvelope(0,1,&linear)==S_OK,"Product accepts linear envelope");
    const auto velocity=[&](LONG at){producer::runtime::NoteMessage note{};note.message.type=1;note.message.size=sizeof(note);note.message.musicTime=at;note.velocity=100;tool->ProcessPMsg(nullptr,&note.message);return note.velocity;};
    require(velocity(0)==100&&velocity(100)==25&&velocity(150)==50&&velocity(200)==75&&velocity(300)==75,"Linear exact clocks and pre/post envelope gaps");require(params->SetParam(DWORD_ALLPARAMS,.9f)==S_OK&&velocity(150)==50,"SetParam applies all parameters without deleting the active envelope");
    auto bad=linear;bad.valEnd=2;require(FAILED(params->AddEnvelope(0,1,&bad))&&velocity(150)==50,"Rejected envelope retains active curve");bad=linear;bad.iCurve=MP_CURVE_SINE;require(FAILED(params->AddEnvelope(0,1,&bad)),"Unsupported runtime shape rejected");
    require(FAILED(params->SetParam(1,.5f))&&FAILED(params->SetParam(0,-1)),"Unknown parameter and invalid SetParam retain value");
    float latest=0;require(params->GetParam(0,&latest)==S_OK&&latest==.5f,"GetParam reports last processed value");
    MP_ENVELOPE_SEGMENT current{400,500,0,1,MP_CURVE_LINEAR,MPF_ENVLP_BEGIN_CURRENTVAL};require(params->AddEnvelope(0,1,&current)==S_OK&&velocity(400)==50&&velocity(450)==75,"Begin Current uses last value rather than authored start");
    MP_ENVELOPE_SEGMENT neutral{600,700,0,.5f,MP_CURVE_LINEAR,MPF_ENVLP_BEGIN_NEUTRALVAL};require(params->AddEnvelope(0,1,&neutral)==S_OK&&velocity(600)==100,"Begin Neutral uses source property");
    tool->Flush(nullptr,nullptr,0);require(velocity(150)==100,"Tool flush resets envelopes and neutral value");
    auto d=SegmentDocument::playback_test();d.set_audio_path(path.save_bytes());d.add_parameter_object(capabilities[0].address);d.add_parameter(0,0);d.add_parameter_curve(0,0,{0,3072,.25f,.25f,1,0});d.add_parameter_curve(0,0,{3072,6144,.75f,.75f,1,0});validate_source_parameter_controls(d.parameter_controls(),capabilities);
    const auto original=d.save_bytes();auto privateCopy=d;privateCopy.edit_parameter_curve(0,0,0,{0,3072,2,2,1,0});rejected([&]{validate_source_parameter_controls(privateCopy.parameter_controls(),capabilities);},"Known Tool invalid authored gain rejected before publication");require(d.save_bytes()==original,"Rejected private Tool edit retains whole Segment");
    privateCopy=d;privateCopy.add_parameter(0,1);rejected([&]{validate_source_parameter_controls(privateCopy.parameter_controls(),capabilities);},"Unsupported discovered parameter rejected");
    const auto project=dir/L"SourceToolProject";std::filesystem::create_directories(project);Framework host;host.tool_graph_document(host.new_tool_graph()).load(baseline);host.save_tool_graph(0,(project/L"Tools.tgp").wstring());host.audio_path_document(host.new_audio_path()).load(path.save_bytes());host.save_audio_path(0,(project/L"Tools.aup").wstring());host.document(host.new_segment()).load(original);host.save_segment(0,(project/L"Automation.sgp").wstring());auto seed=SegmentDocument::playback_test();seed.set_audio_path(path.save_bytes());host.document(host.new_segment()).load(seed.save_bytes());host.save_segment(1,(project/L"Authoring.sgp").wstring());host.save_project((project/L"SourceToolProject.pro").wstring());Framework reopened;reopened.open_project((project/L"SourceToolProject.pro").wstring());require(reopened.document(0).save_bytes()==original&&reopened.tool_graph_document(0).save_bytes()==baseline&&reopened.audio_path_document(0).save_bytes()==path.save_bytes(),"Source Tool native Project restores graph properties path and automation");
}
void source_tool_runtime_tests(const std::filesystem::path& dir){
    ToolGraphDocument graph;graph.add_tool(source_velocity_tool_class,{0});graph.add_tool(source_velocity_tool_class,{0});graph.set_tool_payload(1,source_velocity_payload(.5f));AudioPathDocument path;path.set_tool_graph(graph.save_bytes());const auto objects=discover_audio_path_tool_parameters(path.save_bytes());auto d=SegmentDocument::playback_test();d.set_audio_path(path.save_bytes());d.add_parameter_object(objects[0].address);d.add_parameter(0,0);d.add_parameter_curve(0,0,{0,3072,.25f,.25f,1,0});d.add_parameter_curve(0,0,{3072,6144,.75f,.75f,1,0});const auto source=d.save_bytes();write_file_atomic((dir/L"ProductToolAutomation.sgp").wstring(),source);
    Conductor c;c.set_tool_factories(source_tool_factories());c.enable_note_observation();c.play(source,L"",nullptr);const auto id=c.current_playback_id();auto bad=d;auto invalidGraph=graph;invalidGraph.set_tool_payload(0,Chunk{"data","",Bytes{1,0,0,0}, {}});auto invalidPath=path;invalidPath.set_tool_graph(invalidGraph.save_bytes());bad.set_audio_path(invalidPath.save_bytes());rejected([&]{c.play(bad.save_bytes(),L"",nullptr);},"Malformed builtin properties rejected before old playback Stop");require(c.current_playback_id()==id,"Rejected builtin payload retains current session");auto badCurve=d;badCurve.edit_parameter_curve(0,0,0,{0,3072,2,2,1,0});rejected([&]{c.play(badCurve.save_bytes(),L"",nullptr);},"Unsupported builtin automation rejected before runtime Stop");require(c.current_playback_id()==id,"Rejected builtin automation retains current session");
    const auto deadline=GetTickCount64()+12000;bool started=false,finished=false;while(GetTickCount64()<deadline){const auto p=c.position();started=started||p.playing;if(started&&!p.playing){finished=true;break;}Sleep(20);}require(finished,"Product builtin Tool actual OS playback starts and completes");c.stop();const auto notes=c.observed_notes();std::cerr<<"product source notes="<<notes.size()<<"\n";for(const auto& n:notes)std::cerr<<"product source velocity="<<unsigned(n.velocity)<<"\n";require(notes.size()==8&&std::all_of(notes.begin(),notes.begin()+4,[](const PlaybackNote& n){return n.velocity==12;})&&std::all_of(notes.begin()+4,notes.end(),[](const PlaybackNote& n){return n.velocity==36;}),"Actual OS parameter curves and second same-class Tool compose in order");require(d.save_bytes()==source&&read_file((dir/L"ProductToolAutomation.sgp").wstring())==source,"Product Tool runtime retains source document bytes");require(!c.note_observation_overflow()&&!c.note_observation_forwarding_failed(),"Product Tool forwards all observed notes without overflow");c.shutdown();
}
