template<class T> struct StyleBandRelease {void operator()(T* p)const{if(p)p->Release();}};
template<class T> using StyleBandOwner=std::unique_ptr<T,StyleBandRelease<T>>;
StyleBandOwner<producer::runtime::Track> load_style_band_os_track(const Chunk& track,const std::filesystem::path& dir,const Bytes& source){
    namespace rt=producer::runtime;
    const std::vector<std::pair<GUID,std::wstring>> declared={{rt::bandTrackClass,L"dmband.dll"},{rt::loaderClass,L"dmloader.dll"},{rt::segmentClass,L"dmime.dll"},{rt::styleClass,L"dmstyle.dll"}};
    // Verify all declared public classes before any COM instantiation.
    for(const auto& entry:declared){
        wchar_t id[40]{},serverPath[32768]{},expanded[32768]{},system[MAX_PATH]{},wow[MAX_PATH]{};
        require(StringFromGUID2(entry.first,id,40)!=0,"Public class formats");
        const auto key=std::wstring(L"CLSID\\")+id+L"\\InprocServer32";DWORD size=sizeof(serverPath);
        require(RegGetValueW(HKEY_CLASSES_ROOT,key.c_str(),nullptr,RRF_RT_REG_SZ|RRF_RT_REG_EXPAND_SZ,nullptr,serverPath,&size)==ERROR_SUCCESS,"Declared OS registration available");
        const auto count=ExpandEnvironmentStringsW(serverPath,expanded,32768);require(count>0&&count<=32768,"Declared path expands");
        GetSystemDirectoryW(system,MAX_PATH);GetSystemWow64DirectoryW(wow,MAX_PATH);const auto server=std::filesystem::path(expanded).lexically_normal();
        require(CompareStringOrdinal(server.filename().c_str(),-1,entry.second.c_str(),-1,TRUE)==CSTR_EQUAL&&(CompareStringOrdinal(server.parent_path().c_str(),-1,system,-1,TRUE)==CSTR_EQUAL||CompareStringOrdinal(server.parent_path().c_str(),-1,wow,-1,TRUE)==CSTR_EQUAL),"Track/Loader/Segment use declared Windows modules only");
    }
    const GUID iid={0xf96029a1,0x4282,0x11d2,{0x87,0x17,0,0x60,8,0x93,0xb1,0xbd}};
    rt::Track* raw=nullptr;require(CoCreateInstance(rt::bandTrackClass,nullptr,CLSCTX_INPROC_SERVER,iid,reinterpret_cast<void**>(&raw))==S_OK&&raw,"Create real OS Band track");StyleBandOwner<rt::Track> direct(raw);
    IPersistStream* pp=nullptr;require(raw->QueryInterface(IID_IPersistStream,reinterpret_cast<void**>(&pp))==S_OK&&pp,"Real OS Band track persistence available");StyleBandOwner<IPersistStream> persistence(pp);
    IStream* sp=nullptr;require(CreateStreamOnHGlobal(nullptr,TRUE,&sp)==S_OK&&sp,"Band input memory stream created");StyleBandOwner<IStream> stream(sp);
    const auto bytes=track.find("RIFF","DMBT")->encode();write_file_atomic((dir/L"plain-input.dmbt").wstring(),bytes);ULONG written=0;require(sp->Write(bytes.data(),static_cast<ULONG>(bytes.size()),&written)==S_OK&&written==bytes.size(),"Full Band input stream written");LARGE_INTEGER zero{};require(sp->Seek(zero,STREAM_SEEK_SET,nullptr)==S_OK,"Band input stream rewound");
    const auto plain=pp->Load(sp);std::cerr<<"plain HGLOBAL BandTrack Load HRESULT=0x"<<std::hex<<static_cast<unsigned long>(plain)<<std::dec<<std::endl;
    // Full Segment loading provides the public Loader stream context used by the product.
    SegmentDocument input;auto root=Chunk::parse(input.save_bytes());put32(root.find("segh")->data,4,9216);root.find("LIST","trkl")->children={track};const auto segmentBytes=root.encode();write_file_atomic((dir/L"loader-input.sgp").wstring(),segmentBytes);
    rt::Loader* lr=nullptr;require(CoCreateInstance(rt::loaderClass,nullptr,CLSCTX_INPROC_SERVER,rt::loader8Id,reinterpret_cast<void**>(&lr))==S_OK&&lr,"Create declared OS Loader");StyleBandOwner<rt::Loader> loader(lr);
    rt::ObjectDesc descriptor{};descriptor.size=sizeof(descriptor);descriptor.valid=2|1024;descriptor.classId=rt::segmentClass;descriptor.memory=const_cast<BYTE*>(segmentBytes.data());descriptor.memoryLength=segmentBytes.size();
    rt::Segment* sr=nullptr;const auto loaded=lr->GetObject(&descriptor,rt::segment8Id,reinterpret_cast<void**>(&sr));StyleBandOwner<rt::Segment> segment(sr);
    const std::string diagnostic="{\"plainHGlobalLoadHResult\":"+std::to_string(static_cast<unsigned long>(plain))+",\"loaderSegmentLoadHResult\":"+std::to_string(static_cast<unsigned long>(loaded))+",\"fullAcceptance\":false}\n";write_file_atomic((dir/L"loader-conditions.json").wstring(),Bytes(diagnostic.begin(),diagnostic.end()));
    require(loaded==S_OK&&segment,"Real OS Loader loads full three-Band Segment");
    rt::Track* tr=nullptr;require(sr->GetTrack(rt::bandTrackClass,1,0,&tr)==S_OK&&tr,"Loaded Segment returns real OS Band track");StyleBandOwner<rt::Track> result(tr);
    for(LONG query:{0,3072,6144}){LONG next=0;rt::BandParam value{};const auto hr=tr->GetParam(rt::bandParam,query,&next,&value);StyleBandOwner<IUnknown> band(value.band);std::cerr<<"independent Band query="<<query<<"; HRESULT=0x"<<std::hex<<static_cast<unsigned long>(hr)<<std::dec<<"; next="<<next<<"; physical="<<value.physicalTime<<"; band="<<(band?1:0)<<std::endl;}
    // Native embedded Band objects expose no identifying fields on this OS.
    // Keep that observation separate from source-identified public Band events.
    StyleDocument owned;owned.load(source);auto memory=source;rt::ObjectDesc styleDescriptor{};styleDescriptor.size=sizeof(styleDescriptor);styleDescriptor.valid=2|1024;styleDescriptor.classId=rt::styleClass;styleDescriptor.memory=memory.data();styleDescriptor.memoryLength=memory.size();
    rt::Style* st=nullptr;require(lr->GetObject(&styleDescriptor,rt::styleId,reinterpret_cast<void**>(&st))==S_OK&&st,"Load full owned three-Band Style through declared OS");StyleBandOwner<rt::Style> style(st);
    rt::Track* out=nullptr;require(CoCreateInstance(rt::bandTrackClass,nullptr,CLSCTX_INPROC_SERVER,iid,reinterpret_cast<void**>(&out))==S_OK&&out,"Create fresh public source-identified Band track");StyleBandOwner<rt::Track> identified(out);
    const auto values=band_track_events(track);
    for(const auto& event:values){const auto bandRoot=Chunk::parse(event.band);const auto name=decode_utf16(bandRoot.find("LIST","UNFO")->find("UNAM")->data);rt::Band* br=nullptr;require(st->GetBand(const_cast<WCHAR*>(name.c_str()),&br)==S_OK&&br,"Declared OS Style returns source-selected Band");StyleBandOwner<IUnknown> band(reinterpret_cast<IUnknown*>(br));rt::MusicObject* object=nullptr;require(band->QueryInterface(rt::musicObjectId,reinterpret_cast<void**>(&object))==S_OK&&object,"Selected Band public descriptor available");StyleBandOwner<rt::MusicObject> descriptorObject(object);rt::ObjectDesc d{};d.size=sizeof(d);require(object->GetDescriptor(&d)==S_OK,"Selected Band descriptor reads");std::wcerr<<L"selected public Band "<<name<<L" flags="<<d.valid<<L" name="<<d.name<<std::endl;rt::BandParam p{event.physicalTime,band.get()};require(out->SetParam(rt::bandParam,event.logicalTime,&p)==S_OK,"Public BandTrack SetParam owns selected full Band object");}
    for(LONG query:{0,3072,6144}){LONG next=0;rt::BandParam value{};const auto hr=out->GetParam(rt::bandParam,query,&next,&value);StyleBandOwner<IUnknown> band(value.band);std::cerr<<"identified independent Band query="<<query<<"; HRESULT=0x"<<std::hex<<static_cast<unsigned long>(hr)<<std::dec<<"; next="<<next<<"; physical="<<value.physicalTime<<std::endl;}
    return identified;
}
void style_player_band_tests(const std::filesystem::path& dir){
    const auto initialized=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);require(SUCCEEDED(initialized),"Band test COM apartment initialized");struct Uninitialize{~Uninitialize(){CoUninitialize();}} apartment;
    auto band=[](const std::wstring& name,unsigned patch,std::uint32_t channel){BandDocument d;require(d.add_gm_instrument(patch,channel,64,96),"Source Band instrument creates");auto root=Chunk::parse(d.save_bytes());Chunk info;info.id="LIST";info.type="UNFO";Chunk title;title.id="UNAM";title.data=utf16(name);info.children.push_back(title);root.children.push_back(info);Chunk opaque;opaque.id="XTRA";opaque.data={1,2,3,4,5};opaque.padding=0xa5;root.children.push_back(opaque);return root.encode();};
    const std::vector<Bytes> bands={band(L"Piano A",0,0),band(L"Violin B",40,17),band(L"Flute C",73,0)};
    StyleDocument style;auto root=Chunk::parse(style.save_bytes());for(const auto& b:bands)root.children.push_back(Chunk::parse(b));style.load(root.encode());const auto source=style.save_bytes();
    auto track=make_band_track();for(size_t i=0;i<bands.size();++i)require(set_band_track_event(track,static_cast<LONG>(i*3072),bands[i]),"Distinct native Band event creates");require(move_band_track_event(track,1,3072,2800)&&move_band_track_event(track,2,6144,5900),"Native Band physical times are distinct");const auto original=track.encode();
    SegmentDocument initialDocument;auto initialRoot=Chunk::parse(initialDocument.save_bytes());put32(initialRoot.find("segh")->data,4,9216);initialRoot.find("LIST","trkl")->children.push_back(track);require(initial_style_player_band_name(initialRoot.encode())==L"Piano A","Main initial selection accepts later Band events");auto noInitialInput=initialRoot;delete_band_track_event(noInitialInput.find("LIST","trkl")->children.back(),0);rejected([&]{initial_style_player_band_name(noInitialInput.encode());},"Initial selection rejects absent zero event");auto ambiguousInitialInput=initialRoot;auto second=track;put32(second.find("trkh")->data,20,2);ambiguousInitialInput.find("LIST","trkl")->children.push_back(second);rejected([&]{initial_style_player_band_name(ambiguousInitialInput.encode());},"Initial selection rejects ambiguous Band tracks");
    auto runtime=load_style_band_os_track(track,dir,source);const auto exported=read_style_player_bands(runtime.get(),9216,source,bands[0]);const auto events=band_track_events(exported);
    require(events.size()==3,"Every OS-reported Band event persists");
    for(size_t i=0;i<events.size();++i)require(events[i].logicalTime==static_cast<LONG>(i*3072)&&events[i].physicalTime==(i==0?0:i==1?2800:5900)&&events[i].band==bands[i],"Band logical/physical time and complete owned bytes retained");
    require(style.save_bytes()==source&&!style.dirty()&&track.encode()==original,"Multi-Band export preserves source bytes and dirty state");
    auto missing=root;missing.children.pop_back();rejected([&]{read_style_player_bands(runtime.get(),9216,missing.encode(),bands[0]);},"Missing later source Band rejects instead of default substitution");
    auto duplicate=root;duplicate.children.push_back(Chunk::parse(bands[1]));rejected([&]{read_style_player_bands(runtime.get(),9216,duplicate.encode(),bands[0]);},"Ambiguous later source Band rejects");
    rejected([&]{read_style_player_bands(runtime.get(),3072,source,bands[0]);},"Reported Band beyond declared Segment length rejects");
    rejected([&]{read_style_player_bands(nullptr,9216,source,bands[0]);},"Absent runtime Band track rejects");
    rejected([&]{read_style_player_bands(runtime.get(),9216,source,band(L"Foreign",9,0));},"Foreign default Band rejects before fallback");
    require(style.save_bytes()==source&&track.encode()==original,"Rejected multi-Band export leaves all owned inputs unchanged");
    SegmentDocument document;auto segment=Chunk::parse(document.save_bytes());put32(segment.find("segh")->data,4,9216);segment.find("LIST","trkl")->children.push_back(exported);document.load(segment.encode());document.save((dir/L"multiple-band.sgp").wstring());SegmentDocument restored;restored.load(read_file((dir/L"multiple-band.sgp").wstring()));require(initial_style_player_band_name(restored.save_bytes())==L"Piano A","Main audition accepts one initial Band with later changes");auto noInitial=segment;delete_band_track_event(noInitial.find("LIST","trkl")->children.back(),0);rejected([&]{initial_style_player_band_name(noInitial.encode());},"Audition still requires an initial Band at zero");auto conflicting=segment;auto other=exported;put32(other.find("trkh")->data,20,2);conflicting.find("LIST","trkl")->children.push_back(other);rejected([&]{initial_style_player_band_name(conflicting.encode());},"Ambiguous audition Band tracks reject");const auto finalEvents=restored.band_events();require(finalEvents.size()==3&&finalEvents[2].band==bands[2]&&finalEvents[1].physicalTime==2800,"Native Segment restores complete three-Band timeline");
    write_file_atomic((dir/L"owned-style.stp").wstring(),source);write_file_atomic((dir/L"original-band-track.dmbt").wstring(),track.find("RIFF","DMBT")->encode());
}
