namespace runtime=producer::runtime;
template<class T> struct StyleDefaultRelease {void operator()(T* p)const{if(p)p->Release();}};
template<class T> using StyleDefaultOwned=std::unique_ptr<T,StyleDefaultRelease<T>>;
std::vector<Bytes> style_default_public_roles(Bytes styleBytes,Bytes mapBytes,const StylePlayerSettings& settings){
    struct Apartment {Apartment(){require(SUCCEEDED(CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED)),"Independent default-map oracle apartment");}~Apartment(){CoUninitialize();}} apartment;
    runtime::Loader* rawLoader=nullptr;require(CoCreateInstance(runtime::loaderClass,nullptr,CLSCTX_INPROC_SERVER,runtime::loader8Id,reinterpret_cast<void**>(&rawLoader))==S_OK,"Independent declared OS Loader");StyleDefaultOwned<runtime::Loader> loader(rawLoader);
    auto load=[&](Bytes& bytes,REFGUID cls,REFGUID iid)->IUnknown*{runtime::ObjectDesc desc{};desc.size=sizeof(desc);desc.valid=2|1024;desc.classId=cls;desc.memory=bytes.data();desc.memoryLength=bytes.size();const auto hr=loader->EnableCache(cls,TRUE);require(hr==S_OK||hr==S_FALSE,"Independent default-map cache");require(loader->SetObject(&desc)==S_OK,"Independent default-map registration");IUnknown* raw=nullptr;require(loader->GetObject(&desc,iid,reinterpret_cast<void**>(&raw))==S_OK&&raw,"Independent default-map source load");return raw;};
    StyleDefaultOwned<IUnknown> ownedMap(load(mapBytes,runtime::chordMapClass,runtime::chordMapId));
    StyleDefaultOwned<runtime::Style> style(reinterpret_cast<runtime::Style*>(load(styleBytes,runtime::styleClass,runtime::styleId)));
    runtime::ChordMap* rawMap=nullptr;const auto hr=style->GetDefaultChordMap(&rawMap);StyleDefaultOwned<runtime::ChordMap> map(rawMap);std::cerr<<"Style GetDefaultChordMap HRESULT=0x"<<std::hex<<static_cast<unsigned long>(hr)<<"; object="<<(rawMap?1:0)<<std::dec<<std::endl;require(hr==S_OK&&map,"Style public GetDefaultChordMap returns source map");
    runtime::MusicObject* rawDescriptor=nullptr;require(map->QueryInterface(runtime::musicObjectId,reinterpret_cast<void**>(&rawDescriptor))==S_OK,"Default-map public descriptor");StyleDefaultOwned<runtime::MusicObject> descriptor(rawDescriptor);runtime::ObjectDesc identity{};identity.size=sizeof(identity);require(descriptor->GetDescriptor(&identity)==S_OK&&(identity.valid&1),"Default-map descriptor identity");ChordMapDocument source;source.load(mapBytes);require(std::memcmp(&identity.objectId,source.object_id().data(),16)==0,"Default-map public identity matches immutable input");
    runtime::Composer* rawComposer=nullptr;require(CoCreateInstance(runtime::composerClass,nullptr,CLSCTX_INPROC_SERVER,runtime::composerId,reinterpret_cast<void**>(&rawComposer))==S_OK,"Independent declared OS Composer");StyleDefaultOwned<runtime::Composer> composer(rawComposer);
    runtime::Segment* rawSegment=nullptr;require(composer->ComposeSegmentFromShape(style.get(),settings.measures,static_cast<WORD>(settings.shape),settings.activity,settings.intro,settings.end,map.get(),&rawSegment)==S_OK&&rawSegment,"Independent composition uses Style-selected map");StyleDefaultOwned<runtime::Segment> segment(rawSegment);
    std::vector<Bytes> roles;for(DWORD index=0;index<4096;++index){runtime::Track* raw=nullptr;const auto status=segment->GetTrack(GUID_NULL,0xFFFFFFFFu,index,&raw);StyleDefaultOwned<runtime::Track> track(raw);if(status==DMUS_E_NOT_FOUND&&!track)break;require(status==S_OK&&track,"Independent generated track enumeration");IPersistStream* rawPersistence=nullptr;require(track->QueryInterface(IID_IPersistStream,reinterpret_cast<void**>(&rawPersistence))==S_OK,"Independent generated track class access");StyleDefaultOwned<IPersistStream> persistence(rawPersistence);GUID cls{};DWORD group=0;require(persistence->GetClassID(&cls)==S_OK&&segment->GetTrackGroup(track.get(),&group)==S_OK,"Independent generated class and groups");Bytes role(20);std::memcpy(role.data(),&cls,16);put32(role,16,group);roles.push_back(std::move(role));}
    require(!roles.empty()&&roles.size()<4096,"Independent generated roles bound");std::sort(roles.begin(),roles.end());return roles;
}
void style_player_default_tests(const std::filesystem::path& dir,const std::wstring& stylePath,const std::wstring& mapPath){
    const auto inputStyle=read_file(stylePath),mapBytes=read_file(mapPath);ChordMapDocument map;map.load(mapBytes);auto root=Chunk::parse(inputStyle);const auto mapId=map.object_id();
    root.children.erase(std::remove_if(root.children.begin(),root.children.end(),[](const Chunk& c){return c.id=="LIST"&&c.type=="prrf";}),root.children.end());
    Chunk refs;refs.id="LIST";refs.type="prrf";Chunk descriptor;descriptor.id="LIST";descriptor.type="DMRF";Chunk header;header.id="refh";header.data=Bytes(20);std::memcpy(header.data.data(),&runtime::chordMapClass,16);put32(header.data,16,1|2|16);Chunk id;id.id="guid";id.data.assign(mapId.begin(),mapId.end());Chunk file;file.id="file";file.data=utf16(L"Default.cdm");descriptor.children={header,id,file};refs.children={descriptor};root.children.push_back(refs);
    const auto styleBytes=root.encode();const auto ownedPath=(dir/L"StyleWithDefault.stp").wstring();write_file_atomic(ownedPath,styleBytes);write_file_atomic((dir/L"Default.cdm").wstring(),mapBytes);StyleDocument source;source.load(styleBytes);const StyleCatalogEntry owned{ownedPath,styleBytes};
    // Independently author the optional DMRF name for the direct OS oracle.
    // The product below still receives the original unnamed native input.
    auto namedRoot=root;auto& namedDescriptor=namedRoot.find("LIST","prrf")->children.at(0);put32(namedDescriptor.find("refh")->data,16,1|2|4|16);Chunk name;name.id="name";name.data=utf16(map.name());namedDescriptor.children.push_back(name);
    const auto namedStyleBytes=namedRoot.encode();
    StylePlayerSettings settings;settings.measures=8;settings.shape=StyleShape::Quiet;const auto expectedRoles=style_default_public_roles(namedStyleBytes,mapBytes,settings);
    const auto result=compose_style_player_segment(owned,std::nullopt,settings);SegmentDocument document;document.load(result.segment);
    require(document.length()==8*source.meter().beats*3072/source.meter().denominator,"Default-map Shape retains requested length");require(!document.chords().empty()&&!document.commands().empty(),"Default-map Shape persists generated Chord and Command events");
    require(result.style.bytes==styleBytes&&read_file(ownedPath)==styleBytes&&!source.dirty(),"Default-map Shape retains immutable owned Style bytes");require(result.maps.size()==1&&result.maps[0].bytes==mapBytes&&result.maps[0].reference.objectId==mapId,"Default-map Shape owns full source map matching public selection");
    const auto namedResult=compose_style_player_segment({ownedPath,namedStyleBytes},std::nullopt,settings);
    require(namedResult.style.bytes==namedStyleBytes&&namedResult.maps.size()==1&&namedResult.maps[0].bytes==mapBytes,"Named native default reference retains its complete owned Style and map");
    const auto native=Chunk::parse(result.segment);std::vector<Bytes> roles;for(const auto& track:native.find("LIST","trkl")->children){const auto h=track.find("trkh");Bytes role(h->data.begin(),h->data.begin()+16);role.resize(20);put32(role,16,read32(h->data,20));roles.push_back(std::move(role));}std::sort(roles.begin(),roles.end());require(roles==expectedRoles,"Every public generated track class and group persists");
    Framework host;host.open_style(ownedPath);host.open_chordmap((dir/L"Default.cdm").wstring());const auto index=host.adopt_composed_segment(result.segment);host.save_segment(index,(dir/L"default-map.sgp").wstring());host.save_project((dir/L"Default.pro").wstring());Framework restored;restored.open_project((dir/L"Default.pro").wstring());require(restored.document(0).save_bytes()==result.segment&&restored.playback_chordmaps(0).at(0).bytes==mapBytes,"Native Project restores composed map source and full tracks");
    const auto before=document.save_bytes();require(document.add_tempo(0,150)&&document.undo()&&document.save_bytes()==before&&document.redo(),"Default-map composition retains edit Undo Redo");
    auto noRef=root;noRef.children.erase(std::remove_if(noRef.children.begin(),noRef.children.end(),[](const Chunk& c){return c.type=="prrf";}),noRef.children.end());rejected([&]{compose_style_player_segment({ownedPath,noRef.encode()},std::nullopt,settings);},"Absent Style default is rejected without inventing map data");
    auto wrongRoot=Chunk::parse(mapBytes);wrongRoot.find("guid")->data[0]^=1;rejected([&]{compose_style_player_segment(owned,std::nullopt,settings,{},{{(dir/L"Default.cdm").wstring(),wrongRoot.encode()}});},"Default-map identity mismatch is rejected before composition");
    auto wrongName=namedRoot;wrongName.find("LIST","prrf")->children.at(0).find("name")->data=utf16(L"Different map");rejected([&]{compose_style_player_segment({ownedPath,wrongName.encode()},std::nullopt,settings);},"Default-map source name mismatch rejected without choosing another map");
    auto unnamedMap=Chunk::parse(mapBytes);std::fill(unnamedMap.find("perh")->data.begin(),unnamedMap.find("perh")->data.begin()+40,0);rejected([&]{compose_style_player_segment(owned,std::nullopt,settings,{},{{(dir/L"Default.cdm").wstring(),unnamedMap.encode()}});},"Default-map missing source name is rejected without inventing one");
    require(inputStyle==read_file(stylePath)&&mapBytes==read_file(mapPath)&&styleBytes==read_file(ownedPath)&&mapBytes==read_file((dir/L"Default.cdm").wstring()),"All source inputs remain immutable after success and rejection");
}
