void timeline_range_tests(const std::filesystem::path& dir){
    SegmentDocument d;d.add_tempo(768,90);d.add_tempo(1536,180);d.add_tempo(2304,100);d.add_note({900,384,16,60,90});d.add_note({1800,384,0,64,80});d.add_note({2304,384,0,67,70});const auto baseline=d.save_bytes();d.load(baseline);
    require(d.select_range({768,2304,3})&&d.save_bytes()==baseline&&!d.dirty(),"Shared range selection changes no document bytes");const auto clipboard=d.copy_range();auto decoded=decode_timeline_clipboard(clipboard);require(decoded.span==1536&&decoded.strips==3,"Shared clipboard retains selected strips and blank range bounds");
    require(sequence_notes(decoded.sequence).size()==2&&sequence_notes(decoded.sequence)[0].time==132&&sequence_notes(decoded.sequence)[0].channel==16,"Range excludes exclusive end and retains leading space plus DWORD PChannel");
    require(d.paste_range(clipboard,3840),"Shared Tempo Sequence merge");auto merged=d.save_bytes();require(d.notes().size()==5&&d.tempos().size()==6,"Merge applies both strips");require(d.undo()&&d.save_bytes()==baseline&&!d.dirty()&&!d.undo(),"One Undo restores both strips and checkpoint");require(d.redo()&&d.save_bytes()==merged&&!d.redo(),"One Redo restores complete range transaction");
    require(d.undo(),"Prepare redo preservation");auto corrupt=clipboard;corrupt.pop_back();require(!d.paste_range(corrupt,3840)&&d.save_bytes()==baseline&&!d.dirty()&&d.redo()&&d.save_bytes()==merged,"Malformed clipboard retains whole document and redo history");
    d.load(baseline);d.select_range({768,2304,3});require(!d.select_range({0,0,3})&&!d.select_range({0,d.length()+1,3})&&!d.select_range({0,768,8})&&d.selected_range().begin==768,"Invalid selection retains previous editor range");require(!d.paste_range(clipboard,INT32_MAX)&&d.save_bytes()==baseline&&!d.dirty(),"Paste overflow retains saved document");
    require(d.delete_range()&&d.notes().size()==1&&d.tempos().size()==2,"Shared delete retains end boundary and unrelated events");require(d.undo()&&d.save_bytes()==baseline&&!d.undo(),"Shared delete is one complete history transaction");
    d.load(baseline);d.select_range({768,2304,3});require(!d.paste_range(clipboard,768,true)&&d.notes().size()==3,"Identical overwrite is a no-op without duplicate MIDI events");require(d.save_bytes()==baseline&&!d.dirty()&&!d.undo(),"Overwrite same range preserves exact document and history");
    // Extended records with nonzero offset, controller, curve, unknown chunk.
    auto root=Chunk::parse(baseline);Chunk* seq=nullptr;for(auto& track:root.find("LIST","trkl")->children)if(is_sequence_track(track))seq=track.find("seqt");require(seq!=nullptr,"Sequence fixture present");
    Chunk ev;ev.id="evtl";ev.data.resize(4+48);put32(ev.data,0,24);put32(ev.data,4,800);put32(ev.data,8,384);put32(ev.data,12,16);ev.data[16]=100;ev.data[18]=0x90;ev.data[19]=60;ev.data[20]=90;ev.data[24]=0xaa;put32(ev.data,28,1000);ev.data[42]=0xb0;ev.data[43]=7;ev.data[44]=64;ev.data[48]=0xbb;
    Chunk curve;curve.id="curl";curve.data.resize(4+36);put32(curve.data,0,36);put32(curve.data,4,1200);put32(curve.data,8,384);put32(curve.data,16,16);curve.data[20]=10;curve.data[36]=0xcc;Chunk unknown;unknown.id="xSeq";unknown.data={7,8,9};seq->data=ev.encode();auto append=[&](const Bytes& b){seq->data.insert(seq->data.end(),b.begin(),b.end());};append(curve.encode());append(unknown.encode());const auto extended=root.encode();d.load(extended);d.select_range({768,1536,2});auto c=d.copy_range();const auto owned=c;require(d.paste_range(c,3072),"Extended MIDI and curve range merge");require(c==owned&&d.notes()[1].time==3204,"Clipboard ownership and signed offset preserved");auto after=Chunk::parse(d.save_bytes());const Chunk* out=nullptr;for(const auto& track:after.find("LIST","trkl")->children)if(is_sequence_track(track))out=track.find("seqt");auto items=out->data;auto unknownBytes=unknown.encode();require(std::count(items.begin(),items.end(),0xaa)==2&&std::count(items.begin(),items.end(),0xbb)==2&&std::count(items.begin(),items.end(),0xcc)==2,"Extended note controller curve bytes copied");require(std::search(items.begin(),items.end(),unknownBytes.begin(),unknownBytes.end())!=items.end(),"Destination unknown Sequence subchunk retained");require(d.undo()&&d.save_bytes()==extended&&!d.undo(),"Extended cross-strip operation restores exact original bytes");

    SegmentDocument fresh;fresh.select_range({0,768,2});require(fresh.paste_range(c,3072)&&fresh.notes().size()==1&&fresh.notes()[0].time==3204,"Empty Sequence accepts complete extended event and curve strides");require(fresh.undo()&&!fresh.dirty(),"Empty destination transaction restores saved checkpoint");
    SegmentDocument empty;empty.select_range({0,768,2});auto emptyCopy=empty.copy_range();auto emptyBytes=empty.save_bytes();require(!empty.paste_range(emptyCopy,1536)&&!empty.paste_range(emptyCopy,1536,true)&&empty.save_bytes()==emptyBytes&&!empty.dirty()&&!empty.undo(),"Empty selected strip paste does not manufacture a track or history");
    auto malformed=decode_timeline_clipboard(c);for(size_t pos=0;pos<malformed.sequence.size();pos+=8+read32(malformed.sequence,pos+4)+(read32(malformed.sequence,pos+4)&1))if(std::memcmp(malformed.sequence.data()+pos,"curl",4)==0)put32(malformed.sequence,pos+16,INT32_MAX);
    d.select_range({768,1536,3});auto allClipboard=decode_timeline_clipboard(d.copy_range());malformed.strips=3;malformed.tempo=allClipboard.tempo;fresh.select_range({0,768,3});auto savedFresh=fresh.save_bytes();require(!fresh.paste_range(encode_timeline_clipboard(malformed),3072)&&fresh.save_bytes()==savedFresh&&!fresh.dirty()&&!fresh.undo(),"Curve overrun rejects both strip edits atomically including history");
    auto incompatible=decode_timeline_clipboard(c);d.load(baseline);d.select_range({768,1536,2});auto beforeMismatch=d.save_bytes();require(!d.paste_range(encode_timeline_clipboard(incompatible),3072)&&d.save_bytes()==beforeMismatch&&!d.dirty()&&!d.undo(),"Existing different strides reject without truncating extensions");
    auto grouped=Chunk::parse(extended);auto second=sequence_track();put32(second.find("trkh")->data,20,2);put32(second.find("trkh")->data,16,99);grouped.find("LIST","trkl")->children.push_back(second);d.load(grouped.encode());d.select_track_group(2);d.select_range({0,768,2});require(d.paste_range(c,3072)&&d.notes().size()==1,"Shared range follows selected group and track context");d.select_track_group(1);require(d.notes().size()==1&&d.notes()[0].time==900,"Other group Sequence is retained unchanged");
    Framework host;auto index=host.new_segment();host.document(index).load(extended);host.document(index).select_range({768,1536,2});require(host.document(index).paste_range(c,3072),"Framework owned shared range editing");auto final=host.document(index).save_bytes();auto folder=dir/L"TimelineProject";std::filesystem::create_directories(folder);host.save_segment(index,(folder/L"Range.sgp").wstring());host.save_project((folder/L"TimelineProject.pro").wstring());Framework reload;reload.open_project((folder/L"TimelineProject.pro").wstring());require(reload.documents().size()==1&&reload.document(0).save_bytes()==final&&!reload.document(0).dirty(),"Native Project restores complete range transaction");
    // Relocation uses absolute destination clocks, including overlapping ranges.
    d.load(baseline);d.select_range({768,2304,3});
    require(d.move_range(1536)&&d.notes().size()==3&&d.notes()[0].time==1668&&d.notes()[1].time==2304&&d.notes()[2].time==2568,"Overlapping move relocates selected notes once and retains end-boundary note");
    require(d.tempos().size()==3&&d.tempos()[1].time==1536&&d.tempos()[1].bpm==90&&d.tempos()[2].time==2304&&d.tempos()[2].bpm==180,"Move uses existing Tempo equal-clock replacement contract");
    auto moved=d.save_bytes();require(d.selected_range().begin==1536&&d.selected_range().end==3072&&d.undo()&&d.save_bytes()==baseline&&!d.dirty()&&!d.undo(),"Move selects destination and one Undo restores all strips");
    require(d.redo()&&d.save_bytes()==moved&&!d.redo(),"One Redo restores move without intermediate deletion");
    d.undo();d.select_range({768,2304,3});auto selected=d.selected_range();
    require(!d.move_range(768)&&!d.move_range(-1)&&!d.move_range(INT32_MAX)&&!d.move_range(d.length()-1535)&&d.save_bytes()==baseline&&!d.dirty()&&d.selected_range().begin==selected.begin&&d.selected_range().end==selected.end&&d.redo()&&d.save_bytes()==moved,"No-op invalid and overflowing move retain selection checkpoint and redo");
    d.load(baseline);d.select_range({768,2304,3});require(d.move_range(0)&&d.notes()[0].time==132&&d.notes()[1].time==1032&&d.notes()[2].time==2304,"Backward move retains blank prefix and unselected notes");
    require(d.undo()&&d.save_bytes()==baseline&&!d.undo(),"Backward move restores exact bytes in one edit");
    d.load(baseline);d.select_range({768,2304,2});auto untouched=d.tempos();require(d.move_range(d.length()-1536)&&d.notes().size()==3&&d.notes().back().time==d.length()-504&&d.tempos().size()==untouched.size()&&d.tempos()[1].time==untouched[1].time,"Sequence-only move accepts exact end boundary and leaves Tempo alone");
    SegmentDocument crossing;crossing.add_note({900,2000,16,60,90});auto crossingSaved=crossing.save_bytes();crossing.load(crossingSaved);crossing.select_range({768,1536,3});require(!crossing.move_range(crossing.length()-768)&&crossing.save_bytes()==crossingSaved&&!crossing.dirty()&&!crossing.undo(),"Note duration overrun rejects after private deletion without cross-strip mutation");
    empty.select_range({768,1536,3});require(!empty.move_range(1536)&&empty.save_bytes()==emptyBytes&&!empty.dirty()&&!empty.undo(),"Empty range move retains checkpoint without manufacturing tracks");
    d.load(extended);d.select_range({768,1536,2});require(d.move_range(1536)&&d.notes().size()==1&&d.notes()[0].time==1668&&d.notes()[0].channel==16,"Move relocates extended note with signed offset and DWORD channel");
    require(d.undo()&&d.save_bytes()==extended&&!d.undo(),"Extended controller curve and opaque data move restores exact bytes");
    host.document(index).select_range({3072,3840,2});require(host.document(index).move_range(4608),"Framework-owned Timeline move");auto movedFinal=host.document(index).save_bytes();host.save_segment(index,(folder/L"Range.sgp").wstring());host.save_project((folder/L"TimelineProject.pro").wstring());Framework movedReload;movedReload.open_project((folder/L"TimelineProject.pro").wstring());require(movedReload.documents().size()==1&&movedReload.document(0).save_bytes()==movedFinal&&!movedReload.document(0).dirty(),"Native Project restores complete relocation");

    SegmentDocument lyrics;lyrics.add_tempo(768,90);lyrics.add_note({900,384,16,60,90});lyrics.add_lyric({800,100,8,L"pickup relation"});lyrics.add_lyric({1000,4000,4,L"Unicode \u6b4c\u8a5e"});lyrics.add_lyric({1536,3072,16,L"end"});auto lyricSaved=lyrics.save_bytes();lyrics.load(lyricSaved);
    require(lyrics.select_range({768,1536,7})&&lyrics.move_range(2304),"Three-strip range moves Lyric with Tempo and Sequence atomically");auto lyricMoved=lyrics.save_bytes();auto le=lyrics.lyrics();require(le.size()==3&&le[0].physical==1536&&le[1].physical==2336&&le[1].logical==1636&&le[2].physical==2536&&le[2].logical==5536&&le[2].timing==4,"Lyric movement preserves independent clock delta, timing and exclusive-end event");
    require(lyrics.undo()&&lyrics.save_bytes()==lyricSaved&&!lyrics.dirty()&&!lyrics.undo()&&lyrics.redo()&&lyrics.save_bytes()==lyricMoved&&!lyrics.redo(),"Three-strip move has one exact Undo and Redo");lyrics.undo();lyrics.select_range({768,1536,7});const auto lyricClip=lyrics.copy_range();
    require(!lyrics.move_range(0)&&lyrics.save_bytes()==lyricSaved&&!lyrics.dirty()&&lyrics.redo()&&lyrics.save_bytes()==lyricMoved,"Negative translated logical clock rejects all strips and preserves redo");lyrics.load(lyricSaved);lyrics.select_range({768,1536,7});auto brokenLyric=decode_timeline_clipboard(lyricClip);brokenLyric.lyric.pop_back();require(!lyrics.paste_range(encode_timeline_clipboard(brokenLyric),2304)&&lyrics.save_bytes()==lyricSaved&&!lyrics.dirty()&&!lyrics.undo(),"Corrupt Lyric clipboard rejects Tempo and Sequence before mutation");
    require(!lyrics.paste_range(lyricClip,lyrics.length()-768)&&lyrics.save_bytes()==lyricSaved&&!lyrics.dirty(),"Logical clock beyond Segment end rejects shared paste");
    lyrics.select_range({768,1536,4});require(!lyrics.paste_range(lyrics.copy_range(),768,true)&&lyrics.save_bytes()==lyricSaved&&!lyrics.undo(),"Identical Lyric overwrite retains exact bytes and history");require(lyrics.delete_range()&&lyrics.lyrics().size()==1&&lyrics.lyrics()[0].physical==1536&&lyrics.undo()&&lyrics.save_bytes()==lyricSaved,"Lyric range deletion preserves exclusive end and whole history");
    SegmentDocument emptyLyric;emptyLyric.select_range({0,768,4});auto emptyLyricBytes=emptyLyric.save_bytes(),emptyLyricClip=emptyLyric.copy_range();require(!emptyLyric.paste_range(emptyLyricClip,1536)&&!emptyLyric.paste_range(emptyLyricClip,1536,true)&&emptyLyric.save_bytes()==emptyLyricBytes&&!emptyLyric.undo(),"Empty Lyric range creates no track on merge or overwrite");
    auto lyricOnlyClip=decode_timeline_clipboard(lyricClip);lyricOnlyClip.strips=4;lyricOnlyClip.tempo.clear();lyricOnlyClip.sequence.clear();emptyLyric.select_range({0,768,4});require(emptyLyric.paste_range(encode_timeline_clipboard(lyricOnlyClip),2304)&&emptyLyric.lyrics().size()==2,"Empty destination accepts owned Lyric entries");
    auto lr=Chunk::parse(lyricSaved);auto lx=lyric_track();put32(lx.find("trkh")->data,20,2);add_lyric_event(lx,{800,900,16,L"group2"});lr.find("LIST","trkl")->children.push_back(lx);auto ln=lyric_track();add_lyric_event(ln,{800,1000,16,L"nth"});lr.find("LIST","trkl")->children.push_back(ln);lyrics.load(lr.encode());require(lyrics.select_range({768,1536,4,1})&&lyrics.move_range(2304)&&lyrics.lyrics(1)[0].physical==2336&&lyrics.lyrics(0)[0].physical==800,"Explicit selected-group nth Lyric track isolates range movement");lyrics.select_track_group(2);require(lyrics.lyrics()[0].physical==800&&lyrics.select_range({768,1536,4})&&lyrics.move_range(2304)&&lyrics.lyrics()[0].logical==2436,"Lyric range honors group selection");require(!lyrics.select_range({0,768,4,999})&&lyrics.selected_range().begin==2304,"Invalid Lyric track retains range selection");
    Framework lyricHost;auto li=lyricHost.new_segment();lyricHost.document(li).load(lyricMoved);auto lf=dir/L"LyricRangeProject";std::filesystem::create_directories(lf);lyricHost.save_segment(li,(lf/L"Lyrics.sgp").wstring());lyricHost.save_project((lf/L"LyricRangeProject.pro").wstring());Framework lyricReload;lyricReload.open_project((lf/L"LyricRangeProject.pro").wstring());require(lyricReload.document(0).save_bytes()==lyricMoved&&!lyricReload.document(0).dirty(),"Native Project restores complete Lyric range edit");

    auto extLyrics=lyric_track();add_lyric_event(extLyrics,{800,1600,8,L"extended"});auto listLyrics=extLyrics.find("LIST","lyrt")->find("LIST","lyrl");auto& entryLyrics=listLyrics->children[0];entryLyrics.find("lyrh")->data.insert(entryLyrics.find("lyrh")->data.end(),{0xaa,0xbb});entryLyrics.find("lyrn")->data.insert(entryLyrics.find("lyrn")->data.end(),{0x44,0x55});Chunk opaqueLyric;opaqueLyric.id="xLyr";opaqueLyric.data={1,2,3};entryLyrics.children.push_back(opaqueLyric);auto extCopy=copy_lyric_range(extLyrics,768,1536);auto targetLyrics=lyric_track();require(paste_lyric_range(targetLyrics,extCopy,2304,768,false,12288),"Lyric range transports extended owned entry");auto targetEntry=targetLyrics.find("LIST","lyrt")->find("LIST","lyrl")->children[0];auto expectedEntry=entryLyrics;put32(expectedEntry.find("lyrh")->data,8,3136);put32(expectedEntry.find("lyrh")->data,12,2336);require(targetEntry.encode()==expectedEntry.encode(),"Range changes only independent clocks, retaining header extension, Unicode tail and opaque entry chunk");
}
