void tool_graph_tests(const std::filesystem::path& dir){
    ToolGraphDocument d;const auto empty=d.save_bytes();require(d.tools().empty()&&!d.dirty(),"Empty ToolGraph valid saved checkpoint");
    std::array<std::uint8_t,16> a{},b{};a[0]=1;b[0]=2;
    require(d.add_tool(a,{0,16,65535,0xfffffffb})&&d.add_tool(b,{}),"Distinct Tool instances with DWORD channels and empty mapping");
    require(d.tools()[0].channels==std::vector<std::uint32_t>({0,16,65535,0xfffffffb})&&!d.tools()[1].payload,"Typed channels retain full DWORD; optional tool data absent");
    auto fixture=Chunk::parse(d.save_bytes());auto list=fixture.find("LIST","toll");Chunk opaque;opaque.id="oddx";opaque.data={9};opaque.padding=0x5a;list->children.insert(list->children.begin()+1,opaque);
    auto& h=list->children[0].find("tolh")->data;put32(h,16,0xffffffff);h.push_back(0x31);h.push_back(0x32);Chunk payload;payload.id="data";payload.data={1,2,3};payload.padding=0x7b;list->children[0].children.push_back(payload);
    const auto input=fixture.encode();d.load(input);require(d.save_bytes()==input&&d.tools()[0].index==-1&&d.tools()[0].payload->encode()==payload.encode(),"Signed index extension data unknown sibling padding exact load");
    require(d.set_channels(0,{17,1024}),"Channel mapping edit");auto changed=Chunk::parse(d.save_bytes());const auto changedHeader=changed.find("LIST","toll")->children[0].find("tolh")->data;require(changedHeader.size()==42&&changedHeader[40]==0x31&&changedHeader[41]==0x32&&d.tools()[0].index==-1&&d.tools()[0].payload->encode()==payload.encode(),"Channel edit retains extended header signed index and payload");
    require(d.undo()&&d.save_bytes()==input&&!d.dirty(),"Channel Undo exact fixture saved checkpoint");require(d.redo()&&d.tools()[0].channels==std::vector<std::uint32_t>({17,1024}),"Channel Redo restore mappings");
    const auto beforeMove=d.save_bytes();require(d.move_tool(0,1)&&d.tools()[0].classId==b&&d.tools()[1].classId==a&&d.tools()[0].index==0&&d.tools()[1].index==1,"Move updates tool ordering and indexes together");changed=Chunk::parse(d.save_bytes());require(changed.find("LIST","toll")->children[1].encode()==opaque.encode()&&d.tools()[1].payload->encode()==payload.encode(),"Move retains design sibling slot and tool payload");require(d.undo()&&d.save_bytes()==beforeMove,"Move Undo restores signed indexes and mapping");d.redo();
    require(!d.move_tool(0,2)&&!d.set_channels(2,{1})&&!d.remove_tool(2),"Invalid tool indexes reject");const auto beforeBad=d.save_bytes();
    auto bad=fixture;put32(bad.find("LIST","toll")->children[0].find("tolh")->data,20,0xffffffff);rejected([&]{d.load(bad.encode());},"Count overflow/truncation rejected before allocation");require(d.save_bytes()==beforeBad&&d.undo(),"Rejected ToolGraph load keeps document and history");d.redo();
    bad=fixture;bad.find("LIST","toll")->children[0].find("tolh")->data.resize(31);rejected([&]{d.load(bad.encode());},"Short Tool header rejected");
    bad=fixture;bad.find("LIST","toll")->children[0].children.push_back(payload);rejected([&]{d.load(bad.encode());},"Ambiguous matching tool data rejected");
    bad=fixture;bad.find("LIST","toll")->children[0].children.push_back(*bad.find("LIST","toll")->children[0].find("tolh"));rejected([&]{d.load(bad.encode());},"Duplicate Tool header rejected");
    require(d.set_name(L"ToolGraph Unicode \x65e5\x672c"),"Graph Unicode name edit");const auto named=d.save_bytes();require(!d.set_name(std::wstring(L"a\0b",3))&&d.save_bytes()==named,"Invalid graph name atomic");
    require(d.remove_tool(0)&&d.tools().size()==1&&d.tools()[0].index==0,"Delete tool updates remaining order");require(d.undo()&&d.save_bytes()==named,"Delete Undo restores full graph");
    const auto scenario=dir/L"Scenario";std::filesystem::create_directories(scenario);const auto graph=scenario/L"Graph.tgp",project=scenario/L"Scenario.pro";d.save(graph.wstring());ToolGraphDocument reload;reload.load(read_file(graph.wstring()));require(!d.dirty()&&reload.save_bytes()==named,"ToolGraph disk restore and checkpoint");
    SegmentDocument embedded;const auto cleanSegment=embedded.save_bytes();require(embedded.tool_graph().empty(),"Fresh Segment has no ToolGraph");require(embedded.set_tool_graph(named)&&embedded.tool_graph()==named,"Segment owns exact graph snapshot");const auto graphSegment=embedded.save_bytes();require(embedded.undo()&&embedded.save_bytes()==cleanSegment&&embedded.redo()&&embedded.save_bytes()==graphSegment,"Embedded graph Segment Undo/Redo");require(!embedded.set_tool_graph(named)&&embedded.save_bytes()==graphSegment,"Identical embedding is history no-op");require(embedded.remove_tool_graph()&&embedded.tool_graph().empty()&&embedded.undo()&&embedded.save_bytes()==graphSegment,"Remove embedded graph Undo restores full snapshot");auto broken=Chunk::parse(named);put32(broken.find("LIST","toll")->children[0].find("tolh")->data,20,0xffffffff);rejected([&]{embedded.set_tool_graph(broken.encode());},"Malformed embedded edit rejected");require(embedded.save_bytes()==graphSegment&&embedded.undo()&&embedded.redo(),"Rejected embedded edit keeps bytes and history");auto duplicateGraph=Chunk::parse(graphSegment);duplicateGraph.children.push_back(Chunk::parse(named));rejected([&]{embedded.load(duplicateGraph.encode());},"Duplicate embedded graph load rejected");require(embedded.save_bytes()==graphSegment,"Rejected embedded load leaves document unchanged");
    const auto embeddedDir=dir/L"Embedded";std::filesystem::create_directories(embeddedDir);const auto embeddedPath=embeddedDir/L"Song.sgp",embeddedProject=embeddedDir/L"Embedded.pro";embedded.save(embeddedPath.wstring());Framework embeddedHost;embeddedHost.open_segment(embeddedPath.wstring());embeddedHost.save_project(embeddedProject.wstring());Framework embeddedReload;embeddedReload.open_project(embeddedProject.wstring());require(embeddedReload.documents().size()==1&&embeddedReload.tool_graphs().empty()&&embeddedReload.document(0).tool_graph()==named,"Native Project restores embedded graph without mandatory standalone owner");
    Framework host;const auto index=host.open_tool_graph(graph.wstring());require(index==0&&host.open_tool_graph(graph.wstring())==0&&host.tool_graphs().size()==1,"Framework one ToolGraph owner per path");host.save_project(project.wstring());const auto native=Chunk::parse(read_file(project.wstring()));size_t entries=0;for(const auto& c:native.children)if(c.id=="LIST"&&c.type=="file"){++entries;require(decode_utf16(c.find("LIST","UNFO")->find("rnam")->data)==L"Graph.tgr","Native runtime Graph metadata .tgr");}require(entries==1&&!host.dirty(),"Native Project saved owns ToolGraph");Framework restored;restored.open_project(project.wstring());require(restored.tool_graphs().size()==1&&restored.tool_graph_document(0).save_bytes()==named&&!restored.dirty(),"Native Project reload owns tool order mappings payload");
    const auto oldProject=read_file(project.wstring());host.tool_graph_document(0).set_name(L"Main graph");rejected([&]{host.save_project(project.wstring());},"Dirty graph blocks Project replacement");require(read_file(project.wstring())==oldProject,"Failed graph Project save retains destination");host.save_tool_graph(0,graph.wstring());host.save_project(project.wstring());Framework edited;edited.open_project(project.wstring());require(edited.tool_graph_document(0).name()==L"Main graph","Saved graph metadata journal and name restored");
    const auto second=host.new_tool_graph();host.save_tool_graph(second,(scenario/L"Second.tgp").wstring());const auto firstBytes=host.tool_graph_document(0).save_bytes();rejected([&]{host.save_tool_graph(0,(scenario/L"Second.tgp").wstring());},"Another Graph destination rejected");require(host.tool_graph_document(0).save_bytes()==firstBytes,"Failed Save As preserves graph");host.new_project();require(host.tool_graphs().empty(),"New Project clears Graph ownership");
}
