void wave_pcm_tests(const std::filesystem::path& dir,const std::wstring& wavePath){
    const auto original=read_file(wavePath);auto root=Chunk::parse(original);auto& fmt=root.find("fmt ")->data;fmt[2]=2;fmt[3]=0;put32(fmt,8,44100*4);fmt[12]=4;fmt[13]=0;auto& pcm=root.find("data")->data;pcm.resize(64);for(size_t i=0;i<pcm.size();++i)pcm[i]=static_cast<std::uint8_t>(i+1);
    auto& cue=root.find("cue ")->data;put32(cue,8,2);put32(cue,24,2);put32(cue,32,12);put32(cue,48,12);auto labels=root.find("LIST","adtl");put32(labels->children[0].data,4,10);put32(labels->children[1].data,4,4);
    auto& wsmp=root.find("wsmp")->data;wsmp.resize(55,0);put32(wsmp,16,2);for(size_t i=0;i<2;++i){const auto p=20+i*16;put32(wsmp,p,16);put32(wsmp,p+4,0);put32(wsmp,p+8,i?4:2);put32(wsmp,p+12,i?4:10);}wsmp[52]=0xa1;wsmp[53]=0xa2;wsmp[54]=0xa3;
    auto& smpl=root.find("smpl")->data;smpl.resize(86,0);put32(smpl,28,2);put32(smpl,32,2);for(size_t i=0;i<2;++i){const auto p=36+i*24;put32(smpl,p,21+static_cast<unsigned>(i));put32(smpl,p+4,1);put32(smpl,p+8,4);put32(smpl,p+12,i?7:10);put32(smpl,p+16,0x80000000u);put32(smpl,p+20,3);}smpl[84]=0xb1;smpl[85]=0xb2;
    const auto sourcePcm=pcm;Chunk fact;fact.id="fact";fact.data={16,0,0,0,0xc1};fact.padding=0xe2;root.children.push_back(fact);Chunk opaque;opaque.id="zzzz";opaque.data={1,2,3};opaque.padding=0xa5;root.children.push_back(opaque);
    const auto before=root.encode();WaveDocument doc;doc.load(before);const auto clip=doc.copy_pcm(4,8);const auto clipRoot=Chunk::parse(clip);require(clipRoot.children.size()==2&&clipRoot.find("data")->data==Bytes(sourcePcm.begin()+16,sourcePcm.begin()+32)&&doc.save_bytes()==before&&!doc.dirty()&&!doc.undo(),"PCM copy preserves interleaved complete frames and does not change document history");
    require(doc.erase_pcm(4,8)&&doc.format().frames==12,"PCM delete closes selected frame gap");auto expected=root;auto& e=expected.find("data")->data;e.erase(e.begin()+16,e.begin()+32);auto& ec=expected.find("cue ")->data;put32(ec,32,8);put32(ec,48,8);put32(expected.find("LIST","adtl")->children[0].data,4,6);auto& ew=expected.find("wsmp")->data;ew.erase(ew.begin()+36,ew.begin()+52);put32(ew,16,1);put32(ew,32,6);auto& es=expected.find("smpl")->data;es.erase(es.begin()+60,es.begin()+84);put32(es,28,1);put32(es,48,6);put32(expected.find("fact")->data,0,12);const auto deleted=doc.save_bytes();require(deleted==expected.encode(),"PCM delete maps cues labelled lengths WSMP half-open SMPL inclusive loops and fact; tails unknown identity padding exact");
    require(doc.undo()&&doc.save_bytes()==before&&!doc.dirty(),"PCM deletion is one complete reversible transaction");require(!doc.erase_pcm(4,4)&&doc.save_bytes()==before,"Empty PCM deletion is no-op");rejected([&]{doc.erase_pcm(8,4);},"Reversed PCM range rejected");rejected([&]{doc.erase_pcm(0,17);},"Out-of-bounds PCM range rejected");rejected([&]{doc.copy_pcm(0,17);},"Invalid PCM copy rejected");require(doc.redo()&&doc.save_bytes()==deleted,"Invalid PCM requests retain pending Redo");
    require(doc.paste_pcm(3,clip)&&doc.format().frames==16,"PCM paste inserts material and retains all existing audio");auto& ep=expected.find("data")->data;ep.insert(ep.begin()+12,sourcePcm.begin()+16,sourcePcm.begin()+32);put32(expected.find("cue ")->data,32,12);put32(expected.find("cue ")->data,48,12);put32(expected.find("LIST","adtl")->children[0].data,4,10);put32(expected.find("wsmp")->data,32,10);put32(expected.find("smpl")->data,44,8);put32(expected.find("smpl")->data,48,10);put32(expected.find("fact")->data,0,16);const auto pasted=doc.save_bytes();require(pasted==expected.encode(),"PCM insertion expands containing ranges shifts later cues and preserves SMPL fraction repeat and sampler tail");
    require(doc.undo()&&doc.save_bytes()==deleted&&doc.redo()&&doc.save_bytes()==pasted,"PCM paste has independent complete Undo Redo");auto mismatch=clipRoot;mismatch.find("fmt ")->data[2]=1;mismatch.find("fmt ")->data[12]=2;put32(mismatch.find("fmt ")->data,8,44100*2);rejected([&]{doc.paste_pcm(0,mismatch.encode());},"Different channel layout rejects rather than corrupting PCM");rejected([&]{doc.paste_pcm(17,clip);},"PCM insertion outside frames rejected");rejected([&]{doc.paste_pcm(0,{1,2,3});},"Malformed Wave clipboard rejected");require(doc.save_bytes()==pasted,"Rejected paste retains PCM metadata and history");
    WaveDocument cow;cow.load(original);const auto cowCopy=cow.copy_pcm(1000,2000);require(cow.erase_pcm(1000,2000)&&cow.format().frames==62868,"Original WVP PCM deletion adjusts full-wave labelled take lengths");require(cow.undo()&&cow.save_bytes()==original&&cow.paste_pcm(1000,cowCopy)&&cow.format().frames==64868,"Original WVP copy inserts without replacing existing selection");
    auto malformed=root;put32(malformed.find("cue ")->data,0,999);WaveDocument invalid;invalid.load(malformed.encode());const auto bad=invalid.save_bytes();rejected([&]{invalid.erase_pcm(4,8);},"Malformed position metadata refuses transactional PCM edit");require(invalid.save_bytes()==bad&&!invalid.dirty()&&!invalid.undo(),"Failed metadata preflight retains entire Wave and history");
    const auto projectDir=dir/L"Pcm";std::filesystem::create_directories(projectDir);write_file_atomic((projectDir/L"Edited.wvp").wstring(),pasted);Framework host;host.open_wave((projectDir/L"Edited.wvp").wstring());host.save_project((projectDir/L"Pcm.pro").wstring());Framework reload;reload.open_project((projectDir/L"Pcm.pro").wstring());require(reload.waves().size()==1&&reload.wave_document(0).save_bytes()==pasted,"Native Project restores PCM and all position metadata");write_file_atomic((dir/L"Before.wvp").wstring(),before);write_file_atomic((dir/L"Deleted.wvp").wstring(),deleted);write_file_atomic((dir/L"Pasted.wvp").wstring(),pasted);write_file_atomic((dir/L"Clipboard.wav").wstring(),clip);
}
void wave_sample_loop_tests(const std::filesystem::path& dir,const std::wstring& wavePath){
    const auto source=read_file(wavePath);WaveDocument doc;doc.load(source);
    require(doc.sample_loops().empty()&&!doc.set_sample_loops({})&&doc.save_bytes()==source&&!doc.undo(),"Empty Wave default loop no-op preserves exact source and history");
    const std::vector<WaveSampleLoop> loops{{0,1000,5000},{1,63000,868}};
    require(doc.set_sample_loops(loops)&&doc.sample_loops()==loops&&doc.dirty(),"Owned Wave WSMP default loops support forward and loop-release with frame-end boundary");
    auto expected=Chunk::parse(source);auto& b=expected.find("wsmp")->data;put32(b,16,2);b.resize(52);for(size_t i=0;i<loops.size();++i){const auto at=20+i*16;put32(b,at,16);put32(b,at+4,loops[i].type);put32(b,at+8,loops[i].start);put32(b,at+12,loops[i].length);}
    const auto changed=doc.save_bytes();require(changed==expected.encode(),"Wave sample loop edit changes only WSMP; PCM independent SMPL identity and Producer chunks exact");
    require(!doc.set_sample_loops(loops)&&doc.save_bytes()==changed,"Wave loop no-op preserves typed state");
    require(doc.undo()&&doc.save_bytes()==source&&!doc.dirty()&&!doc.undo(),"Wave multi-loop Apply creates one complete Undo transaction");
    for(const auto value:std::vector<WaveSampleLoop>{{2,0,1},{0,0,0},{0,63868,1},{0,UINT32_MAX,UINT32_MAX}}){bool refused=false;try{doc.set_sample_loops({value});}catch(const std::exception&){refused=true;}require(refused&&doc.save_bytes()==source&&!doc.dirty(),"Invalid Wave loop rejects before document/dirty mutation");}
    require(doc.redo()&&doc.save_bytes()==changed,"Invalid loop attempts preserve pending Redo");
    require(doc.set_sample_loops({})&&doc.sample_loops().empty()&&doc.undo()&&doc.save_bytes()==changed,"Disable default loops and Undo restore exact enabled configuration");
    auto extended=Chunk::parse(source);auto& ext=extended.find("wsmp")->data;ext.insert(ext.begin()+20,{0xa1,0xa2,0xa3,0xa4});put32(ext,0,24);put32(ext,16,1);ext.resize(44);put32(ext,24,20);put32(ext,28,0);put32(ext,32,10);put32(ext,36,20);ext[40]=0xc1;ext[41]=0xc2;ext[42]=0xc3;ext[43]=0xc4;ext.insert(ext.end(),{0xd1,0xd2,0xd3});extended.find("wsmp")->padding=0x79;const auto opaque=extended.encode();doc.load(opaque);
    require(doc.sample_loops()==std::vector<WaveSampleLoop>{{0,10,20}},"Extended WSMP header and variable loop stride decoded");
    require(doc.set_sample_loops({{1,30,40},{0,100,200}}),"Existing extended loop edited and new standard loop appended");
    auto exact=extended;auto& xb=exact.find("wsmp")->data;put32(xb,16,2);put32(xb,28,1);put32(xb,32,30);put32(xb,36,40);Bytes added(16);put32(added,0,16);put32(added,8,100);put32(added,12,200);xb.insert(xb.begin()+44,added.begin(),added.end());require(doc.save_bytes()==exact.encode(),"Wave loop header/record extensions tail and odd padding preserved exactly");
    require(doc.undo()&&doc.save_bytes()==opaque&&!doc.dirty()&&doc.redo()&&doc.save_bytes()==exact.encode(),"Extended sample loop UndoRedo preserves whole document");
    const auto beforeRemove=doc.save_bytes();auto removed=exact;auto& rb=removed.find("wsmp")->data;rb.erase(rb.begin()+24,rb.begin()+44);put32(rb,16,1);require(doc.remove_sample_loop(0)&&doc.save_bytes()==removed.encode()&&doc.sample_loops()==std::vector<WaveSampleLoop>{{0,100,200}},"Selected Wave loop removal preserves remaining record bytes and opaque tail");require(!doc.remove_sample_loop(9)&&doc.save_bytes()==removed.encode()&&doc.undo()&&doc.save_bytes()==beforeRemove,"Out-of-range removal no-op retains exact single Undo transaction");
    auto malformed=extended;put32(malformed.find("wsmp")->data,24,UINT32_MAX);doc.load(malformed.encode());const auto bad=doc.save_bytes();bool refused=false;try{doc.set_sample_loops({{0,0,1}});}catch(const std::exception&){refused=true;}require(refused&&doc.save_bytes()==bad&&!doc.dirty()&&!doc.undo(),"Malformed WSMP stride edit rejected atomically without erasing source");
    auto bare=Chunk::parse(source);bare.children.erase(std::remove_if(bare.children.begin(),bare.children.end(),[](const Chunk& c){return c.id=="wsmp";}),bare.children.end());doc.load(bare.encode());require(doc.set_sample_loops({{0,0,1}})&&doc.sample_loops()[0].length==1&&doc.root_note()==60,"Wave without WSMP gains typed default header preserving root and one-frame loop");
    auto compressed=Chunk::parse(source);compressed.find("fmt ")->data[0]=2;doc.load(compressed.encode());const auto prior=doc.save_bytes();refused=false;try{doc.set_sample_loops({{0,0,1}});}catch(const std::exception&){refused=true;}require(refused&&doc.save_bytes()==prior&&!doc.undo(),"Compressed Wave default loop authoring refuses ambiguous decoded frame layout without mutation");
    const auto folder=dir/L"WaveSampleLoops";std::filesystem::create_directories(folder);doc.load(source);doc.set_sample_loops(loops);doc.save((folder/L"SfxCow.wvp").wstring());WaveDocument loaded;loaded.load(read_file((folder/L"SfxCow.wvp").wstring()));require(loaded.sample_loops()==loops&&loaded.save_bytes()==changed&&!loaded.dirty(),"Separate Wave document restores typed default loops and all source PCM");
    Framework host;host.new_project();const auto wave=host.open_wave((folder/L"SfxCow.wvp").wstring());host.save_project((folder/L"WaveSampleLoops.pro").wstring());Framework restored;restored.open_project((folder/L"WaveSampleLoops.pro").wstring());require(restored.waves().size()==1&&restored.wave_document(0).sample_loops()==loops&&restored.wave_document(0).save_bytes()==changed,"Native Project restores standalone owned Wave default sampler loops");
}
void wave_document_tests(const std::filesystem::path& dir,const std::wstring& wavePath,const std::wstring& segmentPath){
    const auto base=dir/L"wave-document";std::filesystem::create_directories(base);const auto original=read_file(wavePath);WaveDocument d;d.load(original);const auto f=d.format();
    require(d.save_bytes()==original&&!d.dirty(),"Original WVP loaded without dropping Producer/sampler/cue chunks");require(f.tag==1&&f.channels==1&&f.sampleRate==44100&&f.bits==16&&f.frames==63868,"Original independent PCM frame count and format");require(d.identity().has_value()&&d.root_note()==60,"Original Wave identity and unity note");
    const auto name=d.name();require(d.set_properties(L"Cow edited",64),"Wave name and root note edit");const auto edited=d.save_bytes();auto expected=Chunk::parse(original);expected.find("wsmp")->data[4]=64;put32(expected.find("smpl")->data,12,64);expected.find("LIST","INFO")->find("INAM")->data={'C','o','w',' ','e','d','i','t','e','d',0};require(edited==expected.encode(),"Only INFO name and both original sampler unity fields change");require(!d.set_properties(L"Cow edited",64)&&d.save_bytes()==edited,"Identical Wave properties do not create edits");require(!d.set_properties(L"Invalid",128)&&d.save_bytes()==edited,"Invalid combined properties retain whole document");require(d.undo()&&d.save_bytes()==original&&!d.dirty(),"Single Undo restores both fields and saved checkpoint");require(!d.undo(),"Combined Apply is one history step");require(d.redo()&&d.save_bytes()==edited,"Single Redo restores whole properties edit");d.save((base/L"edited.wvp").wstring());require(!d.dirty()&&read_file((base/L"edited.wvp").wstring())==edited,"Wave disk save clears checkpoint");WaveDocument restored;restored.load(read_file((base/L"edited.wvp").wstring()));require(restored.name()==L"Cow edited"&&restored.root_note()==64&&restored.format().frames==63868,"Separate document reload restores typed fields and samples");
    auto invalid=Chunk::parse(original);invalid.find("fmt ")->data.resize(15);bool rejected=false;try{d.load(invalid.encode());}catch(const std::exception&){rejected=true;}require(rejected&&d.save_bytes()==edited&&!d.dirty(),"Truncated format load is atomic");invalid=Chunk::parse(original);invalid.children.push_back(*invalid.find("guid"));rejected=false;try{d.load(invalid.encode());}catch(const std::exception&){rejected=true;}require(rejected&&d.save_bytes()==edited,"Ambiguous identity load is atomic");invalid=Chunk::parse(original);invalid.find("data")->data.pop_back();rejected=false;try{d.load(invalid.encode());}catch(const std::exception&){rejected=true;}require(rejected&&d.save_bytes()==edited,"Partial PCM frame rejected atomically");
    const auto scenario=base/L"Scenario";std::filesystem::create_directories(scenario);write_file_atomic((scenario/L"SfxCow.wvp").wstring(),original);write_file_atomic((scenario/L"SfxCow.sgp").wstring(),read_file(segmentPath));Framework host;host.open_segment((scenario/L"SfxCow.sgp").wstring());const auto wi=host.open_wave((scenario/L"SfxCow.wvp").wstring());require(host.waves().size()==1&&host.open_wave((scenario/L"SfxCow.wvp").wstring())==wi,"Wave catalog owns one instance per path");require(host.playback_waves(0).at(0).bytes==original,"Segment Wave reference resolves catalog identity and PCM");host.save_project((scenario/L"Scenario.pro").wstring());const auto projectBefore=read_file((scenario/L"Scenario.pro").wstring());const auto native=Chunk::parse(projectBefore);size_t references=0;bool waveEntry=false;for(const auto& c:native.children)if(c.id=="LIST"&&c.type=="file"){++references;if(decode_utf16(c.find("name")->data)==L"SfxCow.wvp"){waveEntry=true;require(decode_utf16(c.find("LIST","UNFO")->find("rnam")->data)==L"SfxCow.wav","Wave native runtime filename uses .wav");}}require(references==2&&waveEntry,"Native Project contains owned Wave and Segment entries");Framework reload;reload.open_project((scenario/L"Scenario.pro").wstring());require(reload.waves().size()==1&&reload.wave_document(0).save_bytes()==original&&!reload.dirty(),"Native Project reload owns WVP losslessly");require(reload.wave_document(0).set_properties(L"Cow edited",64)&&reload.dirty(),"Wave edit participates in Framework dirty state");require(reload.playback_waves(0).at(0).bytes==edited,"Resolver exposes owned edited snapshot rather than old disk");rejected=false;try{reload.save_project((scenario/L"Scenario.pro").wstring());}catch(const std::exception&){rejected=true;}require(rejected&&read_file((scenario/L"Scenario.pro").wstring())==projectBefore,"Dirty Wave blocks Project save without replacing metadata");reload.save_wave(0,(scenario/L"SfxCow.wvp").wstring());reload.save_project((scenario/L"Scenario.pro").wstring());Framework again;again.open_project((scenario/L"Scenario.pro").wstring());require(again.wave_document(0).save_bytes()==edited&&again.playback_waves(0).at(0).bytes==edited&&!again.dirty(),"Wave edit/save/native metadata refresh/separate host restoration");
    auto song=Chunk::parse(read_file(segmentPath));auto& wave=song.find("LIST","trkl")->children.at(0);Chunk* reference=nullptr;std::function<void(Chunk&)> find=[&](Chunk& c){if(c.id=="LIST"&&c.type=="DMRF"&&c.find("file")&&decode_utf16(c.find("file")->data)==L"SfxCow.wvp")reference=&c;for(auto& child:c.children)find(child);};find(wave);require(reference!=nullptr,"Observed Segment Wave reference located");reference->children.erase(std::remove_if(reference->children.begin(),reference->children.end(),[](const Chunk& c){return c.id=="file";}),reference->children.end());again.document(0).load(song.encode());require(again.playback_waves(0).at(0).bytes==edited,"GUID-only Wave resolves owned catalog without filename");
    auto other=Chunk::parse(edited);other.find("guid")->data[0]^=1;write_file_atomic((scenario/L"Mismatch.wvp").wstring(),other.encode());reference->children.erase(std::remove_if(reference->children.begin(),reference->children.end(),[](const Chunk& c){return c.id=="guid";}),reference->children.end());Chunk path;path.id="file";path.data=utf16(L"Mismatch.wvp");reference->children.push_back(path);Chunk id;id.id="guid";const auto retainedIdentity=d.identity().value();id.data=Bytes(retainedIdentity.begin(),retainedIdentity.end());reference->children.push_back(id);Framework mismatch;mismatch.open_segment((scenario/L"SfxCow.sgp").wstring());mismatch.document(0).load(song.encode());rejected=false;try{(void)mismatch.playback_waves(0);}catch(const std::exception&){rejected=true;}require(rejected,"Existing filename with wrong Wave identity rejected rather than silently played");
    const auto originalSong=read_file(segmentPath);const std::vector<ResolvedWave> owned{{wavePath,edited,d.format()}};const auto runtime=prepare_wave_playback(originalSong,owned);
    auto expectedSong=Chunk::parse(originalSong);Chunk* expectedReference=nullptr;std::function<void(Chunk&)> locate=[&](Chunk& c){if(c.id=="LIST"&&c.type=="DMRF"&&c.find("file")&&decode_utf16(c.find("file")->data)==L"SfxCow.wvp")expectedReference=&c;for(auto& x:c.children)locate(x);};locate(expectedSong);put32(expectedReference->find("refh")->data,16,3);
    require(runtime.segment==expectedSong.encode()&&runtime.waves.at(0).bytes==edited,"Private Wave mapping changes only reference selection and preserves edited WVP bytes");require(read_file(wavePath)==original&&originalSong==read_file(segmentPath),"Wave playback preflight leaves source files unchanged");
    rejected=false;try{(void)prepare_wave_playback(originalSong,{});}catch(const std::exception&){rejected=true;}require(rejected,"Missing Wave snapshot rejected before runtime");
    auto invalidOwned=owned;auto wrongWave=Chunk::parse(edited);wrongWave.find("guid")->data[0]^=1;invalidOwned[0].bytes=wrongWave.encode();rejected=false;try{(void)prepare_wave_playback(originalSong,invalidOwned);}catch(const std::exception&){rejected=true;}require(rejected,"Wrong Wave GUID snapshot rejected before runtime");
    auto invalidSong=expectedSong;locate(invalidSong);expectedReference->find("refh")->data[0]^=1;rejected=false;try{(void)prepare_wave_playback(invalidSong.encode(),owned);}catch(const std::exception&){rejected=true;}require(rejected,"Wrong Wave runtime class rejected before COM activation");
    invalidSong=Chunk::parse(originalSong);Chunk* itemHeader=nullptr;std::function<void(Chunk&)> item=[&](Chunk& c){if(c.id=="waih")itemHeader=&c;for(auto& x:c.children)item(x);};item(invalidSong);put32(itemHeader->data,24,20000000);put32(itemHeader->data,28,0);rejected=false;try{(void)prepare_wave_playback(invalidSong.encode(),owned);}catch(const std::exception&){rejected=true;}require(rejected,"Start offset beyond PCM rejects before runtime");
    require(owned[0].bytes==edited&&d.save_bytes()==edited&&!d.dirty(),"Failed Wave preflights preserve owned bytes and history checkpoint");
}
