import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'), read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')), bytes=p=>fs.readFileSync(p);
const dir=path.resolve(process.argv[2]??'');if(!process.argv[2])throw Error('Supply GUI evidence directory');
const inputs=read(path.join(dir,'inputs.json')),run=read(inputs.run),build=read(inputs.build);
if(!build.passed||run.cases.some(c=>!c.passed)||hash(bytes(inputs.build))!==run.buildSummarySha256)throw Error('Build/run identity');
for(const s of build.sources)if(hash(bytes(s.path))!==s.sha256||hash(bytes(path.join(build.sourceRoot,s.path)))!==s.sha256)throw Error('Source drift '+s.path);
const exe=build.outputs.find(o=>o.path==='install/bin/Producer.exe');if(hash(bytes(path.join(build.installDirectory,'bin/Producer.exe')))!==exe.sha256)throw Error('EXE drift');
for(const f of inputs.inputs)if(hash(bytes(path.join(dir,'before-'+f.file)))!==f.sha256||hash(bytes(path.join(path.dirname(inputs.run),f.source)))!==f.sha256)throw Error('Input drift '+f.file);
function parse(b,a=0,z=b.length){const out=[];for(let at=a;at<z;){if(at+8>z)throw Error('Header');const id=b.toString('ascii',at,at+4),n=b.readUInt32LE(at+4),end=at+8+n,next=end+(n&1),container=id==='RIFF'||id==='LIST';if(next>z||container&&n<4)throw Error('Bounds');out.push({id,type:container?b.toString('ascii',at+8,at+12):'',data:container?null:Buffer.from(b.subarray(at+8,end)),children:container?parse(b,at+12,end):[],padding:n&1?b[end]:0});at=next;}return out;}
function encode(c){const b=c.data??Buffer.concat([Buffer.from(c.type),...c.children.map(encode)]),h=Buffer.alloc(8);h.write(c.id);h.writeUInt32LE(b.length,4);return Buffer.concat([h,b,...(b.length&1?[Buffer.from([c.padding])]:[])]);}
const child=(c,id,type='')=>{const found=c.children.filter(x=>x.id===id&&(!type||x.type===type));if(found.length!==1)throw Error('Expected unique '+id+type);return found[0];};
const root=f=>{const b=bytes(path.join(dir,f)),r=parse(b);if(r.length!==1||!encode(r[0]).equals(b))throw Error('Roundtrip '+f);return r[0];};
const band=root('before-band.bnp'),instrument=child(child(band,'LIST','lbil'),'LIST','lbin'),bins=child(instrument,'bins'),dls=root('owned.dls'),id=child(dls,'dlid').data;
if(bins.data.readUInt32LE(0)!==73||id.length!==16)throw Error('Fixture');bins.data.writeUInt32LE(256,0);bins.data.writeUInt32LE((bins.data.readUInt32LE(28)|0x63)&~0x1700,28);
const refh=Buffer.alloc(20);Buffer.from('b0f40f48b228d111bef700c04fbf8fef','hex').copy(refh);refh.writeUInt32LE(19,16);
const ref={id:'LIST',type:'DMRF',data:null,children:[{id:'refh',data:refh},{id:'guid',data:id},{id:'file',data:Buffer.from('owned.dls\0','utf16le')}],padding:0};instrument.children.push(ref);
if(!encode(band).equals(bytes(path.join(dir,'band.bnp'))))throw Error('Band changed beyond patch/flags/collection descriptor');
const segment=root('before-playback.sgp'),tracks=child(segment,'LIST','trkl'),bandTracks=tracks.children.filter(t=>t.children.some(x=>x.id==='RIFF'&&x.type==='DMBT'));if(bandTracks.length!==1)throw Error('BandTrack count');const entries=child(child(bandTracks[0],'RIFF','DMBT'),'LIST','lbdl').children.filter(c=>c.type==='lbnd');if(entries.length!==2||child(entries[0],'bd2h').data.readInt32LE(0)!==0)throw Error('Timed fixture');
refh.writeUInt32LE(3,16);ref.children=ref.children.filter(c=>c.id!=='file');const oldBand=child(entries[0],'RIFF','DMBD');entries[0].children[entries[0].children.indexOf(oldBand)]=band;
if(!encode(segment).equals(bytes(path.join(dir,'playback.sgp'))))throw Error('Segment changed beyond Band at time zero');
for(const f of ['owned.dls','project.dmpj'])if(!bytes(path.join(dir,f)).equals(bytes(path.join(dir,'before-'+f))))throw Error('Unrelated input changed '+f);
for(const f of ['band.bnp','playback.sgp'])if(!bytes(path.join(dir,f)).equals(bytes(path.join(dir,'first-saved-'+f))))throw Error('Re-save changed bytes '+f);
const states=read(path.join(dir,'states.json')),screens=[];for(const label of ['project-loaded','patch256','dls-assigned','band-saved','dls-band-copied','segment-saved','project-reloaded','reloaded-gui-play','reloaded-gui-stop','segment-resaved','band-reloaded','band-resaved']){const s=states.find(x=>x.label===label);if(!s?.state.window.app.replaceAll('\\','/').endsWith('/20261002T193427048Z/install/bin/Producer.exe'))throw Error('Window identity '+label);const b=Buffer.from(s.state.screenshots[0].url.split(',')[1],'base64');fs.writeFileSync(path.join(dir,label+'.jpg'),b);screens.push({label,window:s.state.window.id,imageSha256:hash(b)});}
if(new Set(screens.map(s=>s.imageSha256)).size!==screens.length)throw Error('Duplicate stale screenshots');
for(const f of ['first-closed.json','second-closed.json'])if(!read(path.join(dir,f)).absent)throw Error('Window remained');
const proof={schema:1,build:inputs.build,buildSha256:hash(bytes(inputs.build)),run:inputs.run,runSha256:hash(bytes(inputs.run)),exeSha256:exe.sha256,sourceCount:build.sources.length,workspaceSourcesMatched:true,screens,firstWindowClosed:true,secondWindowClosed:true,guiExitCodes:'unverified',bandOnlyPatchFlagsAndCollectionChanged:true,segmentOnlyBandAtZeroChanged:true,projectAndCollectionUnchanged:true,reloadResaveWholeBytesIdentical:true,files:inputs.inputs.map(f=>({file:f.file,beforeSha256:f.sha256,afterSha256:hash(bytes(path.join(dir,f.file)))})),guiPlayStop:'Observed Playing document snapshot then Stopped; command result only, no waveform or human audio confirmation.',limitations:['GUI DLS reference Undo/Redo not exercised','GUI module inventory unverified','Style DLS runtime unexecuted','DLS instrument/region/wave editing incomplete','All eight final gates incomplete'],auditorSha256:hash(bytes(new URL(import.meta.url))),fullAcceptance:false};
fs.writeFileSync(path.join(dir,'unit-audit.json'),JSON.stringify(proof,null,2)+'\n');fs.copyFileSync(new URL(import.meta.url),path.join(dir,'dls-gui-auditor.mjs'));console.log(JSON.stringify({passed:true,exeSha256:exe.sha256,screens:screens.length,proof:path.join(dir,'unit-audit.json')}));
