import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const runPath=path.resolve(process.argv[2]),dir=path.dirname(runPath),read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p).toString().replace(/^\uFEFF/,'')),hash=p=>crypto.createHash('sha256').update(read(p)).digest('hex');
const run=json(runPath);assert(run.passed&&run.exitCode===0&&!run.timedOut);assert.equal(hash(run.buildSummary),run.buildSummarySha256);const build=json(run.buildSummary);assert(build.passed&&build.sourceSnapshotUnchanged);for(const s of build.sources)assert.equal(hash(path.join(build.sourceRoot,s.path)),s.sha256);assert.equal(hash(run.executable),run.executableSha256);for(const i of run.inputs)assert.equal(hash(i.path),i.sha256);
function chunks(b,start,end){const out=[];for(let at=start;at<end;){assert(at+8<=end);const n=b.readUInt32LE(at+4),next=at+8+n+(n&1);assert(next<=end);const id=b.toString('ascii',at,at+4),container=id==='RIFF'||id==='LIST';out.push({id,type:container?b.toString('ascii',at+8,at+12):'',start:at,data:at+8,end:at+8+n,next,children:container?chunks(b,at+12,at+8+n):[]});at=next;}return out;}
const find=(nodes,id,type='')=>{const all=nodes.filter(c=>c.id===id&&(!type||c.type===type));assert.equal(all.length,1);return all[0];};
const base=dir+'/core/motif',original=read(base+'/original.stp'),root=find(chunks(original,0,original.length),'RIFF','DMST'),patterns=root.children.filter(c=>c.id==='LIST'&&c.type==='pttn'),motif=patterns.at(-1),header=find(motif.children,'ptnh'),settings=find(motif.children,'mtfs');
assert.equal(original.readUInt16LE(header.data+6),16);assert.equal(original.readUInt16LE(header.data+8),1);assert.equal(settings.end-settings.data,21);assert.equal(original[settings.end-1],0xad);assert.equal(original[settings.end],0xb7);assert.equal(original.readUInt32LE(settings.data),0);assert.equal(original.readUInt32LE(settings.data+16),1);
const ref=find(find(motif.children,'LIST','pref').children,'prfc'),parts=root.children.filter(c=>c.id==='LIST'&&c.type==='part'),part=parts.at(-1),partHeader=find(part.children,'prth'),notes=find(part.children,'note');assert(original.subarray(ref.data,ref.data+16).equals(original.subarray(partHeader.data+132,partHeader.data+148)));assert.equal(original.readUInt32LE(ref.data+24),5);assert.equal(notes.end-notes.data,4);assert.equal(original.readUInt32LE(notes.data),24);
const source=read(run.inputs.find(i=>path.extname(i.path).toLowerCase()==='.stp').path),sourceRoot=find(chunks(source,0,source.length),'RIFF','DMST');assert.equal(root.children.length,sourceRoot.children.length+2);for(let i=0;i<sourceRoot.children.length;i++){const a=sourceRoot.children[i],b=root.children[i];assert(source.subarray(a.start,a.next).equals(original.subarray(b.start,b.next)));}
const expected=Buffer.from(original);[0xffffffff,384,768,2304,0x81234567].forEach((v,i)=>expected.writeUInt32LE(v,settings.data+4*i));const identities=[];for(const file of ['edited.stp','Heartlnd.stp','resaved.stp']){assert(read(base+'/'+file).equals(expected));identities.push({file,sha256:hash(base+'/'+file)});}
const proof={schema:1,passed:true,checks:run.checks,build:run.buildSummary,executableSha256:run.executableSha256,originalSha256:hash(base+'/original.stp'),identities,auditorSha256:hash(process.argv[1]),scope:'Motif fresh Part/ref/settings shape, original child bytes preserved, five DWORD edit only, native history/Framework save/reload; GUI/runtime/audio/original dynamic comparison/full acceptance unverified',fullAcceptance:false};fs.copyFileSync(process.argv[1],dir+'/motif-auditor.mjs');fs.writeFileSync(dir+'/motif-proof.json',JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify(proof));
